### ISSUE TITLE
Documentation search doesn't work

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey.org#1021]
Steps to reproduce

1. Go to chocolatey.org
1. Click the magnifying glass at the top right hand corner
1. Input a search term
1. Click the `Docs` button
1. You will get the following:

![image](https://user-images.githubusercontent.com/1271146/101165934-602f2f80-362f-11eb-86a0-1bf7683e3598.png)

It has correctly redirected to the docs site, but there is nothing listening in that location anymore, since we are now using Algolia to do the searching.

I think it might be best to just remove the search for docs in this location.

@ferventcoder @designxsteph thoughts?

**Comment by steviecoaster** [comment]
Can we...replace that with Algolia??

**Comment by gep13** [comment]
@steviecoaster no, I don't believe that this will be an option.

**Comment by designxsteph** [comment]
@gep13 Ah I had forgot about this! I actually already have a fix for this, to remove it. I will get a PR up this morning.
