### ISSUE TITLE
Broken link to "Getting Started"

### ISSUE THREAD

**Issue by cadoiz** [chocolatey/chocolatey.org#1025]
This causes a "misplaced" 404 Error.

### What You Are Seeing?
Searching for "tag:notepad++" yields to five results including "Chocolatey Software | Gettingstarted
https://chocolatey.org/docs/gettingstarted " (see Screenshot)
![grafik](https://user-images.githubusercontent.com/26270798/101245312-457eb880-370c-11eb-8b44-1b864fb6baad.png)

which points to this wrong link:
     https://www.google.com/url?client=internal-element-cse&cx=013536524443644524775:xv95wv156yw&q=https://chocolatey.org/docs/gettingstarted&sa=U&ved=2ahUKEwj-gKrUgLftAhWcAWMBHTbvDaYQFjADegQIARAB&usg=AOvVaw2aipKuj-2jzO6Lr0gbI38d
which resolves to https://docs.chocolatey.org/docs/gettingstarted → also see Screenshot:
![grafik](https://user-images.githubusercontent.com/26270798/101245277-005a8680-370c-11eb-871f-557cd9263abe.png)

### What is Expected?
This correct link instead: https://www.chocolatey.org/docs/gettingstarted 

### How Did You Get This To Happen? (Steps to Reproduce)
See above

**Comment by gep13** [comment]
Thanks for bringing this up. I believe this is as a result of the recent switch to the new docs site. I will fix this up asap.

**Comment by gep13** [comment]
@cadoiz I have fixed the issue with the redirect, and this should be live on the site soon.

@designxsteph I think there is another change in here, related to the earlier [issue](https://github.com/chocolatey/chocolatey.org/issues/1021), namely I don't think we want to see the `View Site Results` section as all anymore, right?

@ferventcoder thoughts?

**Comment by ferventcoder** [comment]
This was a bad link that didn't get produced correctly it appears - something in the switchover from processing in wiki docs to cshtml to just keeping them in markdown. Hmmm

**Comment by ferventcoder** [comment]
I thought we removed the site results from the search.

**Comment by gep13** [comment]
> @ferventcoder said...
I thought we removed the site results from the search.

We have removed most of it, i.e. the Documetation Controller, and all the routes etc.  This seems to be a direct inclusion of the results from Google Search, and works stand alone from everything else.  I think it should be removed, but wanted to get a validation that it wasn't _needed_.

**Comment by designxsteph** [comment]
@gep13 @ferventcoder I had left those results (the tab to site results) mainly being because the google search is searching the whole site not just the docs. I'd be happy to remove that all together if that's what is wanted.

**Comment by gep13** [comment]
@designxsteph that is a fair point about searching the site content, so not sure how best to proceed with this. @ferventcoder what are your thoughts?

**Comment by ferventcoder** [comment]
How many redirectfroms can we have? I'd prefer to try to cover them for sure

**Comment by ferventcoder** [comment]
Given we were the bad actor on our side and those links *did* work, we want to try to capture them as they come up in most cases.

**Comment by designxsteph** [comment]
> @designxsteph that is a fair point about searching the site content, so not sure how best to proceed with this. @ferventcoder what are your thoughts?

I've got the confirmation to remove the tab. I've created an issue here: https://github.com/chocolatey/chocolatey.org/issues/1029

**Comment by gep13** [comment]
@ferventcoder I don't believe there is any limit on the amount of redirects that we have.

**Comment by gep13** [comment]
>@ferventcoder said...
we want to try to capture them as they come up in most cases.

Agreed. This is why I have put in place the custom 404 page, and set up a custom report in Google Analytics, so that we can capture the ones that are coming through, and adding redirects as required.

**Comment by gep13** [comment]
@cadoiz thanks for raising this issue.  The link in question here has been addressed.  Let us know if you find any other broken links, and we can get those fixed as well.
