### ISSUE TITLE
Remove Site Results Tab from package results page

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#1029]
With the docs moving over to its own subdomain, the site results tab should be removed as it is slightly confusing.

![Screen Shot 2020-12-09 at 11 23 11 AM](https://user-images.githubusercontent.com/42750725/101664060-05bc1780-3a11-11eb-826a-ddfcb12ad548.png)

**Comment by gep13** [comment]
@designxsteph this is now live on the site.
