### ISSUE TITLE
Don't show packages with *some* versions unlisted as wholly unlisted

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/chocolatey.org#104]
On the Manage My Packages page, if you have unlisted _any_ version of a package, the entire package shows under the "Unlisted" area.
I have some packages that I've unlisted past versions because the package itself had an error in the configuration and I didn't want peoples' machines to be screwed up. Doing this, then going to the Manage My Packages area to see that the _whole_ package is unlisted (when the latest version is still listed and searchable) is really confusing.

**Comment by ferventcoder** [comment]
#173 was marked as a duplicate, but has quite a bit of information and visuals related.
