### ISSUE TITLE
Packages RSS Feed Stopped Working

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#1041]
### What You Are Seeing?

The Community Packages RSS Feed only has up to December 17th in it - http://feeds.feedburner.com/chocolatey. 

![image](https://user-images.githubusercontent.com/63502/103943759-3ff40400-50f8-11eb-9d44-3cfd2e650c57.png)

### What is Expected?

Should see all the latest packages approved.

### How Did You Get This To Happen? (Steps to Reproduce)

Didn't do anything, just stopped working

### References

* https://groups.google.com/d/msgid/chocolatey/8692fdfc-0c24-4256-93df-0f9cc9dd4ce9n%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by gep13** [comment]
@ferventcoder this should now be live on the site.
