### ISSUE TITLE
404 on https://chocolatey.org/products#foss

### ISSUE THREAD

**Issue by augustoproiete** [chocolatey/chocolatey.org#1042]
### What You Are Seeing?

The link under "rigorous moderation review process" in the "[Open Source Chocolatey](https://chocolatey.org/products#foss)" seems to be broken.

![image](https://user-images.githubusercontent.com/177608/104071280-3c877800-51df-11eb-89d5-93da61a15f02.png)

As of this writing, it's pointing to: https://docs.chocolatey.org/en-us/community-repository/maintainers/moderation and I get a 404.

![image](https://user-images.githubusercontent.com/177608/104071462-9b4cf180-51df-11eb-8b55-e274c0c249d5.png)

### What is Expected?

It should Just Work™ :smile:

### How Did You Get This To Happen? (Steps to Reproduce)

https://docs.chocolatey.org/en-us/community-repository/maintainers/moderation

Is suspect the correct link should be:

https://docs.chocolatey.org/en-us/community-repository/moderation/

**Comment by gep13** [comment]
@augustoproiete thanks for pointing this out.  I have updated affected links just now.

Let us know if you find any other broken links.
