### ISSUE TITLE
[Enhancement] Add Approved Status and Approver into Version List

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey.org#111]
On each package page, I think it would be a good idea to include information about the current moderation status and Approver (if there is one) beside each version:

i.e. add some columns here:

![image](https://cloud.githubusercontent.com/assets/1271146/4857382/6f383202-60ce-11e4-8200-9f984228c35d.png)

This will help greatly when it comes to moderating a package, to see if there has already been an approval and by who, so that you can follow up with them if there are any questions/concerns.

**Comment by ferventcoder** [comment]
Deciding not to put approver in but will show status.

**Comment by gep13** [comment]
Hmm, I personally would still like to see it.  Can you be persauded?

If I am coming to a package for the first time, I like to see who previously approved it.  I sort of use that as a gauge as to how closely to inspect the package for approver.  Rightly or wrongly :smile:

**Comment by ferventcoder** [comment]
you can get that info from the click on the log.

**Comment by ferventcoder** [comment]
If you want it, file another issue for it so we don't forget about it.
