### ISSUE TITLE
[Enhancement] Add Package Moderation Checklist to Package page

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey.org#113]
When moderating a package, we should show the moderation checklist directly on the package page, as a reminder of what needs to be done for each package before approving.

**NOTE:** If this issue goes ahead, we need to make sure that any changes to the process are included both here, and on the Chocolatey Wiki (which should have a copy of the checklist as well).  To avoid this duplication, we might want to have a common file

**Comment by ferventcoder** [comment]
I believe this is done, so I'm going to close this one.
