### ISSUE TITLE
Do not allow return rejected packages in results or allow install

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#115]
If someone knows the exact version they are looking for, they could still install a rejected package by passing the name *AND* the version of the package. We've done the work in #211 to remove a copy/paste install box from google searches that bring folks to unlisted/rejected packages. We need to go one step further to ensure that those packages don't show up in the API or are allowed to be installed.

**Comment by gep13** [comment]
:+1:  good work!
