### ISSUE TITLE
Make file list in package description expandable

### ISSUE THREAD

**Issue by glennsarti** [chocolatey/chocolatey.org#133]
Packages which have a large number of files in them make it difficult to read the package description because you have to scroll down the page a long way. Typically, most people are interested in the package description, not the package file list. As an enhancement,  can the number of files displayed be capped at, say, 10 but have a button to expand the full list.  This will give people the ability to see the file list and the package description on most desktop web browers.

**Comment by ferventcoder** [comment]
This is done and will be released today.
