### ISSUE TITLE
[Enhancement] Do not show awaiting moderation message when latest version is approved.

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey.org#148]
_There are versions of this package awaiting moderation_ shows when some versions are not yet moderated, but the latest version is. It gives the visitor a feeling that there are newer versions in the pipeline, but this message stays on when an older version has not yet been moderated.

**Comment by ferventcoder** [comment]
Good point.

**Comment by gep13** [comment]
To confirm, are you talking about "new" older versions, i.e. that haven't been through moderation?

The reason I ask it, there is a package here:

https://chocolatey.org/packages/0ad

That has older package versions, which are not moderated, yet I don't see the dialog at the top of the screen.

**Comment by ferventcoder** [comment]
I think we are talking about when there is a package under moderation (under review) and the newer version may be approved before the older version. Doesn't happen as often, but it does happen. 

When you are on the most recent version, if an older version is under moderation, don't show the message.

**Comment by Redsandro** [comment]
Yes, what he said. :)

**Comment by ferventcoder** [comment]
I actually kind of like seeing this when I've moderated a package. Perhaps we stop showing the message to non-moderators if the latest is approved.

**Comment by djechelon** [comment]
Reopening this issue as a bug.

Today I have visited https://chocolatey.org/packages/tor-browser#versionhistory

From the history of this ticket I understand that the issue was approved, fixed and released in 2015. But now it is occurring again. I was going to report it as an enhancement.
