### ISSUE TITLE
Package moderation guidelines and rules

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey.org#150]
Initiating talks, for now or for later.

>@Redsandro
> I agree with Jean-Philippe that it's unclear when something is a guideline or when it is a rule, as I have experienced myself from time to time. Also, the explanation you (@ferventcoder) gave about when to use what alternative version number is something that would look good in the wiki itself.
>
Based on how we moderate, I think we should split the guidelines into rules and recommendations. We need to uphold a certain quality and unity, but it's frustrating for maintainers volunteering to fix a package based on something the recommendation seems to allow for, and then have us moderators say it must be different.

.

> @gep13 
We need to make things clear, but in order to do this, I think that we need to all be in agreement, so that we can stick to them.
>
Happy to work with you to start defining this.
>
I would suggest creating an issue on Chocolatey GitHub so that we can start conversation.

**Package Fix Notation Submissions**
* Date Notation Only
  * @gep13
* Incremental Notation Only
* Allow both
  * @Redsandro

**Comment by Redsandro** [comment]
I am not sure about the limitations of the nuget method, but I dislike the date notation for a fixed release too. However, iirc, the wiki suggests the date but alternatively suggests adding a number (vRelease.number).

First of all, we either need to accept packages with both numberings, or we need to remove the rejected version numbering from the wiki.

**Comment by gep13** [comment]
Since in most cases a Chocolatey Package is just a wrapper around someone elses application, which is versioned separately, there are times when the versions don't match.  

When a change in version number is required, i.e. the Chocolatey Package needs to be updated due to a bug, but nothing in the underlying application has changed, we need to make it as **clear** as possible that the underlying application hasn't changed.

In my opinion, this is **best** way to indicate that the package has changed, not the application.

For example, let's take an application called ApplicationA which is at version 2.0.0.  Someone comes along and creates a Chocolatey Package for ApplicationA with version 2.0.0.  All things are good.

The next day, someone notices that there is something wrong with the Chocolatey Package, and they want to release a new version of it.  They have two options, either create a Chocolatey Package with a version of ```2.0.0.1``` or ``2.0.0.20150110```.

Now, in my opinion, the latter is very clear, and understood.  There was a change to the Chocolatey Package on the 10th January 2015.  The former could suggest that the underlying application changed.  This is not good.

I would vote for recommending **only** a package fix notation using the date format.

**Comment by gep13** [comment]
I have updated the first post in this discussion with a rudimentary voting mechanism.

**Comment by Redsandro** [comment]
I don't like both. Since I now know we can push the same version, can't we just push a fix to the same version if it's broken so that the version corresponds to the actual developer version?

**Comment by gep13** [comment]
You can only push the same version **while** in moderation. Once it is approved, you cant push the same version again.  Pushing the same version only works if problems are caught during moderation.

Take the example of the additions to the tor-browser that you did. The application version was already pushed and approved, so we had to adopt the package fix notation, in order to create a new package with the additional supported languages.

Sent from my Windows Phone
________________________________

**Comment by ferventcoder** [comment]
The ruby packages are a good location for when incremental fix version notation has been used (or when all four version segments are used).

**Comment by Redsandro** [comment]
@gep13 I understand, but isn't that because @ferventcoder developed it that way?

__Fist choice__

Ideally, I would like to see that the approved version will be in the gallery, and the same version number that is pushed as a fix will be in the moderation queue, and will replace the previous one once approved.

But I don't know if the system allows to (easily) be adopted to that.

__Second choice__

I don't know if the version number can have some regex change to allow for this, but my main concern is that I like to have a version number be that of a commonly known original version number. So if Vagrant stays at 1.7.2 for a while, and as a developer you know there has been an important change between 1.7.0 and 1.7.2, the package should be identifiable as 1.7.2. So if a fix would be needed, I would prefer something like:

* 1.7.2-chocolatey2
* 1.7.2-0109

... and mark the second part as less important in gallery- and installer options:

_Installing **Vagrant 1.7.2**-chocolatey2_

__Third choice__

Leave it up to the discretion of the package maintainer. Aka allow both.

Moreover, no matter what we choose, I think it's wrong to moderate different from the instructions. If the wiki says both is fine (or whatever other instruction allows for interpretation), and as a moderator we don't like it, we're gonna have to allow it once and change the instructions so it won't happen in the future.

These people volunteer to do something, and it's in my opinion tremendously annoying to have to change things that weren't explicitly indicated. Most people mean well, follow instructions to the best of their knowledge (a "guideline" sounds like an "example" but it sounds like there is maintainer choice) and we can reward them by sounding friendly:

> Thanks for the package fix! We have added it to the gallery. 
> 
The chocolatey gods have decided that they like to use the "something something" version notation in the future because of [reason]. We have changed the wiki to reflect this.

Once an instruction is written clearly, we can just point to it and ask them to repush following the instructions.

**Comment by ferventcoder** [comment]
>__First Choice__

>Ideally, I would like to see that the approved version will be in the gallery, and the same version number that is pushed as a fix will be in the moderation queue, and will replace the previous one once approved.

>But I don't know if the system allows to (easily) be adopted to that.

Package version immutability. You can't expect someone who has already installed a version to know to reinstall the same version of a package or know that there was a change to the same version. Plus it is not deterministic. Some people may have the broken one, or the fixed one. There may be breakages in the newer version.  Installing the same version of a package **should** always produce the same result, even if that means it is broken.

Package version immutability is a long well-known concept. A package version, once approved, cannot change. Will not change. It's not up for discussion. That's not a design decision, that's a core concept of package management.

**Comment by Redsandro** [comment]
Okay, sorry I brought it up! :runner:

**Comment by gep13** [comment]
> I like that some moderators sign their replies. Sometimes I see a comment in the queue and I have no idea who wrote that. Was there already an instructive wiki or issue for moderation guidelines? I remember someone (you?) bringing this issue up but I cannot find it back.

I brought it up here:

https://groups.google.com/forum/#!topic/chocolatey-team/oo2XZhpFZoc

> On second thought, I find the full date notation ugly, but I also find inconsistency ugly. So if we cannot find an alternative and you really think it's best, I'm not gonna raise hell if we decide date notation is the only way from now on. :)

My thoughts on why the date package fix notation is the better choice simply comes down to this.  From looking at it, I can immediately see that something in the **package** has changed, not the underlying application.  If I already have the same **application** version installed, and it is working fine, I have no need to update the **package**.  This is my primary reason for advocating the use of the date package fix notation.

**Comment by ferventcoder** [comment]
I think this closes with the documentation being discussed and add to the wiki.
