### ISSUE TITLE
Contact form should accept and encode < > characters or warn users

### ISSUE THREAD

**Issue by robinminto** [chocolatey/chocolatey.org#155]
I included "Chocolatey Gallery <chocolateywebadmin@googlegroups.com>" in a contact form submission (https://chocolatey.org/packages/araxismerge/2013.4430/ContactAdmins) but got an error.

I re-submitted without < and > and it worked. It'd be nice if the page accepted the message and encoded characters that are considered dangerous or at least warned the user that they're not acceptable.

**Comment by ferventcoder** [comment]
Thanks for reporting this!

**Comment by ferventcoder** [comment]
Most of the time we like to see things come in with gists if possible.

**Comment by ferventcoder** [comment]
But that doesn't mean we shouldn't encode characters properly.

**Comment by robinminto** [comment]
No problem. I can see a gist would have been useful to prevent GitHub encoding the angle brackets!

**Comment by ferventcoder** [comment]
Decided to warn users for now.

**Comment by alexchandel** [comment]
Please reopen, this is still an issue. When using the "Contact Maintainers" link, I need to be able to use angle characters to describe a correction to the Nuget XML metadata. Banning it/forcing me to type `&lt;id&gt;foo&lt;/id&gt;` isn't constructive.

**Comment by ferventcoder** [comment]
Is it a big issue to just send the link to a gist?

**Comment by alexchandel** [comment]
@ferventcoder hah no, but papercuts are painful

**Comment by ferventcoder** [comment]
@alexchandel agreed. Do you want to file a new issue and link to this old one?

**Comment by ferventcoder** [comment]
Follow on https://github.com/chocolatey/chocolatey.org/issues/395
