### ISSUE TITLE
Updates for 0.9.9

### ISSUE THREAD

**Issue by rpavlik** [chocolatey/chocolatey.org#159]
- [x] [Account page](https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/Views/Users/Account.cshtml#L80) - Specifically, to set the API key, probably at least want to add the `choco` command to do it.
- [x] Command badges - install upgrade (with command switches link)
- [x] Documentation link to new repo wiki
- [x] Note about release
- [x] News about breaking changes and pointer to what to read.

**Comment by ferventcoder** [comment]
Yes, plus a few other things. Adding them and renaming this issue. Thanks for creating the issue!
