### ISSUE TITLE
Install from Website should install new choco client

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#163]
Remove some of #162

#162 provided a means to install the last POSH client with - https://chocolatey.org/install-lastposhclient.ps1 (update the install script to point to that).

Give folks a certain amount of time to shift to that if they need to use the older client.

**Comment by alexchandel** [comment]
This is a slight hindrance to both new adopters and existing users wishing to do a fresh install.

Frankly, any automation client that depends on the *text* of some `div` on `https://chocolatey.org` deserves to be mercilessly broken.

I suppose having `https://chocolatey.org/install.ps1` point to an old version for a few weeks is ok, but could the command on the front page please install the latest version?

I can't tell someone `choco` is simple with a straight face when I have to go digging through the wiki to install the latest version.

**Comment by alexchandel** [comment]
In the interim, do you have a one-liner similar to ` @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin` that installs the latest version?

**Comment by gep13** [comment]
`
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/InstallAbsoluteLatest.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
`

**Comment by alexchandel** [comment]
Works! Might be worth it to put this on `https://chocolatey.org` until `https://chocolatey.org/install.ps1` is changed. Otherwise there will be a stream of new users installing an old version, updating, and potentially running into errors (e.g. choco#174).

**Comment by ferventcoder** [comment]
This is complete. It may be a few minutes before the site reflects the new changes.
