### ISSUE TITLE
SSL Mixed-Content issue

### ISSUE THREAD

**Issue by cfoellmann** [chocolatey/chocolatey.org#166]
Gravatar images on chocolatey.org are being loaded via `http://`
Should't https://github.com/chocolatey/chocolatey.org/blob/7b4aad8ddb686e7474cba3ce2e3d507d69dc9bba/chocolatey/Website/App_Code/ViewHelpers.cshtml#L82 solve that?
The replace http://www.gravatar.com/", "https://secure.gravatar.com/" seems to be missing in the processing.

**Comment by ferventcoder** [comment]
So was the issue with gravatars or did #167 really fix this?

**Comment by cfoellmann** [comment]
Sorry. I did not properly separate the issues.
Gravatar issue should still persist. Feedburner should be fixed.

**Comment by cfoellmann** [comment]
I am not sure how the site is deployed but are these issues already online?

**Comment by ferventcoder** [comment]
They are now. If you look at the bottom of the site there is a sha1 and a
time.

On Friday, April 17, 2015, Christian Foellmann <notifications@github.com>
wrote:

> I am not sure how the site is deployed but are these issues already online?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/166#issuecomment-93954899>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by tstuttard** [comment]
Hi am am getting a https certificate warning when browsing to https://chocolatey.org/packages?q=hexchat. This wouldn't be an issue but some networks block traffic to website that have a warning.
I am using google chrome on a windows 10 PC.

![chocolatey org-encryption-issue](https://cloud.githubusercontent.com/assets/3101738/12012937/aa8381d0-ad5e-11e5-9a28-605cfbbff9c6.PNG)

I would like to suggest moving to lets encrypt, as a free secure alternative.

Any suggestions to how I get round this issue would be appreciated!

Tom

**Comment by ferventcoder** [comment]
@tstuttard not sure how lets encrypt applies. You may want to see https://github.com/chocolatey/chocolatey.org/pull/258 and #257 to understand we used to pull in content for images based on packages and the linked iconURL, but now we host them locally if they exist and fallback when they don't. Hexchat's iconurl doesn't actually exist so it's likely why there is a mixed content issue with its image.

**Comment by ferventcoder** [comment]
Actually the iconurl exists. Are you seeing this message on any page of chocolatey.org?

**Comment by tstuttard** [comment]
Hmmm not sure what the issue is then. I know that hexchat's icon is using gravatar without a https link. I am not sure if that would cause the issue though. I will check tomorrow if I can view other pages on chocolaty.org. Thanks for the quick response!

**Comment by ferventcoder** [comment]
@tstuttard I was able to go to the page and didn't run into this. So I'm not sure quite what's up.

**Comment by tstuttard** [comment]
It is working fine now. Not really sure what happened.

**Comment by ferventcoder** [comment]
That's fine. If you run into it again, please let us know.
