### ISSUE TITLE
Remove Description from Manage My Packages

### ISSUE THREAD

**Issue by DanAtkinson** [chocolatey/chocolatey.org#170]
The package description on [Manage My Packages](https://chocolatey.org/account/Packages) contains Markdown markup.

The description should be decoded (into actual HTML) before a substring is applied and then re-encode into HTML afterwards.

![markdown](https://cloud.githubusercontent.com/assets/23440/6869464/3ca5bff8-d48c-11e4-821b-31f718f4313b.png)

**Comment by ferventcoder** [comment]
:+1:

**Comment by ferventcoder** [comment]
I took a look at this, I think I would rather remove the description versus trying to work with a field that could mess up the page if it doesn't include the closing elements of the markdown in question, as we can see from your image and from what I saw when I tinkered with this.
