### ISSUE TITLE
Non-secure content on secure pages

### ISSUE THREAD

**Issue by DanAtkinson** [chocolatey/chocolatey.org#172]
The following page types are loading unsecure content, thus raising security warnings in some browsers:

* Package search page.
 * [Example - 'commitmonitor' search results](https://chocolatey.org/packages?q=commitmonitor)
 * **Warning:** Mixed Content: The page at 'https://chocolatey.org/packages?q=commitmonitor' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://feedburner.google.com/fb/a/mailverify'. This endpoint should be made available over a secure connection.
* Package page.
 * [Example - commitmonitor package](https://chocolatey.org/packages/commitmonitor).
 * **Information:** The non secure elements seem to be because Gravatar images are loaded over HTTP rather than HTTPS.
 * **Warning:** Mixed Content: The page at 'https://chocolatey.org/packages/commitmonitor' was loaded over HTTPS, but requested an insecure image 'http://www.gravatar.com/avatar/fdde6bfaf2716a26937e9f7dd0f5028f?s=32&r=g&d=retro'. This content should also be served over HTTPS.
 * **Warning:** Mixed Content: The page at 'https://chocolatey.org/packages/commitmonitor' was loaded over HTTPS, but requested an insecure image 'http://www.gravatar.com/avatar/031f04f9c9b0de39bfb2d381682f99d2?s=32&r=g&d=retro'. This content should also be served over HTTPS.
 * **Warning:** Mixed Content: The page at 'https://chocolatey.org/packages/commitmonitor' was loaded over HTTPS, but requested an insecure image 'http://www.gravatar.com/avatar/d8f76dc7a42d72dd4481fb3d74ce54dc?s=32&r=g&d=retro'. This content should also be served over HTTPS.

Kind regards, Dan

**Comment by DanAtkinson** [comment]
Linked to #166 - although this issue contains a further bug relating to the feedburner form.

**Comment by ferventcoder** [comment]
Yeah, the feedburner url may be fine just to switch to https

**Comment by DanAtkinson** [comment]
That's cool. I submitted a pull request to fix this issue. The Gravatar issue appears to have a back-story however so I thought it best not to touch it unless I take the time to understand it a little more.

**Comment by ferventcoder** [comment]
Not sure what the backstory is on the gravatar.

**Comment by DanAtkinson** [comment]
There's already some work on this [here](https://github.com/chocolatey/chocolatey.org/blob/21be5689648e274299f364d0082e99a65c58c6c1/chocolatey/Website/App_Code/ViewHelpers.cshtml#L82) and [here](https://github.com/chocolatey/chocolatey.org/blob/21be5689648e274299f364d0082e99a65c58c6c1/nugetgallery/Website/App_Code/ViewHelpers.cshtml#L81) but those changes don't appear to be working (although it looks sound).

I haven't investigated why they're not working although I suppose it's possible that  `Request.IsSecureConnection` is returning false if the web server is being passed non-secure traffic by a load balancer where the SSL certificate actually resides. This seems admittedly far-fetched however!

**Comment by ferventcoder** [comment]
We use appharbor so that is likely the case. We should be checking the appharbor ssl

**Comment by DanAtkinson** [comment]
Then you may have a bigger problem as Request.IsSecureConnection is used across the site.

In any case, I don't see any harm in you automatically returning a secure gravatar image to users on all sites, regardless of whether the connection is secure or not.

In fact, from what I can see, you can't even access the site over HTTP without being redirected to HTTPS!

**Comment by ferventcoder** [comment]
That is correct. That's part of what the appharbor ssl check does.

**Comment by DanAtkinson** [comment]
You could always check for X-Forwarded-Proto.

I've had a quick look and, yes, apparently AppHarbor sites apparently report false on `Request.IsSecureConnection` ([link from 2012](https://support.appharbor.com/discussions/problems/2938-dependency-on-x-forwarded-proto-safe) and [original issue from 2011](https://support.appharbor.com/discussions/problems/1562-requestissecureconnection-always-returns-false)).

**Comment by ferventcoder** [comment]
That's what I mean by using the AppHarbor SSL check.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/MvcOverrides/RequireHttpsAppHarborAttribute.cs

**Comment by DanAtkinson** [comment]
Ah right, sorry! :+1:

This needs to be exposed to the view then to allow IsSecureConnection to be replaced which should then fix anywhere else that it's currently used.

**Comment by ferventcoder** [comment]
:)

**Comment by ferventcoder** [comment]
I will call this a duplicate of #166 since it was filed first.
