### ISSUE TITLE
Chocolatey Automatic Package Review Service

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#181]
Chocolatey.org should perform many of the repetitive tasks for package review, as a computer can do them quite well.

Things for chocolatey auto review service

**NOTE:** The automatic review will never automatically approve a package.

## Failures
- [x] check package name - flag if first version based on the naming convention (doesn't matter if prerelease or not)
- [x] suggest the name split if over 25 chars with no -
- [x] flag on "."" in name (unless .portable/.install)
- [x] check tags, ensure no chocolatey tag unless chocolatey
- [x] request admin if it calls Install-ChocolateyPackage (or uses another admin)
- [x] check for projectUrl
- [ ] check for lots of comment lines in installscripts
- [x] flag the use of any of the following:  `$nugetChocolateyPath
    $nugetPath
    $nugetExePath
    $nugetLibPath
    $badLibPath
    $extensionsPath
    $chocInstallVariableName
    $nugetExe
    $ShimGen
    $checksumExe`
- [x] flag the use of choco install/update in scripts

## Guidelines
- [ ] search for other similarly named packages
- [x] check length of description, ask for more than 30 chars
- [x] check for icon
- [x] check for licenseUrl
- [x] flag authors if same as maintainers
- [x] ask for link to release notes
- [x] Write-ChocolateySuccess
- [x] Write-ChocolateyFailure
- [x] With Get-BinRoot, ask if the user should move to a simpler approach
- [x] flag the use of Program Files installs without admin access

**Comment by ferventcoder** [comment]
@gep13 thoughts as to these?

**Comment by gep13** [comment]
This looks good to me.

Other things to look at/think about:

* Flag on direct inclusion of exe/dll's (to prevent inclusion of non-disruptable content)
* BOM in files?
* UTF-8 encoding?

**Comment by ferventcoder** [comment]
Sounds good. Anything you can think of, also make sure whether it is a HOLDING issue or a recommendation to fix at convenience.

**Comment by DanAtkinson** [comment]
* Perform a HTTP request on the install resource url(s) to ensure that they're valid links.
* If the install url contains `x86` or `x64` then we should check that both are being offered and flag if only one option is given in the chocolateyInstall.ps1.
* Consider flagging for human review if install links do not contain a version number (possibly performing a regex match on the version number provided in the `.nupkg`). Forcing external providers to following semver probably isn't possible, but ideally, install links should not point to the 'latest' directory http://danbosoft.com/latest/awesome.exe as this could cause a disparity in chocolately install versions and make identifying issues somewhat difficult.

**Comment by DanAtkinson** [comment]
I think that it'd be a very good idea to code a simple first-pass of most of these rules on the existing moderation queue to identify packages with the most basic problems. This should reduce the queue size significantly until these issues are fixed, allowing less trivial moderation to take place.

**Comment by ferventcoder** [comment]
@DanAtkinson I think I need to reduce confusion - the automoderation/autoreview does not EVER approve a package.

**Comment by ferventcoder** [comment]
> If the install url contains x86 or x64 then we should check that both are being offered and flag if only one option is given in the chocolateyInstall.ps1.

This is nearly impossible to do. It involves screen scraping foreign HTML pages. This would make a good human thing to add though.

**Comment by DanAtkinson** [comment]
Sorry, I meant a check of the url(s) in the chocolateyInstall.ps1. I figured that the existence of `x86` in the package url would imply (although not guarantee) the existence of an `x64` version and vice versa. Then, all we'd have have to do is check whether both are provided and flag accordingly.

**Comment by ferventcoder** [comment]
Ah right on. Yeah I think we'd check to see if they exist. :)

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/package-validator/issues/3

**Comment by ferventcoder** [comment]
This has a new repo and anything not implemented has a ticket over on that repo. https://github.com/chocolatey/package-validator

Closing.
