### ISSUE TITLE
Fix package moderation comments readability

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey.org#183]
![Package Comments](https://cloud.githubusercontent.com/assets/63502/7543258/c2c0abbc-f588-11e4-8cac-4c57b03671f8.png)

Looks messy. Vertical-align top everything and separate comments visually (e.g. (alternating row) grid-view).

**Comment by designxsteph** [comment]
This has been addressed here https://github.com/chocolatey/chocolatey.org/commit/fef90e47d434e16c377b74dca82f8c3e3a113142
