### ISSUE TITLE
Automate duplicate package finder for moderation.

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey.org#184]
It still happens that already existing packages get created anew, and they slip through the moderation process. This will get harder as the gallery contains more packages.

Suggested feature in moderation view: Auto-search the database for the name and title. Add message: Is this package a duplicate of [xxx]?

**Comment by DanAtkinson** [comment]
:+1:

**Comment by ferventcoder** [comment]
This will be done with the validator - https://github.com/chocolatey/package-validator/issues/73

Closing this for that issue.
