### ISSUE TITLE
Should a package review comments show for non-mods/admins/package maintainers?

### ISSUE THREAD

**Issue by DanAtkinson** [chocolatey/chocolatey.org#189]
**Steps to reproduce:**

* Open the [RabbitMQ 3.5.1](https://chocolatey.org/packages/rabbitmq/3.5.1) package in an incognito window (or browser that you are not logged into Chocolatey with).
* See screengrab below.

**What I expect to see:**

* No package review messages. Unless I'm logged in as either an admin, moderator or the package maintainer, I should not see package moderation comments.

![image](https://cloud.githubusercontent.com/assets/23440/7667117/0aa87fe6-fbf5-11e4-8fd1-de9a37a05b42.png)

**Comment by ferventcoder** [comment]
That is actually expected. This way it gives transparency to users
