### ISSUE TITLE
[Enhancement] Chocolatey twitter feed should credit folks by their twitter account (if they've filled out their profile)

### ISSUE THREAD

**Issue by zippy1981** [chocolatey/chocolatey.org#20]
The chocolatey page now collects peoples twitter profiles amongst other things. The @chocolatey tweeets should @mention the author of a package if they populate that field.

**Comment by ferventcoder** [comment]
Revisiting - I don't think we'll do this for now as there could be multiple maintainers and it is hard to credit the twitter account.
