### ISSUE TITLE
Add cmd file to download and install choco

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#201]
This is the batch file method, but the file is kept at a URL - see https://github.com/chocolatey/choco/wiki/Installation#powershell-through-batch-method

**Comment by ferventcoder** [comment]
@TheBigBear How is this? 
![image](https://cloud.githubusercontent.com/assets/63502/8635177/05208550-27dd-11e5-9abd-5cec4a6dd60d.png)

**Comment by ferventcoder** [comment]
```
C:\codelocal\chocolatey.org [master +0 ~3 -0]> curl -O http://localhost:55881/installChocolatey.cmd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   409  100   409    0     0   3752      0 --:--:-- --:--:-- --:--:--  3752
```

**Comment by ferventcoder** [comment]
@TheBigBear and it is live - https://chocolatey.org/installChocolatey.cmd

**Comment by TheBigBear** [comment]
@ferventcoder smashing! Thanks, much appreciated.

**Comment by ferventcoder** [comment]
Glad to have helped. :)
