### ISSUE TITLE
Intermitent error when doing several pack and push in parallel: "The process cannot access the file"

### ISSUE THREAD

**Issue by jpascas** [chocolatey/chocolatey.org#208]
I'm using powershell to issuing several Choco Pack's and Push's commands in the same machine in parallel and some times i got the following error:

> The process cannot access the file 'C:\ProgramData\chocolatey\config\chocolatey.config' because it is being used by another process.

For example on a Push i got this error:

> Error deserializing response of type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
The process cannot access the file 'C:\ProgramData\chocolatey\config\chocolatey.config' because it is being used by another process.
The process cannot access the file 'C:\ProgramData\chocolatey\config\chocolatey.config' because it is being used by another process.
+   + Error pushing package with version X

I understand the need to access the file on Installs but i don't understand why it need it on Packs and Pushs.

does anyone have idea how to solve it?

**Comment by ferventcoder** [comment]
This is not an issue with chocolatey.org, but an issue with choco - please follow these issues:

* https://github.com/chocolatey/choco/issues/364
* https://github.com/chocolatey/choco/issues/355
