### ISSUE TITLE
Choco upgrade information out of date on homepage

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#209]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chocolatey/5gMpSWUDQ1g/48D5MoS8BQAJ

> This text on the home page (https://chocolatey.org/) seems to be outdated:
> "chocolatey update (cup) to get the latest version of chocolatey"
> 
> Not only update is now called upgrade, but running "cup" just prints a warning:
> "Package name is required. Please pass at least one package name to upgrade."

**Comment by designxsteph** [comment]
This has been implemented here https://github.com/chocolatey/chocolatey.org/commit/fa39e98a804534858a0093376db62824150a7f02 and https://github.com/chocolatey/chocolatey.org/commit/a61409b097c9fb2c293e582ed32b314d7544967a
