### ISSUE TITLE
Package review process should take place on the site

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey.org#214]
We all have certain passions, and certain things we really _really_ couldn't care less about. I'm hypothesizing that although we all have _different_ packages that we are passionate about, we _all_ have a huge amount of packages that we would personally flag as either "irrelevant" or even "crap".

When a moderator is - temporary or permanently - having a busy life, reading the vast stream of mails to filter out the packages you personally find most valuable and willing to verify, or searching for the ones where you are personally mentioned or addressed as a moderator, becomes too tedious of a job and the moderator becomes tempted to swipe all (AKA ignore all or mark as read).

I propose that one should have the option to mark certain packages and only receive correspondence about them. This preference should also traverse to the moderation queue so that you only see packages relevant to your interests in the moderation queue.

This is probably not benefiting new, less known, and irrelevant packages. But at least it would give attention to some packages, and as it is now, we're still dealing with a huge backlog, even on more popular packages.

**Comment by ferventcoder** [comment]
I think this is valuable. In as much as I've attempted to reduce the email traffic, I don't believe we've done quite enough. And it will get worse. What I'm looking to do is keep the record of emails on chocolatey.org itself, but allow for the package moderation emails to go back and forth directly between a maintainer and only that moderator.

**Comment by ferventcoder** [comment]
@Redsandro I think you'll find this much more to your liking.
