### ISSUE TITLE
Implement Better Caching Techniques

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey.org#231]
I'm on a 200/200 line and chocolatey.org is craaaaazy slow right now.
This happens more often here in the Netherlands, but it becomes especially apparent when pushing or moderating packages. 

The rest of the internet works lightning fast.

**Comment by ferventcoder** [comment]
Has this improved? There seems to be a very large usage that we hoped to improve with the addition of a CDN last week.

**Comment by Redsandro** [comment]
It seems to be snappy right now. But I must admit that when I made this issue, it was like the server was switching between snappy and stone age every ~ 10 minutes.

**Comment by Redsandro** [comment]
Still snappy. Closing for now.

Any stats? Curious where they discovered chocolatey and made large usage. :smile:

**Comment by Redsandro** [comment]
It's back. :cry: 

![image](https://cloud.githubusercontent.com/assets/1702193/10604060/4044f546-7722-11e5-8e47-c48ad60d7dec.png)

**Comment by lawre** [comment]
I'm getting the "we broke something" page today.  Also, I am unable to 'cinst package', I get the following error:

C:\WINDOWS\system32>cinst winmerge
Installing the following packages:
winmerge
By installing you accept licenses for the packages.
winmerge not installed. An error occurred during installation:
 Unable to read package from path 'winmerge.2.14.0.nupkg'.
The install of winmerge was NOT successful.
winmerge not installed. An error occurred during installation:
 Unable to read package from path 'winmerge.2.14.0.nupkg'.

**Comment by ferventcoder** [comment]
Working on this right now. Should have a solution in place soon for this :+1:

**Comment by Redsandro** [comment]
You have been busy. :+1:

**Comment by ferventcoder** [comment]
Next is to flip the caching to something like Memcached.

**Comment by ferventcoder** [comment]
So the downside is that the first person in is hit with warming up the cache, but every request after that will be snappy.

**Comment by ferventcoder** [comment]
I also increased the command timeout to remove the oh no we broke something that has been killing it.
