### ISSUE TITLE
Website package upload stays on upload page when submitted

### ISSUE THREAD

**Issue by kendaleiv** [chocolatey/chocolatey.org#233]
While logged in, when uploading a file at https://chocolatey.org/packages/upload for a package that already exists the browser displays the same page, rather than going onto the next step.

I don't know what happens for creating a package that does not already exist.

The `choco push` command seems to work OK, though.

--

![image](https://cloud.githubusercontent.com/assets/1012917/10707397/fc20a4c8-79bf-11e5-98cd-0d5682c7c0a4.png)

**Comment by ferventcoder** [comment]
Thanks for logging this!

**Comment by ferventcoder** [comment]
I've tracked this down to something related to CloudFlare and have filed an issue with them to followup. It works everywhere else including the test site - https://chocotest.apphb.com.

**Comment by svnpenn** [comment]
https://github.com/chocolatey/chocolatey.org/issues/252

**Comment by ferventcoder** [comment]
I found the issue - it was related to locking down the bucket policy as part of the work I did for setting up CloudFlare - I had locked down my bucket policy and so it was getting access denied errors looking for files. I resolved this just now by including the AppHarbor IPs in the policy (listed at https://support.appharbor.com/kb/tips-and-tricks/application-server-ips-ec2-configuration).

**Comment by svnpenn** [comment]
@ferventcoder I can upload now, but the page for the new package only shows if I am logged in, else I get a 404

http://chocolatey.org/packages/kid3/3.3

**Comment by ferventcoder** [comment]
@svnpenn caching related. It will clear up fully within the timeout period. We are still working out the kinks on this aspect. #256 is likely related.

**Comment by svnpenn** [comment]
https://github.com/chocolatey/chocolatey.org/issues/251

**Comment by ferventcoder** [comment]
@simoncropp
