### ISSUE TITLE
When deleting a package on chocolatey.org it doesn't hide it

### ISSUE THREAD

**Issue by glennsarti** [chocolatey/chocolatey.org#237]
When trying to delete (hide) a package version using Chocolatey.org, the website shows no error and package is not hidden.

HTTP request to .../delete returns a 302.  Not sure if this is expected behaviour

Related to issue #231

**Comment by ferventcoder** [comment]
It's actually removed, but the cache isn't updating.

**Comment by ferventcoder** [comment]
I just went in an hid a package to see. The package is actually hidden now, but the cache hasn't updated.

**Comment by glennsarti** [comment]
How long is the cache timeout? Might be worth ammending the delete page to say it may take up to xxxx minutes for the delete to take affect?

**Comment by ferventcoder** [comment]
It's considered a bug still, the cache should be cleared immediately.

**Comment by glennsarti** [comment]
Hrmm ok...did you want to keep this issue open?

**Comment by ferventcoder** [comment]
Yes, it's a bug until it is fixed.

**Comment by ericoporto** [comment]
how does one delete a package?

**Comment by gep13** [comment]
@ericoporto the best advice would be to unlist a package version, which you as the package maintainer would be able to do. Deleting a package can be done, but not something we do unless there is a compelling reason to do so.
