### ISSUE TITLE
Chocolatey MySQL Package

### ISSUE THREAD

**Issue by GwenaelPellenMatelli** [chocolatey/chocolatey.org#241]
Hi.

in tools\chocolateyInstall.ps1 in package, line 5 and 6

$url = 'http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.7.9-win32.zip'
$url64 = 'http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.7.9-winx64.zip'

can you replace by

$url = 'http://cdn.mysql.com/Downloads/MySQL-5.7/mysql-5.7.9-win32.zip'
$url64 = 'http://cdn.mysql.com/Downloads/MySQL-5.7/mysql-5.7.9-winx64.zip'

Best regards.

**Comment by ferventcoder** [comment]
Hi, @GwenaelPellenMatelli. This github repository is for the website, not for the packages. If you want to get that fixed, I'd contact the maintainers from the site form. https://chocolatey.org/packages/mysql

NOTE: I am one of the maintainers, but this is not the right channel for reporting package issues. :)

**Comment by ferventcoder** [comment]
I did just fix this though. Something to keep in mind for next time.

**Comment by GwenaelPellenMatelli** [comment]
I'm sorry, I'll do more research next time.
