### ISSUE TITLE
Allow specific environment variables for installing Chocolatey

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#242]
Allow the following environment variables:

* chocolateyVersion - control what version of Chocolatey is installed - idea came from https://github.com/chocolatey/chocolatey/pull/712
* chocolateyUseWindowsCompression - bypass the download and use of 7zip
* chocolateyProxyLocation - explicit proxy location
* chocolateyProxyUser  / chocolateyProxyPassword - optional credentials for explicit proxy

**Comment by gep13** [comment]
:+1:

**Comment by ferventcoder** [comment]
Updated the Wiki https://github.com/chocolatey/choco/wiki/Installation/04b694c834af85e8e95630e4252b9f4f609715e6
