### ISSUE TITLE
Chocolatey.org down during middle of workday

### ISSUE THREAD

**Issue by The1nternet** [chocolatey/chocolatey.org#243]
Hi, chocolatey.org is down, and the site says it is down for maintenance.  It is 12:23 pm, and we use chocolatey during the day for deploying our software to our customers, so we are unable to do any deployments while it is down.  Why is maintenance happening during the work day?  Can the maintenance be moved to a time not during the work day?  When will chocolatey.org be back online?

**Comment by lawre** [comment]
Same here.  Seems the site has been having issues for the past two weeks, perhaps this is the "Big Fix"?

**Comment by ferventcoder** [comment]
It was unplanned maintenance.

**Comment by The1nternet** [comment]
Is there an idea of when chocolatey.org will be back up?

**Comment by ferventcoder** [comment]
Honestly didn't expect it to be this long. It should be up soon.

**Comment by ferventcoder** [comment]
I'll leave a comment as soon as it is coming back up.

**Comment by ferventcoder** [comment]
Okay, queued up. Let's see how this comes up

**Comment by ferventcoder** [comment]
Hoping you got the message earlier. Things have leveled out.

**Comment by The1nternet** [comment]
I see it's up now.  Thanks for the notifications!
