### ISSUE TITLE
Newsletter signup Ux could be better

### ISSUE THREAD

**Issue by mwrock** [chocolatey/chocolatey.org#245]
I wanted to sign up for the newsleter and noticed that the "Sign Up for the Newsletter" link does not go anywhere.

**Comment by gep13** [comment]
Not sure that is meant to be a link. The intention "I think" is for you to enter your email in the textbox to the right, and then hit subscribe, which will then take you through to a mailchimp sign up form.

Sent from my Windows Phone
________________________________

**Comment by mwrock** [comment]
ok. I'm just going to go check myself into the local rest home because obviously I can't see anymore. Tanks @gep13 !

**Comment by gep13** [comment]
Ha ha, not  a problem at all.  I wonder if we should keep this open.  Perhaps rather than saying:

```
Sign up for the Newsletter!
Be the first to know about upcoming features, security releases, and news about Chocolatey.
```

Maybe it should say something like:

```
Sign up for the Newsletter!
Enter your email address and click subscribe, to be the first to know about upcoming features, security releases, and news about Chocolatey.
```

Thoughts?

**Comment by mwrock** [comment]
Yeah I think that would be great. It kind of blends in as it is now.

**Comment by designxsteph** [comment]
This has been first implemented here https://github.com/chocolatey/chocolatey.org/commit/874844c91c481777c70c9122f2c18e3010fd59c1
