### ISSUE TITLE
Search on chocolatey.org should search package names only by default, with option to search description as well

### ISSUE THREAD

**Issue by i-give-up** [chocolatey/chocolatey.org#247]
The logic goes that if a user searches `python` on chocolatey.org, chance are they are looking for python packages. Currently the search result also includes other packages 

- chocolatey
- youtube-dl
- tortoisehg
- qbittorrent

So my proposal is to search only package names by default, and having a dropdown list to let users choose to search names + description.

What do you think?

**Comment by ferventcoder** [comment]
Already exists, not yet advertised - use `id:name` e.g. `id:python`

You can also do this from choco.exe. Another one you can use is `tag:`

**Comment by ferventcoder** [comment]
I just added these in the last week while fixing other things.

**Comment by ferventcoder** [comment]
I think with the `id:` searching, this would be the preferred option. We'll need to expose it so folks know they can search for it.
