### ISSUE TITLE
Tweak cache times

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#251]
Tweak cache times to very specific intervals

- [x] Default cache time - 1 hour
- [x] V2 Feed Services - 25 minutes
- [x] PackageService Invalidating items - 3 hours
- [x] Maintainer profile packages - 30 minutes

**Comment by svnpenn** [comment]
https://github.com/chocolatey/chocolatey.org/issues/252

**Comment by svnpenn** [comment]
https://github.com/chocolatey/chocolatey.org/issues/233

**Comment by svnpenn** [comment]
https://github.com/chocolatey/chocolatey.org/issues/256

**Comment by ferventcoder** [comment]
@svnpenn why are these comments showing up?

**Comment by svnpenn** [comment]
@ferventcoder I linked some related issues.

**Comment by ferventcoder** [comment]
@svnpenn I've been watching this happen several times. You add and delete the statuses very quickly. It looks like some sort of bot.

**Comment by svnpenn** [comment]
You cannot link two issues unless you make an appropriate comment. However after they are linked you can remove the comment, which I do because it is no longer needed. No bot, you just click "Comment", then "Delete comment".
