### ISSUE TITLE
Caching messing with installing newly available packages

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#256]

**Comment by svnpenn** [comment]
https://github.com/chocolatey/chocolatey.org/issues/233

**Comment by ferventcoder** [comment]
Some of this will be fixed by https://github.com/chocolatey/chocolatey.org/issues/251

**Comment by ferventcoder** [comment]
Where things can be invalidated, it will fix things up.

**Comment by svnpenn** [comment]
https://github.com/chocolatey/chocolatey.org/issues/252

**Comment by ferventcoder** [comment]
I think this is resolved with 2636100861a907cf399b1b9d01e6e52d23443eb1. We'll watch and wait to see to be sure.
