### ISSUE TITLE
Highlight package name on its page

### ISSUE THREAD

**Issue by yurikoles** [chocolatey/chocolatey.org#264]
It will be useful to have copy-to-clipboard button near commands to install/upgrade a package.

**Comment by ferventcoder** [comment]
Can you expand a bit on the highlight package name part?

**Comment by yurikoles** [comment]
My original concern was about versions awaiting approval. There is no way to quickly copy package name. 

Also, it will be good to have way to install non-moderated version via quick command.

**Comment by ferventcoder** [comment]
@yurikoles This is on purpose and due to security reasons will not be changed - https://github.com/chocolatey/chocolatey.org/issues/211

**Comment by ferventcoder** [comment]
However if you want to have a copy button near those, I can definitely update this issue for that.

**Comment by designxsteph** [comment]
This has been implemented here https://github.com/chocolatey/chocolatey.org/commit/f57d269e36235eb7b64f2282d6dc573ede945b18
