### ISSUE TITLE
Hold trusted packages until testing has completed

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#265]
Even trusted packages will need to have testing run on them. Which could provide emails back to the folks who are pushing them if there are errors - this will provide a nice buffer in case there are issues with the package that need to be resolved before the trusted package is immutable.

**Comment by gep13** [comment]
This makes a lot of sense! :+1:

**Comment by ferventcoder** [comment]
We will start testing and not holding, on Feb 1 (or awhile after we've sent a message to all maintainers, we will start holding for failures).

**Comment by ferventcoder** [comment]
#308 for the later holding of packages until they pass both validation and verification.
