### ISSUE TITLE
Unlisted Packages are showing up on Package Page

### ISSUE THREAD

**Issue by RickStrahl** [chocolatey/chocolatey.org#269]
I have one package that has an unlisted version. When I view the page without being logged on however I still see the unlisted package.

Example: 
**WestwindHtmlHelpBuilder Version 5.0.143**
https://chocolatey.org/packages/WestwindHtmlHelpBuilder

That version is supposed to be unlisted (shows Listed as no when I'm in my admin panel) but when I go to the main page of the package I see it listed and can drill into the actual package detail.

Expected:
Package should not show in listing of available packages on the list page

**Comment by ferventcoder** [comment]
I think this was caused by this change - 43096df8437f54c092af492b9b5c1a8007c3a97c

**Comment by ferventcoder** [comment]
This has been fixed and deployed. Unlisted versions no longer show up if you are not the maintainer:
![image](https://cloud.githubusercontent.com/assets/63502/11415557/3cbec7ac-93ca-11e5-942c-958fc31efe5a.png)

If someone finds their way to the unlisted version, they will see this note:

![image](https://cloud.githubusercontent.com/assets/63502/11415540/fc676b1e-93c9-11e5-9ad5-4140fb384dad.png)

cc @aronovgj

**Comment by RickStrahl** [comment]
Thanks for fixing.

Unfortunately something is broken now - I can't access the pacakge now (after a search):

![image](https://cloud.githubusercontent.com/assets/1374013/11419392/f6e86318-93ca-11e5-8a9e-fc5b9162ee02.png)

**Comment by aronovgj** [comment]
Yep, seems like no package can be accessed. Home works though.

**Comment by ferventcoder** [comment]
It looks like there was an issue with one of the two servers in the load balancer. It didn't come up quite right, so you had a 50% chance of something failing. This was on AppHarbor side. I saw a little bit of this last night but was waiting to see if it came up (it takes about 15-30 minutes to even out with the cache after a deploy). I saw things working for the most part and mistakenly thought it was good to go.

The error logs point out that it was some issue in the automatic configuration. I'm going to look into getting alerts from appharbor when a server is throwing that many errors as a future mitigation.

**Comment by ferventcoder** [comment]
As a followup, we've now implemented a single cache (memcached) and brought back Lucene to reduce/remove pressure on the database itself. This should really materialize in a site with less error messages coming up.

**Comment by RickStrahl** [comment]
I'll check this out on my next update. I did have major caching issues on my last updates a few days ago on the 11th. Same thing - site showed new release but using Choco install would show an old version for maybe a half an hour that I checked.
