### ISSUE TITLE
[Enhancement] Disqus Comment Sends Email to Maintainer(s)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#27]
Set the right variables for the page so that it uses the same discussion for all query strings -  http://help.disqus.com/customer/portal/articles/472098-javascript-configuration-variables 

Notify package maintainers when they have new comments.

**Comment by gep13** [comment]
For this:

> Notify package maintainers when they have new comments.

I think this will help:

https://help.disqus.com/customer/portal/articles/466258-capturing-disqus-commenting-activity-via-callbacks

@ferventcoder has the first part of this issue already been addressed?

**Comment by ferventcoder** [comment]
I believe that was what I was looking at.

On Thursday, January 1, 2015, Gary Ewan Park <notifications@github.com>
wrote:

> For this:
>
> Notify package maintainers when they have new comments.
>
> I think this will help:
>
>
> https://help.disqus.com/customer/portal/articles/466258-capturing-disqus-commenting-activity-via-callbacks
>
> @ferventcoder <https://github.com/ferventcoder> has the first part of
> this issue already been addressed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/27#issuecomment-68499834>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
This was closed by #140
