### ISSUE TITLE
Packages which were pushed before moderation was introduced can't be upgraded or installed

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/chocolatey.org#274]
https://gist.github.com/aronovgj/52ea79c3dfbc11d2f683

**Comment by ferventcoder** [comment]
That explains the other known issue

On Sunday, November 29, 2015, aronovgj <notifications@github.com> wrote:

> https://gist.github.com/aronovgj/52ea79c3dfbc11d2f683
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/274>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
This is prolly caused by #115

**Comment by ferventcoder** [comment]
This should be released in a few minutes.
