### ISSUE TITLE
More useful info in the subject of the moderation mails

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/chocolatey.org#275]
Currently the subject looks like this: `[Chocolatey Gallery] Moderation for 'pkg' v1.0.0`
This tells me nothing except "something happened".

Better would be something like:
[Package Verifier] 'pkg' v1.0.0 verification PASSED

Same goes for any kind of moderation related mails. Actual info about what happened would be better.

Also in the E-mail it says:
`pkg has failed testing.`
What kind of testing? Add as an info that it failed *automatic* testing.

**Comment by ferventcoder** [comment]
> What kind of testing? Add as an info that it failed automatic testing. 

There is a link tho.

Great feedback. I agree.

**Comment by aronovgj** [comment]
This morning at 3 am I got a mail saying
`[Chocolatey Gallery] Package Failure for 'geforce-game-ready-driver' v352.86`
Later at 5 pm I got 
`[Chocolatey Gallery] Moderation for 'geforce-game-ready-driver' v359.06`
Both failed.

Do you have different verifiers running with different configurations?

**Comment by ferventcoder** [comment]
The first is from the existing approved package. The second is the one under review. And yes, we have one going through the existing packages. It will run against existing packages about once every two weeks to ensure that everything is still kosher.

**Comment by ferventcoder** [comment]
Only the latest approved package version though.
