### ISSUE TITLE
Show/Hide in package Files section when a filename is not unique

### ISSUE THREAD

**Issue by bschwede** [chocolatey/chocolatey.org#280]
If you try to show details for the second "choco.exe" in [Files section](https://chocolatey.org/packages/chocolatey/0.9.9.11), the wrong detail section ist shown. Tag id is not named unique.

**Comment by ferventcoder** [comment]
Thanks for reporting that.

**Comment by ferventcoder** [comment]
Thanks for logging this as an issue, this is now live!
