### ISSUE TITLE
Chocolatey.org Packages List Appears to be Down

### ISSUE THREAD

**Issue by xcjs** [chocolatey/chocolatey.org#289]
After attempting to navigate to https://chocolatey.org/Packages, I was redirect to https://chocolatey.org/Errors/error.html?aspxerrorpath=/Packages with the following message:
Error: Oh no, we broke something!
You might be here because:

•There is an error on our server and the server is "given her all she's got, captain." 
•The system is down, the system is down, the system is down.
•Our name is smalls.
We have logged the error and we will look into it, and make sure it doesn’t happen again. However if you keep seeing this page please File a bug on the Chocolatey Gallery issue tracker.

**Comment by xcjs** [comment]
Apologies if you guys are already on it, but the page requested that I file a bug, so here I am.

**Comment by ferventcoder** [comment]
Thanks. We know about it, we were posting updates to both twitter and the gitter chocolatey.org room.

**Comment by ferventcoder** [comment]
I'm going to close this with a weird label - it was an issue with connection timeouts and we worked with our host folks to resolve it.

**Comment by xcjs** [comment]
No problem. I wasn't aware of the Twitter feed. I'll subscribe to that!
