### ISSUE TITLE
Get rid of flash for copying to clipboard

### ISSUE THREAD

**Issue by rugk** [chocolatey/chocolatey.org#301]
On your main page you directly have some flash content. And as flash is bad you should better not use here.

And here is a very good JS alternative: https://github.com/zenorocha/clipboard.js

**Comment by ferventcoder** [comment]
Thanks.

**Comment by ferventcoder** [comment]
And thanks for mentioning a good library to replace the old JS/Flash library with. Much appreciated.

**Comment by ferventcoder** [comment]
Done.
