### ISSUE TITLE
Create Interface For Maintainers To Request Comment Moderation

### ISSUE THREAD

**Issue by OnorioCatenacci** [chocolatey/chocolatey.org#319]
Every now and again a package maintainer may receive an e-mail to let them know that a Disqus comment has been posted about their package.  But the comment itself may be held in the comment moderation queue (for example, if the comment contains a link).  Please create some means for a package maintainer to contact the chocolatey.org admins to request moderation of messages.

**Comment by ferventcoder** [comment]
> Please create some means for a package maintainer to contact the chocolatey.org admins to request moderation of messages.

So the means is there - using contact site admins link.

We should enhance the email to maintainers to tell them how to followup when the comment is not visible yet. :)

**Comment by ferventcoder** [comment]
This should be live in a few moments.
