### ISSUE TITLE
Add Average approval time to statistics

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#321]
~~~sql
SELECT AVG(DATEDIFF(hour,Created,ApprovedDate)) AS TotalAverageApprovalTime
FROM 
WHERE 
  [Status] = 'Approved'
  AND ReviewedById IS NOT NULL --Not a Trusted Package
  AND Created >= DATEADD(DAY, -14, GETDATE())
~~~

**Comment by gep13** [comment]
@ferventcoder are you planning on putting this on the site somewhere, or just for querying purpose?

Or does statistics refer to the number of packages etc in the moderation queue?  If this, then :+1:

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/12378746/9215df3a-bd0d-11e5-9d03-efe86db8e75f.png)
