### ISSUE TITLE
Packages in Moderation Queue should show a different unlisted message

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey.org#322]
I noticed that you recently changed Chocolatey.org to make the moderation queue visible to everyone. Even though this is entirely intended behavior (see #305), I still think it kind of defeats the entire purpose of package moderation. However, I have noticed another issue that this change creates.

If you view the listing for a package still in moderation, you will see the message "This package is unlisted and hidden from package listings." Now that anyone can view such a package simply by clicking a link on the website, I find this message to be somewhat obsolete. Is it possible to have it removed or rewritten? Thanks!

**Comment by ferventcoder** [comment]
> Now that anyone can view such a package simply by clicking a link on the website, I find this message to be somewhat obsolete. Is it possible to have it removed or rewritten? 

The message is specific to when a package is unlisted, which is also true if the package is in moderation - I think we should likely have a different message for packages in moderation. So :+1: `

**Comment by ferventcoder** [comment]
> Even though this is entirely intended behavior (see #305), I still think it kind of defeats the entire purpose of package moderation. However, I have noticed another issue that this change creates.

Being able to see and being able to install are two different concepts. Seeing the backlog introduces transparency, which is what we want. You still can't just run out and install a package under moderation without knowing how.

**Comment by ferventcoder** [comment]
Notice that there is no shown install/upgrade command.

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/12378280/91b4cc4a-bcfe-11e5-93a2-02613831fdb6.png)

**Comment by ferventcoder** [comment]
I tweaked it a bit more, but that is the message.

**Comment by ferventcoder** [comment]
This should be live in a few moments.
