### ISSUE TITLE
Automatically move to Submitted (Ready) if rerun checks succeed

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/chocolatey.org#349]
If a moderator re-runs the automated checks on a package on which those checks have failed previously, and the re-run indicates no problems - i.e. all automated checks succeed - then the package should move to Submitted (Ready) just as if the checks would have succeeded on the first run.

**Comment by ferventcoder** [comment]
Thanks!

**Comment by ferventcoder** [comment]
Discussion at https://gitter.im/chocolatey/choco?at=56acb41580ad69394a7b60f1

**Comment by ferventcoder** [comment]
We only rerun the verifier, so we could move it back to a pending state on a rerun and check the status of both the verifier and validator before moving it to ready. If both are passing, move it. Otherwise continue to indicate #348 whether the package is waiting or if it is good to go for review.

**Comment by ferventcoder** [comment]
#347 is related
