### ISSUE TITLE
Unable to use chocolatey behind Tor

### ISSUE THREAD

**Issue by pyhedgehog** [chocolatey/chocolatey.org#357]
### Preface
I'm behind restrictive corporate firewall, so I had to use Tor to bypass it.

### What You Are Seeing?
```output
C:\>cup -y firefox
Upgrading the following packages:
firefox
By upgrading you accept licenses for the packages.
firefox was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is pos
sible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey upgraded 0/1 package(s). 0 package(s) failed.
 1 package(s) had warnings.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Warnings:
 - firefox

C:\>
```
I've checked accessibility of mentioned URL:
https://gist.github.com/pyhedgehog/8a6b55fb5fc6e9721691#file-buggy-output

### What is Expected?
Normal install/upgrade and accessible api:
https://gist.github.com/pyhedgehog/8a6b55fb5fc6e9721691#file-good-output

### How Did You Get This To Happen? (Steps to Reproduce)
 1. Set http_proxy, https_proxy and choco proxy to privoxy configured to use tor.
 2. Attempt to install or upgrade any package from remote source.

**Comment by ferventcoder** [comment]
Would you agree this is more likely something with respect to choco and your environment than it is Chocolatey.org? And by that I mean, what changes would you expect on dot org to fix the issue?

**Comment by ferventcoder** [comment]
I just read the log, sorry about that. Looks like it is an issue with security checks and CloudFlare

**Comment by ferventcoder** [comment]
This may take a bit of working together to get through. I made an adjustment, can you verify it works now?

**Comment by pyhedgehog** [comment]
Good now:
```output
C:\>bash -c "http_proxy=http://127.0.0.1:8118 curl -i https://chocolatey.org/api/v2/
HTTP/2.0 200
server:cloudflare-nginx
date:Sun, 21 Feb 2016 14:26:52 GMT
content-type:application/xml;charset=utf-8
content-length:397
set-cookie:__cfduid=daef4d75e9bc833bbce70916a6d378a6a1456064812; expires=Mon, 20-Feb-17 14:26:52 GMT; path=/; domain=.chocolatey.org; HttpOnly
cache-control:no-cache
dataserviceversion:1.0;
cf-ray:278320f34f41168e-ARN

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<service xml:base="http://chocolatey.org/api/v2/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app" xmlns="http://www.w3.org/2007/app">
  <workspace>
    <atom:title>Default</atom:title>
    <collection href="Packages">
      <atom:title>Packages</atom:title>
    </collection>
  </workspace>
</service>
```

**Comment by ferventcoder** [comment]
:+1: Glad we could get that accomodated.
