### ISSUE TITLE
maintainers not able to reply to notes when package is approved

### ISSUE THREAD

**Issue by Vaquero84** [chocolatey/chocolatey.org#358]
### What You Are Seeing?
My packages get approved, but reviewers still leave a comment or a question. Once the package is approved, however, I can no longer answer to these comments in the review section.

### What is Expected?
That I would still be able to comment on reviewer's package comments after approval.

### How Did You Get This To Happen? (Steps to Reproduce)
push package
get it approved, while reviewer leaves comment in the step of approving (last step)

**Comment by ferventcoder** [comment]
Thanks for adding this. :)

**Comment by ferventcoder** [comment]
This will be related to #291

**Comment by ferventcoder** [comment]
This is live now.

**Comment by ferventcoder** [comment]
Thanks for logging this as an issue!
