### ISSUE TITLE
Cannot access my profile

### ISSUE THREAD

**Issue by szaiser** [chocolatey/chocolatey.org#364]
EDIT: If just the Chocolatey servers are down temporarily, please ignore this issue.

i can log into my profile, but when i want to access it, this is the result:

_Error: Oh no, we broke something!

You might be here because:

    There is an error on our server and the server is "given her all she's got, captain."
    The system is down, the system is down, the system is down.
    Our name is smalls.

We have logged the error and we will look into it, and make sure it doesn’t happen again. However if you keep seeing this page please File a bug on the Chocolatey Gallery issue tracker._

The same happens when i search for the "canopy" package and try to open its page.

I assume, the two error messages are connected.

**Comment by ferventcoder** [comment]
We have identified the issues and are working to resolve them - https://twitter.com/chocolateynuget/status/705865285694164992

**Comment by amarzavery** [comment]
Cannot login..

**Comment by ferventcoder** [comment]
Should be good to go now. Let me know if you see otherwise. Thanks!

On Friday, March 4, 2016, Amar Zavery <notifications@github.com> wrote:

> Cannot login..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/364#issuecomment-192531373>
> .
>


-- 

Rob
"Be passionate in all you do"

http://codebetter.com/robreynolds
http://ferventcoder.com
https://twitter.com/ferventcoder

**Comment by amarzavery** [comment]
Thanks. I am able to login :+1:
