### ISSUE TITLE
Package Listing Doubled

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey.org#368]
### What You Are Seeing?

Most (albeit not all) of the packages listed on Chocolatey.org are shown twice. See below screenshot.

![Chocolatey.org Screenshot](https://cloud.githubusercontent.com/assets/1915951/13886811/1f083ace-ed0f-11e5-85d5-163a44fe3319.png)

### What is Expected?

The packages should not be shown twice.

### How Did You Get This To Happen? (Steps to Reproduce)

Go to Chocolatey.org, click on Packages, select Recent from the rightmost pop-up menu. My browser is Safari 9.0.3 on OS X 10.11.3. This only started happening today.

**Comment by ferventcoder** [comment]
FWIW, this is only happening on web 1 (1/3 web balancers).

![image](https://cloud.githubusercontent.com/assets/63502/13887207/797a35c2-ed08-11e5-8362-a12a553ed7b5.png)

**Comment by ferventcoder** [comment]
It's an issue with indexing and it will eventually clear itself up. I can try to clean up the index by redeploying

**Comment by ferventcoder** [comment]
This should now be resolved.

On Fri, Mar 18, 2016 at 12:42 PM, William Kent <notifications@github.com>
wrote:

> What You Are Seeing?
>
> Most (albeit not all) of the packages listed on Chocolatey.org are shown
> twice. See below screenshot.
>
> [image: Chocolatey.org Screenshot]
> <https://cloud.githubusercontent.com/assets/1915951/13886811/1f083ace-ed0f-11e5-85d5-163a44fe3319.png>
> What is Expected?
>
> The packages should not be shown twice.
> How Did You Get This To Happen? (Steps to Reproduce)
>
> Go to Chocolatey.org, click on Packages, select Recent from the rightmost
> pop-up menu. My browser is Safari 9.0.3 on OS X 10.11.3. This only started
> happening today.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/368>
>



-- 

Rob
"Be passionate in all you do"

http://codebetter.com/robreynolds
http://ferventcoder.com
https://twitter.com/ferventcoder

**Comment by wjk** [comment]
Indeed it is. Thank you!
