### ISSUE TITLE
[Enhancement] Low traffic update mail for package maintainers

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey.org#37]
Sometimes I learn new stuff about packages randomly. Stuff I could have read somewhere when I was actively looking. Which I am not very often. 

Might it be a good idea to have package maintainers who signed up to the website (automatically/recommended to) sign up to some sort of low-traffic newsletter where new features, shortcuts, and essentials that come with every non-prerelease new version of `Chocolatey`?

For example, the `0.9.8.21` could have among other points:

> * You no longer need custom processor architecture address width detection to differentiate 32 from 64 bits. You can now use `if (Get-ProcessorBits 64) {} else {}`.  
> See [src/helpers/functions/Get-ProcessorBits.ps1](https://github.com/chocolatey/chocolatey/blob/master/src/helpers/functions/Get-ProcessorBits.ps1)

Every time you (__@ferventcoder__) merge or code something, you can add a little bulletpoint like this to a Sticky Note/Tomboy Note/Opera Note. And with every major version mail all new points to the packagers. Perhaps have these points in a Chocolatey `Feature Version History` wiki. Because packagers of course have a responsibility to use the leanest cleanest code in their packages because it will serve as an example for new packagers. ;)

**Comment by ferventcoder** [comment]
This is now done. http://us8.campaign-archive2.com/home/?u=86a6d80146a0da7f2223712e4&id=3cf9038d77
