### ISSUE TITLE
Maintenance Review Conversation Errors on Posting Comment

### ISSUE THREAD

**Issue by sedouard** [chocolatey/chocolatey.org#371]
### What You Are Seeing?

Maintenance review page errors on comment submission:

https://chocolatey.org/packages/logdna-agent/1.0.0
### What is Expected?

The commend is posted to the thread.

### How Did You Get This To Happen? (Steps to Reproduce)

I simply submit a comment on the review page for:
https://chocolatey.org/packages/logdna-agent/1.0.0

**Comment by ferventcoder** [comment]
What did you try to send?

**Comment by ferventcoder** [comment]
`<` `>` - it doesn't like these items.

**Comment by sedouard** [comment]
Yeah pretty sure I entered a `<` or `>`. I don't have the exact text anymore sorry. :-(. But pretty sure that was it.

**Comment by ferventcoder** [comment]
This is now allowed - see #395.
