### ISSUE TITLE
Cannot install Mercurial package

### ISSUE THREAD

**Issue by jozefizso** [chocolatey/chocolatey.org#375]
Running `choco install mercurial` does not install Mercurial but display error **mercurial not installed. The package was not found with the source(s) listed**

I use the chocolatey v0.9.9.12 on Windows 10 with default source server.

Verbose log: https://gist.github.com/jozefizso/f20ace6bed8de62474eb

```
Installing the following packages:
mercurial
By installing you accept licenses for the packages.
mercurial not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - mercurial
Exiting with 1
```

**Comment by gep13** [comment]
@jozefizso There isn't a package called mercurial.  There is however one called hg.

Try `choco install hg`.

https://chocolatey.org/packages/hg

**Comment by ferventcoder** [comment]
@jozefizso It might help if you grab the latest beta `choco upgrade chocolatey -pre` - it has tab completion for package names. Do you think that would be helpful?
