### ISSUE TITLE
An asynchronous call is already in progress. It must be completed or canceled before you can call this method

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#379]
"An asynchronous call is already in progress. It must be completed or canceled before you can call this method" was an error that came back when one of the services was attempting to update the site.
- http://stackoverflow.com/q/8369614/18475

**Comment by Thilas** [comment]
Hey,
I just got this error while pushing 2 automatic packages (with AU from AppVeyor). Here is the report: https://gist.github.com/Thilas/c09573f2f23bc2aa904d90ff63de2cfe/787a9ea2fe2ca0f93bf362bb0a9a0f661ceb6a35. For the build on AppVeyor, it's this one: https://ci.appveyor.com/project/Thilas/chocolatey-packages/build/219.
Thanks,
Thomas

**Comment by ferventcoder** [comment]
Thanks @Thilas - it's not often we see this. I see a possible fix in http://stackoverflow.com/a/16438292/18475

**Comment by Thilas** [comment]
The idea seems nice indeed. I would prefer to do this using Task on my side. If you want I can submit a PR about it?

**Comment by ferventcoder** [comment]
Sure. A PR would be lovely.
