### ISSUE TITLE
Package Upload Error

### ISSUE THREAD

**Issue by mquevill** [chocolatey/chocolatey.org#381]
### What You Are Seeing?

Cannot upload a .nupkg to chocolatey.org. Error is thrown every time.
"Sorry, an error occurred while processing your request."
"Error: Oh no, we broke something!"
### What is Expected?

Package is uploaded properly to chocolatey.org
### How Did You Get This To Happen? (Steps to Reproduce)

I uploaded one package (sgt-puzzles.2016.04.10), which was automatically rejected since I made errors (forgetting "admin", etc.) since it is my first package. I fixed all my errors and tried to reupload the package, but got a vague error. The interesting thing is that I get an email saying it is submitted for moderation review. However, a week out, there's no progress.

As there is a new version of the software available, I tried uploading sgt-puzzles.2016.04.25 to chocolatey.org, with the same result.

**Comment by ferventcoder** [comment]
Howdy, how big are these files?

**Comment by mquevill** [comment]
3.3 MB

**Comment by ferventcoder** [comment]
Hmm, that should work. That's pretty small.

Have you attempted to use `choco push`?

**Comment by mquevill** [comment]
That worked. I guess I'll have to use that method for now. Thanks!

**Comment by bcurran3** [comment]
I have been having this same problem.
I consistently cannot submit setpoint.6.67.83.nupkg (10k) or network-inventory-advisor.4.3.nupkg (10k). I have attempted NUMEROUS times. 
I have not tried choco push - will attempt to learn how and do now.

**Comment by bcurran3** [comment]
Looks like I found the problem: choco push gives me this error: "Failed to process request. 'This package had an issue pushing: A nuget package's Description property may not be more than 4000 characters long.'.
The remote server returned an error: (409) Conflict.."
I'll tone down my packages.
FEATURE REQUEST: Make this error available after attempting to upload via the web.

**Comment by ferventcoder** [comment]
4,000 is a limit for dot org. We can start working to put this into choco itself during package validation (part of what happens during packaging).

**Comment by kevinkabatra** [comment]
@ferventcoder when I use choco push I receive the email that it went through, but I do not see it on the site listed under Manage My Packages. Does this normally take some time to appear there? This is my first upload. Thanks for the support.

**Comment by ferventcoder** [comment]
Should be able to access it from the link in the email - otherwise assume there was an issue

**Comment by ferventcoder** [comment]
Superseded by #798
