### ISSUE TITLE
choco pack should check for nuspec problem

### ISSUE THREAD

**Issue by teknowledgist** [chocolatey/chocolatey.org#385]
I discovered after bit of frustration (getting unspecified upload errors) that

> A nuget package's Description property may not be more than 4000 characters long.

It would be helpful if _choco pack_ would check for this kind of thing like it does for some others (blank licenseUrl node, for example), so we know from the get-go.

**Comment by ferventcoder** [comment]
That is a limitation with the Chocolatey Gallery and not with the nuspec. What we are doing is adding validation to choco pack in 0.9.10.x, one of those things will be to validate for the community feed.

**Comment by ferventcoder** [comment]
The problem I'm seeing here is that you opened this on CHocolatey.org repo, but the wording lends to an enhancement with choco, which is a different repository.

**Comment by ferventcoder** [comment]
This is getting added to choco pack with the validator - https://github.com/chocolatey/choco/issues/602
