### ISSUE TITLE
Font Display Issue

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey.org#390]
### What You Are Seeing?

I am seeing Times New Roman used as the font on Chocolatey.org pages using the new visual design.

### What is Expected?

Following 2206eee a series of fallback fonts should be used. I am still seeing Times New Roman.

### How Did You Get This To Happen? (Steps to Reproduce)

Go to Chocolatey.org and view any page using the new visual design. (Safari 9.1.1 on OS X 10.11.5.)

**Comment by ferventcoder** [comment]
Try clearing your browser cache and tell me if you still see this.

On Sunday, May 22, 2016, William Kent <notifications@github.com> wrote:

> What You Are Seeing?
>
> I am seeing Times New Roman used as the font on Chocolatey.org pages using
> the new visual design.
> What is Expected?
>
> Following 2206eee
> <https://github.com/chocolatey/chocolatey.org/commit/2206eee265ae4b3439fcd4f37bef9355748fb761>
> a series of fallback fonts should be used. I am still seeing Times New
> Roman.
> How Did You Get This To Happen? (Steps to Reproduce)
>
> Go to Chocolatey.org and view any page using the new visual design.
> (Safari 9.1.1 on OS X 10.11.5.)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/390>
>


-- 

Rob
"Be passionate in all you do"

http://codebetter.com/robreynolds
http://ferventcoder.com
https://twitter.com/ferventcoder

**Comment by wjk** [comment]
Yeah, that fixed it. Sorry to bother you.
