### ISSUE TITLE
Add OpenSans as webfont

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#391]
It's not on all systems by default, so add it as a webfont if available. Suggested by @Redsandro

**Comment by ferventcoder** [comment]
Suggested as a way to get the fonts necessary

> `$('head').append('<style type="text/css">@import url(//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,300,400,700);</style>');`

**Comment by AdmiringWorm** [comment]
Suggested as an alternative to using javascript to load the webfont:
> `<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,300,400,700" />`

benefit of having it loaded even if the user doesn't have javascript enabled

**Comment by designxsteph** [comment]
This has been released here: https://github.com/chocolatey/chocolatey.org/commit/ec083803ac7af2a5d3ab9dbbb2c0e130382007d3
