### ISSUE TITLE
Add support for full URL to nupkg to the Source argument

### ISSUE THREAD

**Issue by hessj001** [chocolatey/chocolatey.org#393]
Hi!  We love Chocolatey at my work and use it heaps.

Can I suggest that the --source argument accept a URL link to the nupkg that I'd like installed?

`choco install package --source https://server.blah/package-1.0.nupkg
`

There are a couple of custom packages that we've created and it would be handy to be able to just grab them without having to create a NuGet host.

**Comment by ferventcoder** [comment]
That's an interesting one. And there may already be an issue related to this. If not, definitely something we should allow (fetching from a bare url).

How would you see this handling dependencies?

**Comment by ferventcoder** [comment]
We have talked about making HTTP/HTTPS sources not need to be OData - just bare http indexes and making things work appropriately. I am unsure if we created an issue to that regard though. It would provide the same kind of thing you are asking here, the only difference is that it would mean you could call:

`choco install packagename --source https://server.blah/` - this would make things harder if it was not a bare index though.

**Comment by hessj001** [comment]
Our customer choco packages don't have dependencies, but good question.

Just to clarify: we do have a NuGet server for our custom chocolatey packages but it has a size limit and I'd prefer to embed our in the packages instead of having the packages download the installers as a separate step in the install script.  That's why I was hoping to just dump them to a server and farm them out by a direct link.

**Comment by ferventcoder** [comment]
Makes perfect sense. I just noticed this issue was created on chocolatey.org code base, can you recreate this over at https://github.com/chocolatey/choco/issues/new with the same issue request but also link back to this issue? Then we can close it here since it is the wrong repository.

**Comment by hessj001** [comment]
Done.

https://github.com/chocolatey/choco/issues/770
