### ISSUE TITLE
Can't submit feedback in the Feedback box

### ISSUE THREAD

**Issue by RickStrahl** [chocolatey/chocolatey.org#394]
On my package submissions page there are a number of 'suggestions' and a submission box.

When I try to submit a comment in the submission box, I get the Chocolatey error page. Reloaded page tried again same result.

Trying to find out about this:

> This package uses a helper function that requires administrative permissions, the tag 'admin' should also be in the nuspec. More... 

It's great you have a link to a topic, but then topic doesn't give an example of what the values are or how this should be added to the file, so I have to guess. I figure it's an `<admin>true</admin>` key but that doesn't work - `choco pack` fails with that.

It also mentions `<packageSourceUrl>` but the stock template adds `<projectSourceUrl>`. Which is it?

Worse there's no full schema documentation anywhere. You point at NuSpec, but that doesn't include Choco specific extensions. Nowhere that I can find is there a sample of a file that has all the options in it. Is it `<packageSourceUrl>` correct or `<projectSourceUrl>` - I have no idea. Is `<admin>` the right key and what do I use for a value? `true|false`, `0|1` No idea. 

This should be an easy fix. Post a file that has **ALL** possible options in it with default values as necessary and post that **prominently** - from that I could easily figure out what's needed. Now I'm just guessing.

You have lots of documentation here and lots of it is very well written and valuable as tutorials and background. But it's very verbose and a real bitch if you need to find anything specifically. A lot of the topics (especially the linked help links from the package page) don't show examples of the things you're supposed to fix. It'd be real easy to show a couple examples of the tags that need fixing.

It might help to use a better doc system than the GitHub Wiki which is pretty terrible unless your documentation is made up of a handful of documents.

+++ Rick ---

**Comment by RickStrahl** [comment]
Sorry I realize I ranted a bit here, but using Chocolatey has been frustrating lately. There are lots of things broken and it grates a bit when you need to get things done and two hours later I'm still at it for a simple install.

I realize this is a side project for you, and I can appreciate all that goes into this project, and I do love it. I appreciate the work that goes into this wonderful tooling that's become essential for Windows and the front end part for installing and retrieving packages works very smoothly (which is obviously the most important thing).

 But I really wish things would work more smoothly on the backend for publishers. The issues like the recent auth caching issue, today's comment submission, the lack of updated package counts all seem like things that drag on for a long time before they get addressed. I'm not sure what the scope of this is, but these don't seem like difficult technical issues to solve (I could be wrong).

A little love for the backend would go a long way towards making Chocolatey publishing experience a lot more user friendly.

**Comment by ferventcoder** [comment]
Today's comment submission - did you have any html looking tags in there? Such as `<something>` - it doesn't like that. We've posted that in a few places, perhaps we need it in more.

**Comment by ferventcoder** [comment]
For a nicer nuspec, consider upgrading to the latest beta (which will be released in a few days) - then run choco new.

**Comment by gep13** [comment]
@RickStrahl regarding the admin tag problem you are seeing with the validator, have a look at this commit:

https://github.com/chocolatey/chocolatey-coreteampackages/commit/09e3b7e8a7487025d7b623e75359799f8186ac3d

where i was fixing th e same issue for some of the core team package.

**Comment by gep13** [comment]
@RickStrahl also, have you seen the docs here:

https://chocolatey.org/docs

They are an export of the same content from the wiki that exists in the GitHub repo.

**Comment by ferventcoder** [comment]
@gep13 I think he means the package validator documentation - some of those are still the stubs.

**Comment by ferventcoder** [comment]
In this case I added an example - https://github.com/chocolatey/package-validator/wiki/AdminTagShouldBeUsedWhenUsingAdminHelper

**Comment by gep13** [comment]
>@ferventcoder said...
@gep13 I think he means the package validator documentation - some of those are still the stubs.

Ah, fair point.

**Comment by ferventcoder** [comment]
@RickStrahl we definitely need to spend some time focusing on more of smoothing out the publisher side of the house - one of those things is to run the package validation when you run choco pack. We had that in for 0.9.10, but were not able to get it into the release in time so we scoped it for 0.9.10.1. It's a big feature and I think we definitely need it soonest.

We've gone a long way to making things better for publishers in 0.9.10 - you can see it if you install the beta and run `choco new testnew` versus 0.9.9.x `choco new testold`.

When creating packages, almost all of our documentation recommends running `choco new`, which has what we call just in time documentation - one of which already has the admin tag (in the 0.9.9.x series as well). We never recommend just copying an older working package because folks miss out on the advancements in packaging that way. It sounds like we need more of what it creates up somewhere for reference though. 👍

**Comment by RickStrahl** [comment]
Re: comment breakage. Yes I think I <admin></admin> in there. But then again - why is that breaking given that you know that this is a problem? That's not exactly a hard problem to fix with encoding and it's something that very likely will end up in comments.

Thanks for the link on how to use the Admin 'tag'. I would have never put that together that it goes in the same list with my custom tags. That seems very unintuitive to mix tags like this but Ok :-)  I guess there's no way to put that anywhere else. Thanks. Did this get linked from the `more...` link as well - cause that's where I would want to see this.

So basic related question: does Chocolately only use NuSpec elements or does chocolately extend the spec in any way? I assumed it extended but giving you're shoehorning the admin flag into `tags` makes me think you probably are not...

> It also mentions <packageSourceUrl> but the stock template adds <projectSourceUrl>. Which is it?

I created this package with choco new. I believe it created `<projectSourceUrl>` but the actual package expects `<packageSourceUrl>`.

Ok, so I create another package with `choco new` and it looks like it generates this:

```
    <packageSourceUrl></packageSourceUrl>
    <!--<projectSourceUrl></projectSourceUrl>
    <docsUrl></docsUrl>
    <mailingListUrl></mailingListUrl>
    <bugTrackerUrl></bugTrackerUrl>-->
```

I guess I must have grabbed the projectSourceUrl instead of packageSourceUrl, so that's likely my mistake. Should both of those be in there? They both would be pointing at hte same place no?

Anyways, just again to clarify I really do appreciate what you do and the fact we're having this dicsussion here, as well as the fact that you've fixed me up with what I need here. I hope the feedback is helpful in terms of shining a light on things that I've had problems with with Choco.

Aloha...

**Comment by RickStrahl** [comment]
Just to confirm the problem with the comment box was indeed `<admin>true</admin>` tags. That's probably something that should be addressed since you're going to get messages with XML since the nuspec file is XML. Or at the very least a better error message.

Anyway closing since it's at least identified. You'll likely want to track this elsewhere.

**Comment by ferventcoder** [comment]
@RickStrahl Adding https://github.com/chocolatey/chocolatey.org/issues/395 to address this.

**Comment by ferventcoder** [comment]
>  projectSourceUrl instead of packageSourceUrl. Should both of those be in there? They both would be pointing at the same place no?

Not always. Package source for maintainers who are not also the vendors would most likely be a different location than where the project source code is.

**Comment by ferventcoder** [comment]
@RickStrahl #395 has been deployed. Trying to submit review responses and getting an error can lead to lots of frustration on the part of maintainers, especially when maintainers have no idea that it is due to RequestValidation and their use of XML (and there was no information on the review form as to this limitation like other places in the site had). This has now been fixed so that the review box and most other places where it makes sense we encode the html tags.

Thank you for pointing that out and catching us on an area where we needed to do better to serve maintainers. We love helpful feedback, even when born out of frustration, because it helps the community rather than silence about things that are not working.

**Comment by ferventcoder** [comment]
> Did this get linked from the more... link as well - cause that's where I would want to see this.

Yes, that's where the link for more... goes to.

**Comment by ferventcoder** [comment]
> So basic related question: does Chocolately only use NuSpec elements or does chocolately extend the spec in any way?

We extend the nuspec, and in the 0.9.10 nuspec file that is generated when you `choco new`, we are better about telling you what those elements are. It's very similar to: https://github.com/ferventcoder/chocolatey-packages/blob/6df5980203702dd19fa61f1df40ad78f21b564f4/manual/default.template/templates/default.nuspec.template#L8-L12
