### ISSUE TITLE
Homepage problem, also some packages installing ok, others failing

### ISSUE THREAD

**Issue by Tom999Hall** [chocolatey/chocolatey.org#396]
Chocolatey Homepage error:
======================
Error: Oh no, we broke something!
You might be here because:
There is an error on our server and the server is "given her all she's got, captain." 
The system is down, the system is down, the system is down.
Our name is smalls.
We have logged the error and we will look into it, and make sure it doesn’t happen again. However if you keep seeing this page please File a bug on the Chocolatey Gallery issue tracker. 

Package installs failing:
=================
Failures
 - realtek-hd-audio-driver - realtek-hd-audio-driver not installed. An error occurred during installation:
 Unable to read package from path 'realtek-hd-audio-driver.2.79.nupkg'.
 - chocolateygui - chocolateygui not installed. An error occurred during installation:
 Unable to read package from path 'ChocolateyGUI.0.13.2.nupkg'.
 - notepadplusplus.install - notepadplusplus.install not installed. An error occurred during installation:
 Unable to read package from path 'notepadplusplus.install.6.9.2.nupkg'.
 - 7zip.install - 7zip.install not installed. An error occurred during installation:
 Unable to read package from path '7zip.install.16.02.nupkg'.

**Comment by ferventcoder** [comment]
Started looking into this around the same time this was issued. Thanks!

**Comment by Tom999Hall** [comment]
Thanks Rob - I'm down the pub at the moment - so not a high priority (for me) 😂😂😂


Get Outlook for Android



From: Rob Reynolds

Sent: Saturday, 18 June, 13:59

Subject: Re: [chocolatey/chocolatey.org] Homepage problem, also some packages installing ok, others failing (#396)

To: chocolatey/chocolatey.org

Cc: Tom999Hall, Author



Started looking into this around the same time this was issued. Thanks!

**Comment by ferventcoder** [comment]
This should be resolved now.

**Comment by rhwood** [comment]
I am seeing a [failure to download ant](https://ci.appveyor.com/project/JMRI/jmri/build/2948) at AppVeyor and the Homepage error message described above.

**Comment by ferventcoder** [comment]
@rhwood I just performed some additional changes - It seems that one of the servers in the load balancer was still misbehaving.
