### ISSUE TITLE
Can't install chocolatey

### ISSUE THREAD

**Issue by jcatama06** [chocolatey/chocolatey.org#400]
![capture](https://cloud.githubusercontent.com/assets/10590503/16450259/bd6fd6d4-3e2e-11e6-8178-887d979819e7.PNG)

**Comment by ferventcoder** [comment]
Have you seen the message about extreme load currently with intermittent outages? This applies.

**Comment by ferventcoder** [comment]
The answer until we get this load spiking issue resolved is to give it another shot.

**Comment by ferventcoder** [comment]
Duplicate of #397

**Comment by jcatama06** [comment]
Nope, but thank you.
