### ISSUE TITLE
Account registration does not block the use of "<" for password, error occurs when trying to login

### ISSUE THREAD

**Issue by flyingfeather1501** [chocolatey/chocolatey.org#403]
#### What I've done
When registering an account, I generated a random password with the html tag marker "<" in it.
After registration and email is complete, I then tried to login. Chocolatey returned to a page saying "error occured". 
If I delete the "<" in my password, it tells me that the password is incorrect.

#### What is expected
Either: 
a) Server processes "<" correctly as a character in the password, or
b) Registration blocks the use of some characters, including "<".

**Comment by ferventcoder** [comment]
It should work, but perhaps there is an issue on the login screen with allowing "<". I'll take a look

**Comment by ferventcoder** [comment]
I was not able to reproduce this issue

**Comment by ferventcoder** [comment]
This could be an issue with CloudFlare

**Comment by ferventcoder** [comment]
Can you give this another shot?

**Comment by flyingfeather1501** [comment]
I tried registering another account with the password "123456789<", and now it works.

**Comment by ferventcoder** [comment]
Thanks!
