### ISSUE TITLE
Cannot Sign Up New User Account

### ISSUE THREAD

**Issue by androindep** [chocolatey/chocolatey.org#404]
### What You Are Seeing?
Error after attempting to register a new account. "Uh oh, we broke something!"

### What is Expected?
That I get to create one?

### How Did You Get This To Happen? (Steps to Reproduce)
Use the Sign Up link on the main page, enter information, click Register. Tried different machines/browsers.

**Comment by ferventcoder** [comment]
Thanks for logging this - can you reach out to us directly at chocolateywebadmin at google groups? Thanks!

**Comment by ferventcoder** [comment]
@androindep give it another shot. We confirmed with another user that this is working appropriately.
