### ISSUE TITLE
Include SO as binary executables

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#405]

**Comment by ferventcoder** [comment]
https://chocolatey.org/packages/romp/1.2.0#files

**Comment by gep13** [comment]
@ferventcoder just catching up with emails.  What exactly is meant by this one?

**Comment by ferventcoder** [comment]
.so files

On Monday, July 11, 2016, Gary Ewan Park <notifications@github.com> wrote:

> @ferventcoder <https://github.com/ferventcoder> just catching up with
> emails. What exactly is meant by this one?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/405#issuecomment-231829325>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAD4Dg310FWHlLn07zLYUKUI99ylZqpGks5qUpD8gaJpZM4JHp3K>
> .
>


-- 

Rob
"Be passionate in all you do"

http://codebetter.com/robreynolds
http://ferventcoder.com
https://twitter.com/ferventcoder
