### ISSUE TITLE
Chocolatey Installantion Error: [System.String] does not contain a method named 'DownloadString'

### ISSUE THREAD

**Issue by manassornt** [chocolatey/chocolatey.org#413]
### What You Are Seeing?
![downloadstringerror](https://cloud.githubusercontent.com/assets/12132288/17660939/36f055a0-6306-11e6-892e-fe756fdc4f16.png)

### What is Expected?
chocolatey installed

### How Did You Get This To Happen? (Steps to Reproduce)
I ran the chocolatey installation command
@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin

I think the problem is https://chocolatey.org/install.ps1
The Write-Output "using system proxy server '$proxyaddress' ." line have uncaptured output
So it return this value instead of $downloader

![writeoutput](https://cloud.githubusercontent.com/assets/12132288/17661189/d3f09792-6307-11e6-95ef-59606aad1187.PNG)

**Comment by ferventcoder** [comment]
I think you are correct. Marking this high priority.

**Comment by ferventcoder** [comment]
This was released as fixed about 2 hours ago.
