### ISSUE TITLE
Package Upload Screen shows old Package Data

### ISSUE THREAD

**Issue by RickStrahl** [chocolatey/chocolatey.org#418]
I created a new package a couple of days ago and submitted it to Chocolatey. The package has not been approved yet, and I decided to reject it (or rather had the moderator reject it although I'm not sure if that matters).

Today I went in to upload a new package. After logging in and clicking on the Upload Package I'm greeted with an already filled out package screen from the last package upload. I'm not getting form that has the upload button on it.

Tried different browsers just to be sure it's not a client caching issue - why would these upload definitions cache, even if they weren't followed all the way through?

**Comment by ferventcoder** [comment]
It's not a cache - it's an upload in progress. This has existed since way before caching to allow you to upload a package and come back later.

**Comment by ferventcoder** [comment]
What happens is that the upload uses your key to upload a package and when it is verified it renames it to the package name. Seeing that key is what is triggering the page. I'm just in there so I can remove the package for you.

**Comment by ferventcoder** [comment]
It's something that came from the original NuGet Gallery, not exactly my favorite thing.

**Comment by ferventcoder** [comment]
Click on "Cancel" to remove the old one.

**Comment by ferventcoder** [comment]
Let me know if that doesn't work.

**Comment by RickStrahl** [comment]
Thanks - yeah I think I started an upload and never completed it. Came back a few days later and it came right back on that form. Cancel did fix it and I managed to get a new version uploaded.
