### ISSUE TITLE
Disqus logon does not work in MS Edge

### ISSUE THREAD

**Issue by jberezanski** [chocolatey/chocolatey.org#420]
### What You Are Seeing?

Attempting to log on to Disqus (using a Disqus account) on a package page in MS Edge (Win10 1511) opens a new, fullscreen browser window with the url "https://disqus.com/next/login-success/#!auth%3Asuccess", displaying spinning cogs. The window stays open and the Disqus section on the package page does not recognize the successful logon.
### What is Expected?

After successful authentication, the Disqus logon popup window should automatically close and the Disqus section on the package page should recognize the logon and allow commenting. (This is what happens in Internet Explorer on the same system.)
### How Did You Get This To Happen? (Steps to Reproduce)
1. Open MS Edge on Windows 10 1511, possibly in InPrivate mode (to eliminate interference from existing cookies)
2. Navigate to a package page, such as https://chocolatey.org/packages/git/2.10.0
3. Go to the Disqus section, click "Login" and select "Disqus" from the menu
4. Observe that a new browser window with a logon form is opened
5. Fill in the Disqus logon form in the newly opened browser window and click "Log In"
6. Observe a message from Disqus: "There was an error submitting the form."
7. Close the browser window with the error message
8. On the package page, click "Login" and select "Disqus" from the menu again
9. Observe that a new browser window with the url "https://disqus.com/next/login-success/#!auth%3Asuccess", displaying spinning cogs, is opened
10. Close the new browser window
11. Observe that the Disqus section on the package page still displays the "Login" button

Note: on Windows 10 1607 the behavior is slightly different: in step 9, the logon form is displayed again (same as step 4).

**Comment by ferventcoder** [comment]
Disqus issue, MS Edge issue or something else? 

If it has to do with Disqus, especially commenting or logging in, it's an issue outside of our control. The only thing we can do to fix is remove disqus or decide to keep it around.

**Comment by jberezanski** [comment]
Someone else had that issue on a different site and [reported it to Disqus](https://disqus.com/home/discussion/channel-discussdisqus/cant_login_with_edge/), but it got closed as "unable to reproduce". Meanwhile, Disqus officially claims [it does support Edge](https://help.disqus.com/customer/portal/articles/466228-which-browsers-does-disqus-work-with-).

Forgot to add: in step 6, the window title states "CSRF verification failed".

**Comment by ferventcoder** [comment]
Unfortunately there is not much we can do except decide to stop using disqus in a case like this. I will leave this open for a bit for other folks to find this issue as well.

**Comment by OldtownAdge** [comment]
I have the identical issue. Disqus didn't really explore the other thread, so there's no real info on this. I suspect it's a privacy setting in Edge, but I can't prove it.
Disqus' claim to support Edge certainly looks iffy.

**Comment by jberezanski** [comment]
I've recently upgraded my OS to the Creators Update (1703) and Disqus logon works for me in Edge now.

**Comment by ferventcoder** [comment]
Thanks for that update!

**Comment by renandiett** [comment]
For me, login works properly! But when I try to update my profile settings the Network inspection show a 403 (Forbidden) in Ajax requests. The response from the server is "CSRF verification failed".

Any tips to solve this issue or should I come back using Chrome and/or Firefox?

**Comment by renandiett** [comment]
as faslfkafa

**Comment by renandiett** [comment]
asfklasf
