### ISSUE TITLE
404 Not Found When Uploading Package

### ISSUE THREAD

**Issue by npruehs** [chocolatey/chocolatey.org#423]
### What You Are Seeing?

At the command-line:

```
Chocolatey v0.10.0
Attempting to push tome.0.5.nupkg to https://chocolatey.org
Failed to process request. 'Not Found'.
The remote server returned an error: (404) Not Found..
```

In the browser:

![image](https://cloud.githubusercontent.com/assets/757321/18419783/4a72e5b2-7863-11e6-90e1-f5807325e233.png)
### What is Expected?

A success message for uploading my package to chocolate.org, and/or the ability to review the package.
### How Did You Get This To Happen? (Steps to Reproduce)
- Create a very simple portable Chocolatey package (no installation scripts, just the [tome.nuspec](https://github.com/chocolatey/chocolatey.org/files/466188/tome.nuspec.zip) and the binary folder
- Verify the package can be installed locally by running `choco install tome -source tome.0.5.nupkg -f`
- Uninstall the package again
- Try to upload the package at the command-line first, and in the browser after

**Comment by ferventcoder** [comment]
That doesn't seem to work well at all. :/

**Comment by ferventcoder** [comment]
Well the 404 looks totally inappropriate - it should have mentioned that the package id already exists - https://chocolatey.org/packages/tome

**Comment by ferventcoder** [comment]
That package is no longer listed, but I don't know what that means. @anthonymastrean?

**Comment by npruehs** [comment]
Well, that again seems like a reasonable reason :) Thanks for the diagnosis. The package not being listed anymore might be due to a stale update history, or failing tests: https://gist.github.com/choco-bot/fd692f8e4f294cd954c0593cdcddb00f

Anyway, I'm gonna choose another name for my package. Even if that one is gonna be removed at some time, I'd like to avoid the confusion of people thinking they'd get one thing but getting another instead.

Thanks for your help!

**Comment by npruehs** [comment]
Nope, same result :/

```
choco push tome-editor.0.5-alpha.nupkg -s https://chocolatey.org

Chocolatey v0.10.0
Attempting to push tome-editor.0.5-alpha.nupkg to https://chocolatey.org
Failed to process request. 'Not Found'.
The remote server returned an error: (404) Not Found..
```

**Comment by ferventcoder** [comment]
Just for me to personally know if there is an issue, would you mind pushing to 'https://chocolatey.org/' (the trailing slash at the end)?

I don't think that is the issue at all, so I'm not quite sure what the issue is just yet. Also I looked over the nuspec and nothing jumped out as wrong there.

**Comment by ferventcoder** [comment]
@npruehs Something was definitely up with the site. Give it a shot now.

**Comment by ferventcoder** [comment]
What is the total size of the package?

**Comment by npruehs** [comment]
Roughly about 30 MB. Thanks, will try later today!

**Comment by npruehs** [comment]
Trailing slash didn't fix it. Uploading the package from the website doesn't work as well - shouldn't at least that one work?

https://chocolatey.org/packages/upload

**Comment by ferventcoder** [comment]
30MB could be the factor. You definitely can't upload anything over something more than 5MB on the website. You would definitely need to use choco to push it. It's possible 30MB is too much for it as well.

**Comment by npruehs** [comment]
What now? That's a normal desktop application based on Qt, nothing fancy here, no large images or huge examples. Are there any plans of allowing submitting "larger" applications with the choco client? Is there any other possibility of uploading the package?

**Comment by ferventcoder** [comment]
@npruehs there are two methods of packaging, one of which is to host the binary somewhere and download it. 

It's `Install-ChocolateyPackage` vs `Install-ChocolateyInstallPackage` and `Install-ChocolateyZipFile` vs `Get-ChocolateyUnzip`. https://chocolatey.org/docs/helpers-reference

**Comment by npruehs** [comment]
Okay, switched to a smaller package that downloads a zip from GitHub, and that one worked immediately. Thanks for your help.

https://chocolatey.org/packages/tome-editor/0.5-alpha

Here are the scripts, for future reference:

https://github.com/npruehs/tome-editor/blob/develop/tome-editor.nuspec
https://github.com/npruehs/tome-editor/blob/develop/chocolateyinstall.ps1

You should work on your error messages, though ;)

**Comment by ferventcoder** [comment]
Agreed on error messages - #424

**Comment by ferventcoder** [comment]
The package size limit is now 150MB. Thanks

**Comment by ferventcoder** [comment]
We determined what and why the hard limit on #424.
