### ISSUE TITLE
Provide guidance/warnings about the ~150MB limit for package size

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#424]
https://gitter.im/chocolatey/choco?at=57d680f0ef19fa3f407a82a2

**Comment by petemounce** [comment]
It would be nice to get a 400 bad request back with a list of problems to correct, in the instance of publishing a package.

**Comment by ferventcoder** [comment]
We've seen this error at as low as 30MB. #423

**Comment by ferventcoder** [comment]
Actually, it could be 28 MB - here's why - https://msdn.microsoft.com/en-us/library/ms689462(v=vs.90).aspx

**Comment by ferventcoder** [comment]
See https://github.com/chocolatey/simple-server/pull/2 for details.

**Comment by ferventcoder** [comment]
First things first, let's bump to 200MB as that is the hard limit for Cloudflare.

**Comment by ferventcoder** [comment]
Started some guidance at https://github.com/chocolatey/choco/wiki/How-To-Host-Feed

**Comment by ferventcoder** [comment]
Will add more to FAQs. Created wiki docs ticket at https://github.com/chocolatey/choco-wiki/issues/41. Closing this out.
