### ISSUE TITLE
Instructions for installing specific version are incorrect

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/chocolatey.org#427]
On the site it says to install the specific version of a package the user should use `-version <version number>`
which results in this from the choco cmd line:

```
PS C:\WINDOWS\system32> cup phraseexpress -y -version 12.0.93
Parsing -version resulted in exception:
 Cannot bundle unregistered option '-e'.
Chocolatey v0.10.0 Business
```

the **actual** flag is `--version` (two dashes) which works as intended.

```
PS C:\WINDOWS\system32> cup phraseexpress -y --version 12.0.93
Chocolatey v0.10.0 Business
Upgrading the following packages:
phraseexpress
By upgrading you accept licenses for the packages.
phraseexpress v12.0.93 is the latest version available based on your source(s).
```

Anywhere we cite `-version` to be used with `choco` needs to be fixed.

**Comment by ferventcoder** [comment]
@bc3tech when you run with `-version` it produces that issue the first time through, but it works once the rest of the configuration options are loaded.

We may still have some older versions of choco in the wild, but the compiled version has been out for almost 1.5 years now, so perhaps it is time to upgrade for the newer versions. We designed Chocolatey so that both options would work. 

I also fixed that message for 0.10.1 to understand it is a warning but it doesn't affect the setting of `-version`.

**Comment by ferventcoder** [comment]
@bc3tech let me be clear though, are you seeing this message with no further output?

~~~sh
cup phraseexpress -y -version 12.0.93
Parsing -version resulted in exception:
 Cannot bundle unregistered option '-e'.
Chocolatey v0.10.0 Business
~~~

or is it

~~~sh
cup phraseexpress -y -version 12.0.93
Parsing -version resulted in exception:
 Cannot bundle unregistered option '-e'.
Chocolatey v0.10.0 Business
Upgrading the following packages:
phraseexpress
By upgrading you accept licenses for the packages.
phraseexpress v12.0.93 is the latest version available based on your source(s).
~~~

**Comment by ferventcoder** [comment]
Because if it is the former, then that is a bug we need to address quickly.

**Comment by ferventcoder** [comment]
@bc3tech can you confirm if this errors for you or it is just a warning message that looks like an error?

**Comment by brandonh-msft** [comment]
@ferventcoder it is the latter, which continues on but completely ignores the desired version specifier

**Comment by bc3tech** [comment]
@ferventcoder it is the latter, which continues on but completely ignores the desired version specifier 

so telling somebody on the package pages to use `-version` does **not** result in that specified version being installed.

**Comment by ferventcoder** [comment]
Wait, I've seen it work to provide the right version even though it throws the first error. 

`cup phraseexpress -y -version 12.0.93 --noop -d`

~~~sh
Parsing -version resulted in exception:
 Cannot bundle unregistered option '-e'.
[..snip..]
|Input='phraseexpress'|Version='12.0.93'|
[..snip..]
~~~

I think something else may be going on for you.

**Comment by brandonh-msft** [comment]
does it work if that version isn't approved in the packages list? that was the case for this version of phraseexpress (might still be)

**Comment by bc3tech** [comment]
does it work if that version isn't approved in the packages list? that was the case for this version of phraseexpress (might still be)

**Comment by ferventcoder** [comment]
It should, but it's possible it's timing and hitting a small caching issue on the community repository where it is not yet available by the cache.
