### ISSUE TITLE
unzip issue for install.ps1 on Windows Server 2012 R2 Core machines

### ISSUE THREAD

**Issue by JoshuaToth** [chocolatey/chocolatey.org#434]
x-post from https://github.com/chocolatey/choco/issues/997 which was the incorrect repo. 
### What You Are Seeing?

Now when installing via powershell on a Windows Server 2012 R2 Core "headless" environment chocolatey fails to unzip using the using built-in compression. It must use 7zip, which can be enabled with the environment variable, yes, but it does not work without it. 
### What is Expected?

~~The install.ps1 script is able to install without the use of 7zip in a Windows Server 2012 R2 Core environment. This was working previously and has stopped working very recently (03 - Oct - 2016).~~

I didn't realise this was already using 7za.exe by default and now it's not. 
### How Did You Get This To Happen? (Steps to Reproduce)

Run the install.ps1 script in an Windows Server 2012 R2 Core environment without the 7zip flag.  (like ami-e28fa681 for example in AWS)
### Output Log

``` sh
.\install.ps1 --debug --verbose
Getting latest version of the Chocolatey package for download.
Downloading https://chocolatey.org/api/v2/package/chocolatey/0.10.2 to C:\Users\ADMINI~1\AppData\Local\Temp\2\chocolatey\chocInstall\chocolatey.zip
Extracting C:\Users\ADMINI~1\AppData\Local\Temp\2\chocolatey\chocInstall\chocolatey.zip to C:\Users\ADMINI~1\AppData\Local\Temp\2\chocolatey\chocInstall...
Unable to unzip package using built-in compression. Set $env:chocolateyUseWindowsCompression = 'false' and call install again to use 7zip to unzip. Error: Exception calling "NameSpace" with "1" argument(s): "Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))" At C:\Users\Administrator\install.ps1:185 char:5
+     throw "Unable to unzip package using built-in compression. Set`$env:chocola ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Unable to unzip...4005 (E_FAIL))":String) [], RuntimeException
+ FullyQualifiedErrorId : Unable to unzip package using built-in compression. Set $env:chocolateyUseWindowsCompression = 'false' and call install again to use 7zip to unzip. Error: Exception calling "NameSpace" with "1" argument(s): "Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))"
```

**Comment by ferventcoder** [comment]
Thanks for doing that, much appreciated. So we don't always have a good way to communicate these issues in advance to folks, but we are working on that.

https://github.com/chocolatey/chocolatey.org/issues/432 is the particular issue with some of the driving factors.

**Comment by ferventcoder** [comment]
Is setting the environment variable a large setback for you?

I'm a little confused by your expectation - before it always used 7za.exe (7zip standalone).

**Comment by JoshuaToth** [comment]
Apologies. 
I'll amend my expectation. I didn't realize it was, by default, using 7za.exe. I assumed it was using the built-in compression. 

I did look for the install.ps1 file in the _other repo_ to check out the changes but of course it's not there so I didn't find it.

For us it's less of a setback, more of a break during what is our deployment process. (we have a bad habit of not pre-baking our AMI's with tools like chocolatey and including them in our deployment scripts.)

Unfortunately this all caused our 'staging' environment to break unexpectedly (which luckily it wasn't straight to live!)

We have as of today made sure to set that environment variable during our install/deployment process, since this was intentional it can be closed off. 

It is a little frustrating that a breaking change for core users who weren't previously setting that variable was pushed out. But that's up to you and that's the risk we run installing latest. 

Thanks for the quick reply.

**Comment by JoshuaToth** [comment]
Not sure, but just to speed up the process for people with this issue maybe consider adding a little more information into the error message like: 'Unable to unzip package using built-in compression. **Chocolatey no longer uses 7za.exe by default.** Set $env:chocolateyUseWindowsCompression = 'false' and call install again to use 7zip to unzip."

At least for a month or so while people sort out their processes..

**Comment by ferventcoder** [comment]
Good idea to add more help.

 One thing we've seen most organizations using Chocolatey do is use a copy of that install.ps1 internally that installs a known good version of Chocolatey (usually also internal). This does make the upgrades intentional, but it also shields from possible issues because it is deterministic.

For packages themselves, I'm making the assumption that after you've installed Chocolatey, everything else as far as packages is internal? Our recommendation for organizations that have a low tolerance for breakages is to host their own packages embedding software or pointing to internal download resources so that the process is completely repeatable and reliable.

**Comment by ferventcoder** [comment]
Apologies on the breaking change - the issue we have currently is we can make attempts to notify users of upcoming changes that could possibly affect them. But we have so many folks using Chocolatey that we don't always know until after a change.

In this case we should have added in the environment variable and set a big warning of the upcoming change in the script output, so folks could prepare for the change. We typically will attempt things like that, unless for some reason we have something broken for folks.

I think we may have a way to set it back, provide the warning that we are going to convert and wait a month. That should give folks the opportunity to notice the warning and make changes in preparation.

**Comment by JoshuaToth** [comment]
For these installs we do use internal packages after Chocolatey is installed. 
We may have to take that path for Chocolatey and keep the script somewhere and make those upgrades when we need. But really there hasn't been anything else in the ~18 months we've been using it as part of this install process and it was only our staging environment that was affected. 

I can understand that it must be incredibly difficult to try and reach out to so many people using Chocolatey in different ways. For us if you had added the warning a month in advance, we probably wouldn't have seen it anyway. Our install process is a bit of a fire and forget. 
Adding that bit of information to the error message would have helped a fair bit though, reducing confusion and speeding up the triage process. 

Thanks for all the help and quick response times!

**Comment by ferventcoder** [comment]
> For us if you had added the warning a month in advance, we probably wouldn't have seen it anyway. Our install process is a bit of a fire and forget. 

That's probably a fair statement and kind of what I had assumed it might be.

**Comment by ferventcoder** [comment]
Due to incompatibilities in newer Windows, which means that COM may not be available in an unattended way, this is going to go back to the default of 7z.
