### ISSUE TITLE
Add share buttons to blog posts

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey.org#441]
So that people can share blog posts to various places.

**Comment by gep13** [comment]
Too much?

![image](https://cloud.githubusercontent.com/assets/1271146/19386941/1cf80b38-920f-11e6-91db-95f7210ba70e.png)

**Comment by gep13** [comment]
Maybe this is better?

![image](https://cloud.githubusercontent.com/assets/1271146/19387032/a288839a-920f-11e6-955b-a3f9f5c3ce96.png)

**Comment by gep13** [comment]
Or, what about the following:

![image](https://cloud.githubusercontent.com/assets/1271146/19387127/2667651e-9210-11e6-84a9-c2469357083e.png)

Which scrolls with the page?  Obviously would need to pad over the main text a bit though.

**Comment by ferventcoder** [comment]
The last maybe put the share on the right side of the page?

**Comment by gep13** [comment]
Yip, that is doable.  Any preference on which share buttons are enabled by default?  In the screenshot above, there is twitter, tumblr (not sure why I included that one 😄 ), facebook, and print (again, not sure what I included that one 😄 ) It is all configurable though.

**Comment by ferventcoder** [comment]
print is good, tumblr, twitter, facebook are all good.

**Comment by designxsteph** [comment]
this has been implemented here https://github.com/chocolatey/chocolatey.org/commit/291f5d9c32c1dfc318d817e54ca6b81137d3832a
