### ISSUE TITLE
Approval by moderator that is not also an admin may remove testing exemption

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#442]
Watching this closely - https://gitter.im/chocolatey/chocolatey.org?at=58050f67b827179842cdb2b8

**Comment by ferventcoder** [comment]
Happened again - same circumstances - [November 1, 2016 5:05 PM](https://gitter.im/chocolatey/chocolatey.org?at=581911b495e079a822d087f8)

**Comment by ferventcoder** [comment]
cc @pascalberger

**Comment by ferventcoder** [comment]
FYI @gep13 @flcdrg

**Comment by flcdrg** [comment]
Me again for the Nov 1 instance :-( That got approved by me a few days after it was submitted. Would that have been around the time the testing VM went offline?

**Comment by ferventcoder** [comment]
I was not aware the testing VM went offline. Maybe we are talking about the VM used for existing packages, not the submitted packages - that one had been offline on purpose for awhile.

**Comment by flcdrg** [comment]
I could be using the wrong name. I know something was down a few weeks back and we had the queue building up.

**Comment by ferventcoder** [comment]
Wasn't you - bug in the system.
