### ISSUE TITLE
Package count incorrect

### ISSUE THREAD

**Issue by wjk** [chocolatey/chocolatey.org#443]
### What You Are Seeing?

As of this writing (~3:40 PM EDT) the Chocolatey Gallery lists "0 community-maintained packages". See below screenshot. I have verified it’s not a cookie issue by viewing the gallery logged-out using my browser's incognito feature; the problem persists.

### What is Expected?

Packages should be listed.

### How Did You Get This To Happen? (Steps to Reproduce)

Go to Chocolatey.org, click Packages.

----------

![Chocolatey.org Gallery Screenshot](https://cloud.githubusercontent.com/assets/1915951/19575494/b8b7f30e-96dc-11e6-8fed-6c9d00a6618a.png)

**Comment by wjk** [comment]
Browser is Safari 10.0 on macOS Sierra 10.12. Forgot to mention this in my original post.

**Comment by wjk** [comment]
And, now (as of ~4:20 PM EDT), there are now _7001_ (!) packages shown, but the top three packages in the list are all the `chocolatey` package. I suspect that the bulk of those 7,000 packages are duplicates of each other.

**Comment by wjk** [comment]
As of 6:00 PM EDT everything seems to be back to normal. There are 4225 packages shown, and no duplicates are immediately visible. I’m going to close this now.

**Comment by gep13** [comment]
@wjk thanks for the heads up on this.  It helps to identify and correct the problem!
