### ISSUE TITLE
404 Not Found returned when nupkg too large for gallery

### ISSUE THREAD

**Issue by brandonh-msft** [chocolatey/chocolatey.org#453]
I've got two packages whose installers are embedded in the `nupkg`. When I try to `cpush` to the community gallery, I get a 404 Not Found in the console. Shrink the size (by downloading the installer vs including it) and `push` is successful.

~~~sh
Chocolatey v0.10.3 Business
Attempting to push vivaldi.1.5.658.21-snapshot.nupkg to https://chocolatey.org/
Failed to process request. 'Not Found'.
The remote server returned an error: (404) Not Found..
~~~

**Comment by ferventcoder** [comment]
Related to #424.

**Comment by ferventcoder** [comment]
Actually, this could be a duplicate.

**Comment by ferventcoder** [comment]
Package sizes can now be 150MB. We determined why the hard limit (which we found was 28.61MB) in #424.
