### ISSUE TITLE
Add sub-category filtering to https://chocolatey.org/packages Moderator queue

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/chocolatey.org#456]
I'd like to be able to filter the results to just include the subcategory. eg. 

- Updated
- Responded
- Submitted
- Waiting for Maintainer
- Unreviewed

And also for the 'Responded/Updated' to filter if possible to those that I (as a moderator) had commented on

**Comment by ferventcoder** [comment]
That sounds quite helpful. 👍

**Comment by designxsteph** [comment]
This has been implemented here https://github.com/chocolatey/chocolatey.org/commit/feb90ceb33cbaef832b21f242286d84971ec6402 and https://github.com/chocolatey/chocolatey.org/commit/2cf837c761441f5ac6e0e05433d8f8e691c4178f
