### ISSUE TITLE
Integrate with community software grading site such as alternativeto.net

### ISSUE THREAD

**Issue by da9l** [chocolatey/chocolatey.org#457]
## Consider integrating http://alternativeto.net (or something similar)  in the chocolatey repository site.

Given an application A, Alternativeto.net lists other applications B,C... that has similar capabilities. 
It also lists other attributes of an application like platform, license, status and warnings (about bloatware for instance)
Alternativeto.net is community driven and therefore a pretty reliable source of information. 

If this information was made available on each package page in chocolatey it would be easier for users to assess the sanity of the application before installing it.

A good example is the cd ripper cdex. it has been reported to have gone over to a maintainer that has included bloatware in it.  http://alternativeto.net/software/cdex/

Possible attributes to list on a package page:
* Status
* Alternatives (top n)
* license model.

### Possible problems: 
I have no clue if alternativeto.net is integration friendly (API? Policy?)

**Comment by ferventcoder** [comment]
We'd need to reach out to them.

**Comment by ferventcoder** [comment]
We have to be very careful with this feature (and may not want to pursue it) for the reason of attracting vendors to maintain packages for their software. If the site was displaying competing products, it would not be something that would entice them to pursue or continue. That is the exact opposite of what we want to foster in the community repository. Does that sound fair?

**Comment by da9l** [comment]
Yep. I didn't consider that. You need to consider all stakeholders here.

**Comment by ferventcoder** [comment]
Maybe best to hold on this. Folks can still go over to alternativeto.net and perform searches manually.

I will say when I find vendors and other folks posting alternatives in the disqus thread without warrant, those are considered spam and deleted.

**Comment by ferventcoder** [comment]
Perhaps we close this as won't do unless we can find a way to do this respectfully (unfortunately I can't think of a way to do that currently that would not be considered a threat).

**Comment by da9l** [comment]
I agree with you. Being respectful is important. 

Thanks for taking your time to consider the idea!

Regards, Daniel
