### ISSUE TITLE
Very slow Web Page Load for Packages that have lots of files

### ISSUE THREAD

**Issue by RickStrahl** [chocolatey/chocolatey.org#474]
Some packages are extremely slow to load on the Web site especially packages that are embedded and list all files.

Example:
https://chocolatey.org/packages/MarkdownMonster.Portable

This page takes upwards of 15 seconds before anything displays. When it does display only half the page displays and the scrollbar is frozen. In fact when going to that link if I didn't know better i'd probably assume the link is broken and give up.

I'd expect this to just work and although there are a fair bit of files in this embedded source package this should not be so slow. If size is an issue then the files should not be shown unless you click on a link to see them (perhaps only in packages where files exceed a certain number of files).

**Comment by ferventcoder** [comment]
Thanks for logging this issue. I agree that this is substandard. I'm not sure if it will get fixed until after upcoming travel next week, but it is on my list of things to address soonest.

In the interim, perhaps some planned maintenance will help speed this up so that things do not freeze.

**Comment by ferventcoder** [comment]
Will keep you informed. Thanks again for everything @RickStrahl !

**Comment by RickStrahl** [comment]
Yeah I figured it'd be a good idea to file a bug and get it officially tracked :-)

**Comment by RickStrahl** [comment]
Any word on this? If anything this seems to be getting worse. Now what I see is that Choco just comes up with a blank page for about 10 seconds then something finally displays. 

I see 8 downloads of this package in nearly a month and while I don't expect a huge run on it in comparison to the full package, I know quite a few people requested this feature. So I wouldn't be surprised that the slow load that seems to hang is affecting access to this package.

**Comment by ferventcoder** [comment]
@RickStrahl this is on my list to find a solution for upcoming soon. There are just a couple of things ahead of it in prioritization.

**Comment by ferventcoder** [comment]
This is being pushed out currently.
