### ISSUE TITLE
Command to install a specific/old version is incorrect

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey/chocolatey.org#478]
When I view the page for a specific/old version of a package, the install command text changes and it's incorrect. For example...

![image](https://cloud.githubusercontent.com/assets/217842/22949338/ede54e06-f2cf-11e6-9d80-0a7f946da9e8.png)
https://chocolatey.org/packages/goggalaxy/1.0.2.958

If I try that command in my console...

```
PS> choco install goggalaxy -version 1.0.2.958
Parsing -version resulted in error (converted to warning):
 Cannot bundle unregistered option '-e'.
```

The current command line uses `-v` to show verbose messages and doesn't know what to do with the rest of the "options". 

```
 -v, --verbose
     Verbose - Show verbose messaging.
```

The install command text should use `--version` to install a specific/old version. There is no short option for version.

```
     --version=VALUE
     Version - A specific version to install. Defaults to unspecified.
```

**Comment by ferventcoder** [comment]
Note that it does get `--version` assigned appropriately.

**Comment by ferventcoder** [comment]
Sorry, I mean you may get `-v` (verbose), but it also later recognizes `-version` for the version field.

**Comment by AnthonyMastrean** [comment]
Oh, I see that... 

```
PS> choco install goggalaxy -version 1.0.2.958
Parsing -version resulted in error (converted to warning):
 Cannot bundle unregistered option '-e'.
Chocolatey v0.10.3
Installing the following packages:
goggalaxy
By installing you accept licenses for the packages.

goggalaxy v1.0.2.958 [Approved]
```

So, I still get unintended verbose messages and the scary "Cannot bundle" message. You're not saying this isn't a bug, right?

:wink:

**Comment by ferventcoder** [comment]
@AnthonyMastrean double negatives. I'm saying that while you get those messages, things still work appropriately. It's sort of how bundled options work and that you should always use `--` with options that are more than one characters as per the docs otherwise it confuses the options parser. However, yeah. This is annoying to see.

**Comment by AnthonyMastrean** [comment]
I also don't see `-version` or any short-form of the version option documented, so that's another hiccup.

```
     --version=VALUE
     Version - A specific version to install. Defaults to unspecified.
```

**Comment by ferventcoder** [comment]
Sorry for the confusion, there is no short form of version - short form is the one letter option, and not all options have a short form. So not a hiccup, just not there.

**Comment by AdmiringWorm** [comment]
@ferventcoder shouldn't this really be fixed/changed on the package details page?
Although it works, it's still inconsistent with the docs.

**Comment by AdmiringWorm** [comment]
I think this one is perhaps also related to #427

**Comment by ferventcoder** [comment]
We will call this a duplicate
