### ISSUE TITLE
Mixed content on pricing page

### ISSUE THREAD

**Issue by OmgImAlexis** [chocolatey/chocolatey.org#482]
On the pricing page the img for Gratipay is using an image served over HTTP even though the page uses HTTPS.

https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/Views/Pages/Pricing.cshtml#L215

**Comment by ferventcoder** [comment]
Thanks. That's not awesome. We'll need to look into ways to handle that.

**Comment by ferventcoder** [comment]
This is now deployed. Thanks for the note.
