### ISSUE TITLE
Do not allow uploads through web interface larger than 3MB - instruct to use `choco push`

### ISSUE THREAD

**Issue by jmbeach** [chocolatey/chocolatey.org#483]
### What You Are Seeing?

Uploading a package just leads to blank page.

### What is Expected?

Package upload to succeed or fail and show information

### How Did You Get This To Happen? (Steps to Reproduce)

Tried uploading the following file: [matrikon-sim.1.5.0.0.nupkg](http://www.mediafire.com/file/2g824bibndlnn88/matrikon-sim.1.5.0.0.nupkg) but I'm redirected to a blank page. Maybe it's just too large a file, but I'd like to see an error message at least.

**Comment by ferventcoder** [comment]
How big is the package? The size limit is 150MB, but I'm not sure you can do that size through the web interface. Really anything larger than 3MB, I would recommend pushing through `choco push`.

**Comment by ferventcoder** [comment]
48MB is definitely too large to use the web interface. Please use `choco push`

**Comment by jmbeach** [comment]
Will do. Could we have an error message though?

**Comment by ferventcoder** [comment]
I think we should probably add some documentation to the upload page.

**Comment by ferventcoder** [comment]
There should have been an error page, but yes, let's ensure that the web interface responds appropriately.

**Comment by ferventcoder** [comment]
Do the changes to the title look good?

**Comment by jmbeach** [comment]
Yep!

**Comment by ferventcoder** [comment]
This has been adjusted as part of the work for #798. I am going to say #798 supersedes this.
