### ISSUE TITLE
Feature request: only download 7za.exe if it is not already present

### ISSUE THREAD

**Issue by kewalaka** [chocolatey/chocolatey.org#491]
Would it be possible to add a 'Test-Path' statement to see if 7za.exe already exists in the temp folder, and if so skip the download?

This is helpful in scenarios where there is no internet, but we can use DSC to ensure the file is present prior to chocolatey being installed.

At present I work around this by using windows compression, using a chunk of DSC like this:

    Environment chocolateyDownloadUrl
    {
        Name  = "chocolateyDownloadUrl"
        Value = "https://chocolatey.myaddress.co.nz/install.ps1"
    }
    
    Environment chocolateyUseWindowsCompression
    {
        Name  = "chocolateyUseWindowsCompression"
        Value = "true"
    }
    
    cChocoInstaller installChoco
    {
        InstallDir             = "$env:PROGRAMDATA\chocolatey"
        ChocoInstallScriptUrl  = "https://chocolatey.myaddress.co.nz/install.ps1"
        DependsOn = @(  "[Environment]chocolateyDownloadUrl",
                        "[Environment]chocolateyUseWindowsCompression" )
    } 

@ferventcoder - I was slightly confused by your comments [here](https://github.com/chocolatey/choco/issues/1228) about the infrastructure management tools handling this?  If it's what I think you mean, I agree :), which is why the above makes sure the necessary environment variables are in place, and sources the install.ps1 from an internal repo.

**Comment by ferventcoder** [comment]
I think we were agreeing 👍

**Comment by ferventcoder** [comment]
@kewalaka this is open for contribution. :D

**Comment by AdmiringWorm** [comment]
@ferventcoder just curious. would this be as simple as just change the following line:
https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/Install.ps1#L182
to
```powershell
} elseif (!Test-Path $7zaExe) {
```

It certainly looks that way for me

**Comment by kewalaka** [comment]
@AdmiringWorm yes that's right. I just wanted something to refer to for the PR.  & then I was distracted by a surprise trip away.  Thanks for submitting the PR. :)
