### ISSUE TITLE
Why are we serving un-minified assets? 16kb is so key to my experience....

### ISSUE THREAD

**Issue by chad-ramos** [chocolatey/chocolatey.org#497]
### What You Are Seeing?
My oh my, in this day in age how is it possible that you are serving un-minified css to the client.  What, do you think we have time to wait for this file to just....download?

![browser](https://cloud.githubusercontent.com/assets/3170200/25028565/0fad21ca-207b-11e7-890e-3124c10efb3e.png)

### What is Expected?
I only expect the best.  Clearly, someone missed the boat when it comes to optimization. Sheesh...I want my 16kb back? 
![min](https://cloud.githubusercontent.com/assets/3170200/25028607/4c8a27dc-207b-11e7-943b-5c508a07f92a.png)

### How Did You Get This To Happen? (Steps to Reproduce)
Yeah, I think I just "went to your site".

:smile: All in good fun.  Keep up the good work.  

If you are interested, I am more than willing to set a Gulp pipeline to handle this.

**Comment by ferventcoder** [comment]
You got that thing to minify?!

**Comment by ferventcoder** [comment]
Or should I say minify and bundle is where this went wrong

**Comment by chad-ramos** [comment]
@ferventcoder So in all seriousness, I don't what compelled me to take a look at the assets this site was serving but regardless, I did notice your "style" sheet was un-minified.  Looks like there was an attempt to get the CSS assets optimized through the ASP.NET Bundler and that it might have been abandoned in favor of hard coding with a cache buster.  Is this correct?  Was the Bundler something you could not get working or decided to abandon? 

I can try and put a PR together to see if I can get that working for you or if you're interested, explore something like Gulp to handle it for you.

**Comment by ferventcoder** [comment]
Not bundler, it was an older technology. Perhaps we should explore the included bundling

**Comment by chad-ramos** [comment]
@ferventcoder - After finally getting around to exploring this, I have the following to say...

### Implementing the bundler by way of Microsoft.AspNet.Web.Optimization

I actually forgot that this bundling service does not actually have a native way to bust cache.  Meaning, to make this work we would...

- Bring in the NuGet package.
- Scaffold the necessary configuration
- Create a new static "Helper" class that wraps the native Optimization functionality in order to produce the necessary hanging query string `\style.cs?v=some-string` needed to bust the cache.

The challenge would be to decide on a way to produce and maintain the {some-string} portion of the equation. As of now, you are simply hard coding it. 

- Do you update the hard-coded "Helper" class with this value everytime you want to change this style sheet?
- Do you pull it in from configuration?

Typically, to remove the "remember to do this" portion of the equation, we would not hard-code it.  We would rely on a file change date. 

[http://madskristensen.net/post/cache-busting-in-aspnet](http://madskristensen.net/post/cache-busting-in-aspnet)

Or even better, we would use a file hash.

So yeah, a bit of overhead to massage the Microsoft.AspNet.Web.Optimization method into the project.

### Script It

As mentioned earlier, you could bring in Gulp to handle it.

- Pull in necessary dependencies
- Tie your Gulp task up with the Visual Task Runner, which would eliminate some of the "remember" portion of the equation.
- Negatively, you would be required to have node available,

Some decisions to made with this choice...
- Do you rely on development to produce the final output or do you have you build server do it?  That is assuming you have a CI pipeline for this project. 
- Production scripts would end up in the same place they are now but you would need to introduce a "dev" folder in the project to house the non-optimized (dev) versions.
- Cache busting could be handled exactly like you are doing it today or you can introduce one of the concepts mentioned above. 

So yeah, let me know what you think.

**Comment by ferventcoder** [comment]
We already have a way for this to work if we can get it to work with minifying the asset.

**Comment by ferventcoder** [comment]
It's being excluded right now - see https://github.com/chocolatey/chocolatey.org/blob/c83ab0e610f275102b53f85ff2a1d8c5a5d68c0f/chocolatey/Website/Infrastructure/CassetteConfiguration.cs#L38

**Comment by ferventcoder** [comment]
That's actually sad that the built-in asp.net stuff didn't at least get to feature parity with Cassette.

**Comment by chad-ramos** [comment]
Gotcha.  I was wondering what some of that disabled stuff was in your layout. 

I actually never heard of Cassette before.  Looking at their docs, it looks like it set out to do what you would want it to do.  Looking at their source, it looks like the project is dead.  I would suspect that has to do with Microsoft rolling out their own implementation. 

That being said, am I safe to assume you do not want to use Gulp or anything in that domain of tooling? 

I play around and to see if I can come up with a way to "auto-bust" a cache with the .NET bundler.  I recall moving away from it a few years back for this reason but you never know.

**Comment by ferventcoder** [comment]
For Gulp - not yet.

**Comment by ferventcoder** [comment]
Yes - Cassette has had no major development since asp.net 4 had the bundler - however cassette works very well.
