### ISSUE TITLE
Cloudflare returning 524 on push - even though package push is successful

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#499]
Cloudflare is returning origin timeouts even though pushing is successful. This has been noted in Gitter and with customers. 

References:
* https://groups.google.com/d/msgid/chocolatey/35db1241-0a63-4d84-9981-86581932c904%40googlegroups.com
* https://gitter.im/chocolatey/chocolatey-coreteampackages?at=58f54411bdf4acc1126bccac / https://gitter.im/chocolatey/chocolatey-coreteampackages?at=58f642bb8fcce56b2013aa11
* https://chocolatey.zendesk.com/agent/tickets/726

**Comment by ferventcoder** [comment]
CloudFlare has a default timeout of 100 seconds. Looking to work around this now. From https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524-A-timeout-occurred

> If you regularly run HTTP requests that take over 100 seconds to complete (for example large data exports), one alternative is to move those long-running processes to a subdomain that is not proxied by Cloudflare. That subdomain would have the orange cloud icon toggled to grey in the Cloudflare DNS Settings. Note that you cannot use a Page Rule to avoid a 524 error.

**Comment by ferventcoder** [comment]
The likely culprit is non-prioritized traffic. At 22M requests per day with 8TB data transfer, there are certain things that are starting to have issues. We definitely need to ensure pushing does not hit a timeout.

**Comment by AdmiringWorm** [comment]
this was also noted back in december, although it didn't happen as frequently as it does today.
https://github.com/chocolatey/choco/issues/1087

**Comment by majkinetor** [comment]
It happened way before that even. At least for a year.

**Comment by shiftkey** [comment]
Just encountered this today, and because of the `HTTP 524` the deploy script didn't continue on publishing artifacts, which meant the automated verification failed.

[Build Output](https://ci.appveyor.com/project/shiftkey/carnac/build/2.0.0.73)

> Publishing carnac.2.0.0.73.nupkg to https://chocolatey.org/api/v2/package...
> Error publishing package. NuGet server returned 524: Origin Time-out

Package Validation failure: https://gist.github.com/109dce6d37b34cc45b86cc03cae10076

**Comment by bc3tech** [comment]
happened for a while again this morning w/ me trying to update `Vivaldi`. eventually pushed thru.

**Comment by ferventcoder** [comment]
Folks - use https://package.chocolatey.org to push. I am going to update documentation for this now and adjust it to work as the default for Chocolatey v0.10.6+.

**Comment by ferventcoder** [comment]
If someone else can verify that they no longer see issues when using that push url, that would be great!

**Comment by majkinetor** [comment]
I changed AU to see how that behaves on core team packages: https://github.com/majkinetor/au/commit/46bf476a9a06645eea15c20c75b637cb349e4bed

**Comment by ferventcoder** [comment]
I'm not sold on the subdomain name just yet - push is what I started out with and didn't like it. I also didn't like submit. So then I settled on package, not to be confused with packages.

**Comment by ferventcoder** [comment]
Push may be best to alleviate any confusion.

**Comment by majkinetor** [comment]
Yeah, `push` is IMO more suitable. Just let us know here so I can change the AU to use the new source.

**Comment by ferventcoder** [comment]
I changed it over to https://push.chocolatey.org - please adjust accordingly. HTH

**Comment by majkinetor** [comment]
OK, changed AU accordingly.

**Comment by AdmiringWorm** [comment]
Looks like the new push url works great, can't say I've seen any problems with pushing yet on the core team packages repo.

**Comment by ferventcoder** [comment]
I think this is good to close as deployed

**Comment by brandonh-msft** [comment]
what's the action item for consumers? v0.10.5 still has this problem as of right now.
~~~
Chocolatey v0.10.5 Professional
Attempting to push vivaldi.1.10.845.3-snapshot.nupkg to https://chocolatey.org/
Failed to process request. 'Origin Time-out'.
The remote server returned an error: (524) Origin Time-out..
~~~

**Comment by ferventcoder** [comment]
Adjust your push location. Change your API key to use `https://push.chocolatey.org/`.


Then `choco push -s https://push.chocolatey.org/`

Follow https://github.com/chocolatey/choco/issues/1285 and see that this will be fixed in 0.10.6.

**Comment by ferventcoder** [comment]
Of note, to keep the change in location from being a breaking change, if you have no api key for push, but you have one for the old location, it will use the old location. So you will need to update that API key anyway to take advantage of the new location, and 0.10.6 will automatically prefer push url over the old (unless of course you have an api key set ONLY for the old).

**Comment by brandonh-msft** [comment]
how does one *remote* an apikey that's been set? Not seeing anything under `-h` or the help for `apikey` or `setapikey`... tried using `-s` w/o `-k` and specifying `-k` w/ no value...

**Comment by brandonh-msft** [comment]
ended up just manually editing `chocolatey.config`

**Comment by ferventcoder** [comment]
@brandonh-msft may not be a bad idea to follow up with an issue for removing api keys - https://github.com/chocolatey/choco/issues/new (just so we can get that competed).
