### ISSUE TITLE
FEATURE REQUEST (DOWNGRADE): cpack and cpush don't need elevated privileges

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey.org#500]
choco v0.10.5 added the feature of choco commands running with elevated privileges.

Some choco commands such as cpack, cpush, and clist (others?) shouldn't require elevated privileges.

**Comment by ferventcoder** [comment]
Wrong repository. But read over https://github.com/chocolatey/choco/issues/1054 to understand the change.

**Comment by ferventcoder** [comment]
Duplicate of https://github.com/chocolatey/choco/issues/1307

**Comment by ferventcoder** [comment]
We are moving 0.10.7 back while we discuss a better way to handle this per command in 1307.
