### ISSUE TITLE
Sign Install.ps1 with new certificate - ensure valid encoding

### ISSUE THREAD

**Issue by gqqnbig** [chocolatey/chocolatey.org#508]
I tried to install chocolatey by running the powershell script. powershell gives me error that it cannot load the script because the certificate is expired.

**Comment by ferventcoder** [comment]
Do you mean the authenticode signature? Or the SSL/TLS cert for the site?

The latter was recently updated, the former is signed with a timestamp server so it is okay to be past that date. 

Can you please post the exact issue you are seeing? Thanks!

**Comment by gqqnbig** [comment]
@ferventcoder I first tried to run 

iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

it fails, saying the file "

> might have been changed by an unauthorized user
> or process, because the hash of the file does not match the hash stored in the digital signature.

"
![1](https://cloud.githubusercontent.com/assets/614159/25837860/bec062bc-3444-11e7-8a57-7c9922fed137.JPG)

Then I downloaded the ps1 file manually on browser, then execute it. It fails again, saying "

> the file cannot be loaded. A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.

"

![2](https://cloud.githubusercontent.com/assets/614159/25837944/34f5f6b8-3445-11e7-9d00-cc451c507813.JPG)

**Comment by ferventcoder** [comment]
The hash mismatch we've found is a now a known bug with PowerShell - https://github.com/chocolatey/choco/issues/1203 (we filed https://github.com/PowerShell/PowerShell/issues/3361 to let them know about the issue). 

Let me get that file re-signed and pushed out.

**Comment by ferventcoder** [comment]
Actually, it's not https://chocolatey.org/install.ps1 that is giving you the first issue, it's the chocolatey.nupkg install files themselves. That has been fixed for 0.10.6 with https://github.com/chocolatey/choco/issues/1225. We discovered another issue with PowerShell, which we filed https://github.com/PowerShell/PowerShell/issues/3466

Unfortunately we hit the second issue with new text added (a unicode character) after we verified the first issue to make sure it was good to go, so we didn't catch it in time for release. You may wish to use Bypass for that first install.

**Comment by ferventcoder** [comment]
@gqqnbig Give this a shot now with https://chocolatey.org/install.ps1. 

Do keep in mind that the chocolateysetup.psm1 is still going to run into issues until 0.10.6. You can install the beta to verify it is fixed, you will want to set the script up in the following way:

~~~powershell
$env:chocolateyVersion = '0.10.6-beta-20170503'
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
~~~

HTH

**Comment by gqqnbig** [comment]
It's working now. Thanks!
