### ISSUE TITLE
Package upload size is lower than the expected 150 MB

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey.org#521]
### What You Are Seeing?
Recently tried to upload the embedded package [hedgewars](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/hedgewars) which had a total package size of 144 MB, but failed to push with an error message with `Request Entity Too Large` (as can be seen on the following [appveyor build](https://ci.appveyor.com/project/chocolatey/chocolatey-coreteampackages/build/1856#L350).

### What is Expected?
Since it have been mentioned in the past that the limit for a package is 150MB, I was expecting the 144MB package to be pushed, and not to be rejected with an error message.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Clone <https://github.com/chocolatey/chocolatey-coreteampackages>
2. run `.\test_all.ps1 hedgewars` (make sure to install [AU](https://chocolatey.org/packages/au) if it isn't already installed)
3. navigate to `automatic\hedgewars`
4. try pushing the package.

**Comment by AdmiringWorm** [comment]
✨ 
This issue have now been fixed

**Comment by ferventcoder** [comment]
https://support.appharbor.com/discussions/problems/90864-is-there-an-upload-limit-on-the-gateway is where this was being limited.
