### ISSUE TITLE
Choco new should output a .nuspec in UTF-8 without a byte order mark

### ISSUE THREAD

**Issue by jnm2** [chocolatey/chocolatey.org#527]
I'm totally on board with this:

> Do not save your *.nuspec files with a Byte Order Mark (BOM). A BOM is neither required nor recommended for UTF-8, because it can lead to several issues.

https://chocolatey.org/docs/create-packages#character-encoding

But choco new is not. It's currently creating UTF-8-BOM nuspecs.

**Comment by ferventcoder** [comment]
Please file issues for the choco tool at https://github.com/chocolatey/choco/issues/new. Thanks!
