### ISSUE TITLE
Website upload form should mention size limitation

### ISSUE THREAD

**Issue by gregoirefra** [chocolatey/chocolatey.org#529]
I am seeing issue with new packages upload. I either get a 524 error from cloudflare or the broken page from chocolatey telling me there is a bug that as been recorded. 

Test on a google chrome, microsoft edge and microsoft internet explorer 11

My packages was made with powershell 5 and has been tested locally. After the error, if I go back to the upload page I am brought back to the verifiy option without having to reupload my package. My package is kind of big I think, it's 27.7mb.

**Comment by ferventcoder** [comment]
Use `choco push` for anything bigger than 5MB. I'm not sure the upload form is designed well enough to handle bigger files.

**Comment by ferventcoder** [comment]
Also added the note to our conversation on Gitter at [July 24, 2017 2:54 PM](https://gitter.im/chocolatey/chocolatey.org?at=5976508076a757f80841a427)

**Comment by ferventcoder** [comment]
I think we'll leave this open to ensure the documentation on the website upload form also mentions the limitation.

**Comment by ferventcoder** [comment]
This is being pushed out now.
