### ISSUE TITLE
Account Name not shown in Account Settings

### ISSUE THREAD

**Issue by kenmaglio** [chocolatey/chocolatey.org#532]
### What You Are Seeing?
Cannot View Account Name in Account Settings on Chocolatey.org

### What is Expected?
I would expect to see our Account Name above / around the Email Display on the site under Account.

### How Did You Get This To Happen? (Steps to Reproduce)
Just went to account, and it's not there!

**Comment by ferventcoder** [comment]
This has been released. You will see username in the account heading (give the system a few minutes to fully release the code).
