### ISSUE TITLE
Add Copy button next to choco install command line

### ISSUE THREAD

**Issue by adriens** [chocolatey/chocolatey.org#556]
# This is a feature request for the website

When listing the packages, it would be very nice to get the copy button, just next to the 

```
choco install ....
```

Actually we have to :

1. select the command line
2. copy
3. paste

With this approach, we could just have to :

1. Click
2. Paste

Take a look below what it could look like :

![copy-choco](https://user-images.githubusercontent.com/5235127/37441783-29736940-2857-11e8-9274-ae3e4a234e6e.png)

**Comment by gep13** [comment]
@adriens actually, I think that this is the same as this issue:  https://github.com/chocolatey/chocolatey.org/issues/264

**Comment by adriens** [comment]
Very well explained by @gep13 :

![2018-03-16 15_38_04-installation](https://user-images.githubusercontent.com/5235127/37504078-3fdced76-2930-11e8-9b90-3c974c6dcb26.png)

**Comment by designxsteph** [comment]
This has been implemented here https://github.com/chocolatey/chocolatey.org/commit/f57d269e36235eb7b64f2282d6dc573ede945b18
