### ISSUE TITLE
Chocolatey.org returns value of API key passed in error messages

### ISSUE THREAD

**Issue by athomas** [chocolatey/chocolatey.org#560]
https://github.com/chocolatey/chocolatey.org/blob/425a8f1808c42c23416cb64e341f6c87560df665/chocolatey/Website/Strings.resx#L175

This can leak API keys if the server doesn't accept the API Key for some reason. Mostly that means the API key is actually invalid, but it might be a valid key for another source. Chocolatey should not leak these keys.

E.g. a choco push -k secret might print this:
Chocolatey v0.10.10
Attempting to push package.nupkg to https://push.chocolatey.org/
Failed to process request. 'The API key 'secret' is invalid.'. 
The remote server returned an error: (400) Bad Request..

**Comment by ferventcoder** [comment]
Thanks for reporting this. This is not as serious as other security issues, but keep in mind the responsible thing to do for security type issues is to report them directly to us first. See https://chocolatey.org/security

**Comment by ferventcoder** [comment]
Changed the title here - "leaks" is something I saw and immediately took note, then I read this and realized it only returns what you pass it. That is not the same thing as a leak - leak is when you are getting something to provide data you didn't already have.

**Comment by ferventcoder** [comment]
I am curious if you can elaborate on the bit about "it might be a valid key for another source" - you choose what to pass here, it is not going to pass an API key set for a different source. 

The communication is over SSL, so it's not going to be seen by 3rd parties without some crazy DNS poisoning on the client, but even then, they key needs to be passed.

**Full stop we should not pass the value back to the client.** I'm just assessing the weight of this. Input definitely appreciated.

**Comment by athomas** [comment]
Sorry, I didn't mean to be overly alarmist. By "it might be a valid key for another source" I meant that if I make a mistake and pass the wrong secret to chocolatey (or if there is a bug in chocolatey that makes it reject a valid key) I think it's a bad practice to echo the key. The same way a password entry form shouldn't echo the password back even if it's wrong. Not because you don't know what you typed, but because somebody might be looking over your shoulder.

In my particular use case, this amounts to a leak: I don't run choco push myself, it runs on a CI build. The logs of that build are widely available and therefore I need to take care to ensure that they do not contain any sensitive information. Hence, I intentionally configured a bogus API key to see if it would show up anywhere in the logs.

Regarding https://chocolatey.org/security, I should've used that. I went to https://chocolatey.org/bugs and this repo seemed the most appropriate (since it was a backend issue). It might be a good idea to add a "Is it a security issue?" question to https://chocolatey.org/bugs to prevent other people from making the same mistake.

**Comment by ferventcoder** [comment]
@athomas Good idea, I will capture that change as well while I'm fixing this.
