### ISSUE TITLE
Understanding, documenting and improving the build process

### ISSUE THREAD

**Issue by zippy1981** [chocolatey/chocolatey.org#58]
I'm hacking on the Chocolatey gallery for the first time. I'd like to clarify my understanding of a few things about the way chocolatey.org is setup, Then I'd like to add some of this understanding to the readme, and make some changes:

* So it seems build.bat in the root directory builds the NugetGallery project, and as a post step copies files to the chocolatey folder.
* The views (or at least [ContactOwners.cshtml](https://github.com/chocolatey/chocolatey.org/blob/master/nugetgallery/Website/Views/Packages/ContactOwners.cshtml)) don't seem to get copied over. Is that intentional?
* Should I delete [nugetgallery/build.bat](https://github.com/chocolatey/chocolatey.org/blob/master/nugetgallery/build.bat)
* Should I commit another solution that builds the nuget gallery and gallery facts? 
* Should I delete all the files in the chocolatey folder that are overwritten by build.bat?

**Comment by ferventcoder** [comment]
This is a bit old. I'm closing for now, as the question of items in here is no longer valid at this time.
