### ISSUE TITLE
Commits 57657a0 and e7c9308 broke install.ps1 signature

### ISSUE THREAD

**Issue by hseg** [chocolatey/chocolatey.org#581]
Downloaded and verified `install.ps1`, `Get-AuthenticodeSignature` complains of a `HashMismatch`.
Checking through the logs, found commits 57657a0 and e7c9308 both edited the copyright lines of some scripts without also updating the signature block.

**Comment by gep13** [comment]
@hseg thanks again for reporting this.  New versions of these files with the corrected Authenticode Signature will be pushed shortly.
