### ISSUE TITLE
Send intermediates for push.chocolatey.org?

### ISSUE THREAD

**Issue by philipjameson** [chocolatey/chocolatey.org#584]
### What You Are Seeing?

I'm seeing some issues when I try to do a put of a new package (buck is the package) via python's requests module to https://push.chocolatey.org/api/v2/package. However, I wasn't seeing TLS verification problems on chocolatey.org (I was getting timeouts there, and docs seem to suggest using push.chocolatey.org). Digging in a bit, it looks like cloudflare may be sending the intermediates, but the origin server is not. 

### What is Expected?

That we get the godaddy intermediates sent down when hitting the origin like we do for cloudflare. Looks like the nginx docs aren't linkable, but it's a pretty straightforward config change (http://nginx.org/en/docs/http/configuring_https_servers.html, ctrl-f for "SSL certificate chains")

### How Did You Get This To Happen? (Steps to Reproduce)

openssl s_client connection for push.chocolatey.org: https://gist.github.com/philipjameson/a079269bd6822356f0b9eb9b37dc86e9
openssl s_client connection for chocolatey.org: https://gist.github.com/philipjameson/c4a0cd2e3e0c0a4a9ae40c30b6795963

**Comment by philipjameson** [comment]
ping

**Comment by TheCakeIsNaOH** [comment]
This is also causing issues with choco push when running on mono. 

It can be worked around by importing the intermediate cert, but I would prefer that it be fixed on the server end. 

Workarround for the choco docker container-
`curl https://gist.githubusercontent.com/TheCakeIsNaOH/57254dc7f99b528d495e4f4e52de7f03/raw/ee936d6efddac485091ca6de833863f04ea77e39/Go%2520Daddy%2520Secure%2520Certificate%2520Authority%2520-%2520G2.crt >> /etc/ssl/certs/ca-certificates.crt`

`cert-sync /etc/ssl/certs/ca-certificates.crt`

**Comment by ferventcoder** [comment]
@rekire @philipjameson That's weird that the intermediates are not being sent. It sounds like there is still an issue based on https://gitter.im/chocolatey/chocolatey.org?at=5d9ce8eb97358746731c105c. We'll have a look and ensure these are correct.

**Comment by rekire** [comment]
Thank you for checking this. That should be simple to fix. In worst case a couple of openssl commands.

**Comment by ferventcoder** [comment]
This should be good to go now. Can one of you verify?

**Comment by mkevenaar** [comment]
@ferventcoder ssllabs is showing the full chain now. So that’s correct now

**Comment by ferventcoder** [comment]
I saw that as well, I was going to wait on others to report that things are working. Apologies it took awhile to read and fix, in reality it should have been dealt with much sooner. Apologies.

**Comment by TheCakeIsNaOH** [comment]
Can confirm working for me. Thanks for fixing :)

**Comment by rfay** [comment]
Yup, working, thanks so much.
