### ISSUE TITLE
Show hashes for vsix files as well

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey.org#586]
In the same way that we do for exe, msi, zip, etc.

An example package is here:

https://chocolatey.org/packages/disposablefixer

**Comment by ferventcoder** [comment]
@gep13 always feel free to add the labels to the right depending on how you think this should be set. I've just added this as it was a quick fix .

**Comment by ferventcoder** [comment]
This has just been pushed live - so any new packages submitted with VSIX will show as binaries and show the hashes.
