### ISSUE TITLE
Packages that are not RTM yet are hidden from the gallery

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/chocolatey.org#59]
A lot of FOSS exists for a long time before ever becoming RTM.

`Pirate Browser` is such a package that is pre-release and hidden because there is no non-pre-release yet. 

Shouldn't this one be listed?

**Comment by TomOne** [comment]
@Redsandro is right. This is a major design flaw of the NuGet Gallery/Chocolatey Gallery.

As moderator I’ve experienced several times that maintainers pushed duplicate packages or incorrect versions because of this.

Packages that only consist of prerelease versions should be visible by default in the gallery. The current way how prerelease version are handled is flawed and does not make sense.

**Comment by ferventcoder** [comment]
This is the real question - Is less than v1 considered pre-release?

If you want to install a prerelease, should you have to indicate -pre if
there are only prereleases?

On Thursday, January 1, 2015, TomOne <notifications@github.com> wrote:

> @Redsandro <https://github.com/Redsandro> is right. This is a major
> design flaw of the NuGet Gallery/Chocolatey Gallery.
>
> As moderator I’ve experienced several times that maintainers pushed
> duplicate packages or incorrect versions because of this.
>
> Packages that only consist of prerelease versions should be visible by
> default in the gallery. The current way how prerelease version are handled
> is flawed and does not make sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/59#issuecomment-68508613>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
There is also a strange period of time when the maintainers are releasing
prereleases of a version and there are no other releases.

On Friday, January 2, 2015, Rob Reynolds <ferventcoder@gmail.com> wrote:

> This is the real question - Is less than v1 considered pre-release?
>
> If you want to install a prerelease, should you have to indicate -pre if
> there are only prereleases?
>
> On Thursday, January 1, 2015, TomOne <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @Redsandro <https://github.com/Redsandro> is right. This is a major
>> design flaw of the NuGet Gallery/Chocolatey Gallery.
>>
>> As moderator I’ve experienced several times that maintainers pushed
>> duplicate packages or incorrect versions because of this.
>>
>> Packages that only consist of prerelease versions should be visible by
>> default in the gallery. The current way how prerelease version are handled
>> is flawed and does not make sense.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/chocolatey/chocolatey.org/issues/59#issuecomment-68508613>
>> .
>>
>
>
> --
>
> Rob
> "Be passionate in all you do"
>
> http://devlicio.us/blogs/rob_reynolds
> http://ferventcoder.com
> http://twitter.com/ferventcoder
>
>

-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by gep13** [comment]
> This is the real question - Is less than v1 considered pre-release?

If it does, then the Chocolatey Package itself shouldn't appear on the site :smile_cat: 

Personally, anything to me that says alpha, beta, pre, or anything like that shouldn't magically get installed.  This to me indicates that the package maintainers, or application authors, are indicating "use at your own risk".  As such, at install time, it should be a conscious effort on the part of the person installing it to say, "I am ok with the risk", so they put ```-pre``` on the installation command.  IMO, that should not change.

Having said that, I do agree that allowing packages that exist as pre-release only, should turn up in a search on the site, and should be visible.

**Comment by ferventcoder** [comment]
Yeah. I think we can all agree that the switch to see pre release just goes
away.

On Friday, January 2, 2015, Gary Ewan Park <notifications@github.com> wrote:

> This is the real question - Is less than v1 considered pre-release?
>
> If it does, then the Chocolatey Package itself shouldn't appear on the
> site [image: :smile_cat:]
>
> Personally, anything to me that says alpha, beta, pre, or anything like
> that shouldn't magically get installed. This to me indicates that the
> package maintainers, or application authors, are indicating "use at your
> own risk". As such, at install time, it should be a conscious effort on the
> part of the person installing it to say, "I am ok with the risk", so they
> put -pre on the installation command. IMO, that should not change.
>
> Having said that, I do agree that allowing packages that exist as
> pre-release only, should turn up in a search on the site, and should be
> visible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/59#issuecomment-68554268>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by TomOne** [comment]
> Having said that, I do agree that allowing packages that exist as pre-release only, should turn up in a search on the site, and should be visible.

:+1: 

> Personally, anything to me that says alpha, beta, pre, or anything like that shouldn't magically get installed.

For packages that have stable versions too, yes. But what about prerelease-only packgaes? The purpose of a package manager would be deceived if they wouldn’t update automatically. In my opinion, prerelease-only packages should definitely update automatically. Or why would one for example not want the latest firefox-developer for instance?

@ferventcoder 

> Yeah. I think we can all agree that the switch to see pre release just goes away.

Not sure what you mean with that. Should the pre-release switch go away completely?

**Comment by ferventcoder** [comment]
@TomOne no - if you look on the packages page, there is a little drop down that says include prerelease. I'm talking about removing that completely.

**Comment by ferventcoder** [comment]
> For packages that have stable versions too, yes. But what about prerelease-only packgaes? The purpose of a package manager would be deceived if they wouldn’t update automatically. In my opinion, prerelease-only packages should definitely update automatically. Or why would one for example not want the latest firefox-developer for instance?

Back to my original question @TomOne - Is less than v1 considered pre-release? I would say not. If you are installing firefox-developer, you are already opting into another stream (that we would normally call a prerelease). Terminology aside, it's not the mainstream release, but it ***is*** the release for that package. In my mind, there is no such thing as a permanent pre-release only package. If it also has releases, then the two packages should be combined into one. There is no reason for the pre-release only package.

But let's go back to my original question - is less than v1 considered pre-release? I'm curious what your answer is for this. @Redsandro as well.

**Comment by TomOne** [comment]
> @TomOne no - if you look on the packages page, there is a little drop down that says include prerelease. I'm talking about removing that completely.

Actually I meant exactly that switch. :bowtie:

Sorry for the confusion. I had some doubts, but now they are clarified.

**Comment by TomOne** [comment]
> Back to my original question @TomOne - Is less than v1 considered pre-release?

Not in a narrow sense.

> Terminology aside, it's not the mainstream release

I think there’s no way to leave terminology aside here. I think that depends on the developer’s taste. 

One could version it as `0.9.9` or just as well `1.0-beta1` or whatever. There are different versioning schemes out there. For instance, some projects such as Gnome, have equal numbers in the second segment as stable versions and unequal versions as unstable versions.

Counter question: Is then Gnome 3.15.x a pre-release? :smile:

**Comment by ferventcoder** [comment]
> Counter question: Is then Gnome 3.15.x a pre-release?

Isn't it the even numbers (major version) are considered unstable? This seems a trick question ;)
However, I'm somewhat familiar with the numbering scheme used by many GNU projects. It's an interesting one, and I bet they have a different package for each major version. I'm guessing that they may or may not have a package per major version. gnome doesn't appear to though.

**Comment by TomOne** [comment]
> If you are installing firefox-developer, you are already opting into another stream

Nope, not in this case. firefox-developer is a separate browsers that can be installed run simultaneously with Firefox stable. I actually have that on my machine. The same applies to Chrome stable and Chrome Canary. So I might not agree with your approach of combining them.

**Comment by ferventcoder** [comment]
> Nope, not in this case. firefox-developer is a separate browsers that can be installed run simultaneously with Firefox stable. I actually have that on my machine. The same applies to Chrome stable and Chrome Canary. So I might not agree with your approach of combining them.

So for the package itself, you would agree that it can be a release, not a prerelease. I'm already opting into chrome canary, so of course I want every release.

**Comment by ferventcoder** [comment]
Prerelease means different things to different folks. But we need a definition that works for Chocolatey that we can agree on.

**Comment by ferventcoder** [comment]
> One could version it as 0.9.9 or just as well 1.0-beta1 or whatever. There are different versioning schemes out there. 

I would argue this is true, but Chocolatey / NuGet has a bit of a stricter numbering scheme. As long as packages can work with with that, then fine. 

Side note: we probably need a text version as well for things like `ruby 2.1.3p555`

**Comment by TomOne** [comment]
> I would argue this is true, but Chocolatey / NuGet has a bit of a stricter numbering scheme. As long as packages can work with with that, then all is well.

That is what bothers me. Restricting to SemVer might be OK for specific package managers such as NuGet or npm, but not for general application package managers such as Chocolatey. In fact neither apt-get nor yum have such suboptimal versioning restrictions. I opened an issue about this topic some time ago: https://github.com/chocolatey/chocolatey/issues/330. Basically Chocolatey needs this for a proper versioning scheme:

* Don’t restrict to SemVer
* Allow alphanumeric characters such as Debians’s [upstream_version](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version)
* Introduce a [version epoch](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version)
* A package fix notation similar to [debian_revision](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version)

As long as such a versioning scheme is not implemented, maintainers will be forced to use non-semantic and sometimes confusing and incorrect package versions that do not correspond to upstream versions, together with the current ugly package fix notation. I don’t know how difficult this would be to implement on top of NuGet.

**Comment by ferventcoder** [comment]
Quite difficult. That's why we haven't approached it yet. We'd be
abandoning nuget completely and we are not in a place yet where we could do
that. The goal of 2015 is to introduce new things to the nuspec, reduce our
reliance on nuget, get a server infrastructure in place (for
testing/building/pro features) and get the Pro/business stuff done. In 2016
we can look to see what options we have, and make a decision from a better
place technically. By then nuget may have better support for that stuff.
Who knows? I want to have a better packaging format as well. NVR (name
version release ) at the very least, likely A (architecture) in there as
well.

On Friday, January 2, 2015, TomOne <notifications@github.com> wrote:

> I would argue this is true, but Chocolatey / NuGet has a bit of a stricter
> numbering scheme. As long as packages can work with with that, then all is
> well.
>
> That is what bothers me. Restricting to SemVer might be OK for specific
> package managers such as NuGet or npm, but not for general application
> package managers such as Chocolatey. In fact neither apt-get nor yum have
> such suboptimal versioning restrictions. I opened an issue about this topic
> some time ago: chocolatey/chocolatey#330
> <https://github.com/chocolatey/chocolatey/issues/330>. Basically
> Chocolatey needs this for a proper versioning scheme:
>
>    - Don’t restrict to SemVer
>    - Allow alphanumeric characters such as Debians’s upstream_version
>    <https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version>
>    - Introduce a version epoch
>    <https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version>
>    - A package fix notation similar to debian_revision
>    <https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version>
>
> As long as such a versioning scheme is not implemented, maintainers will
> be forced to use non-semantic and sometimes confusing and incorrect package
> versions that do not correspond to upstream versions, together with the
> current ugly package fix notation. I don’t know how difficult this would be
> to implement on top of NuGet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey.org/issues/59#issuecomment-68576098>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Look for this to switch to a default with prereleases soon.

**Comment by ferventcoder** [comment]
#255 will revert this
