### ISSUE TITLE
install.ps1 - Windows 10 Install error - An exception occurred during a WebClient request

### ISSUE THREAD

**Issue by FrankGlez** [chocolatey/chocolatey.org#591]
### What You Are Seeing?
Error in installing choco.
I have tried to google the error and arrived at issue #1462 'Cannot install Chocolatey on a newly formatted Windows 10'
This issue is similar, but not exactly the same since there is no 403 error.

### What is Expected?
Installed Chocolatey on Windows 10.

### How Did You Get This To Happen? (Steps to Reproduce)
Pasted the following into an admin shell in Windows 10:
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

### Output Log

~~~
C:\windows\system32>@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.11.
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:167 char:3
+   $downloader.DownloadFile($url, $file)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Extracting C:\Users\gonzaf03.SJM\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\gonzaf03.SJM\AppData\Local\Temp\chocolatey\chocInstall...

ERROR: The system cannot find the file specified.
C:\Users\gonzaf03.SJM\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip



System ERROR:
The system cannot find the file specified.
Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install again. Error: 7-Zip encountered a fatal error while extracting the files
At line:216 char:9
+     2 { throw "$errorMessage 7-Zip encountered a fatal error while ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to unzip...cting the files:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install again. Error: 7-Zip encountered a fatal error while extracting the files


C:\windows\system32>
~~~

**Comment by FrankGlez** [comment]
That worked great!
I didn't need to enable the Proxy section.
Likely some issue with the Temp folder.

Thanks for taking the time to solve this.

**Comment by gobindags** [comment]
I'm Still getting issue, I have set temp folder as mentioned above, I do not use any proxy server. can you please help me on this.

Below are the output

PS C:\Windows\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).Downloa
dString('https://chocolatey.org/install.ps1'))
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.11.
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
At line:167 char:3
+   $downloader.DownloadFile($url, $file)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Extracting C:\ProgramData\choco-cache\chocolatey\chocInstall\chocolatey.zip to C:\ProgramData\choco-cache\chocolatey\chocInstall...

ERROR: The system cannot find the file specified.
C:\ProgramData\choco-cache\chocolatey\chocInstall\chocolatey.zip



System ERROR:
The system cannot find the file specified.
Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install
again. Error: 7-Zip encountered a fatal error while extracting the files
At line:216 char:9
+     2 { throw "$errorMessage 7-Zip encountered a fatal error while ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to unzip...cting the files:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompres
   sion = 'true' and call install again. Error: 7-Zip encountered a fatal error while extracting the files

**Comment by gobindags** [comment]
> I'm Still getting issue, I have set temp folder as mentioned above, I do not use any proxy server. can you please help me on this.
> 
> Below are the output
> 
> PS C:\Windows\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).Downloa
> dString('https://chocolatey.org/install.ps1'))
> Getting latest version of the Chocolatey package for download.
> Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.11.
> Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
> At line:167 char:3
> 
> * $downloader.DownloadFile($url, $file)
> * ```
>   + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>   + FullyQualifiedErrorId : WebException
>   ```
> 
> Extracting C:\ProgramData\choco-cache\chocolatey\chocInstall\chocolatey.zip to C:\ProgramData\choco-cache\chocolatey\chocInstall...
> 
> ERROR: The system cannot find the file specified.
> C:\ProgramData\choco-cache\chocolatey\chocInstall\chocolatey.zip
> 
> System ERROR:
> The system cannot find the file specified.
> Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompression = 'true' and call install
> again. Error: 7-Zip encountered a fatal error while extracting the files
> At line:216 char:9
> 
> * ```
>   2 { throw "$errorMessage 7-Zip encountered a fatal error while ex ...
>   ```
> * ```
>       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   * CategoryInfo          : OperationStopped: (Unable to unzip...cting the files:String) [], RuntimeException
>   * FullyQualifiedErrorId : Unable to unzip package using 7zip. Perhaps try setting $env:chocolateyUseWindowsCompres
>     sion = 'true' and call install again. Error: 7-Zip encountered a fatal error while extracting the files

Adding to this--- It is unable to detect appropriate download path, manually giving path is working fine,

Just to check download path modified as below..

# Download the Chocolatey package
Write-Output "Getting Chocolatey from $url."
Download-File https://packages.chocolatey.org/chocolatey.0.10.11.nupkg $file

# Determine unzipping method
# 7zip is the most compatible so use it by default

Thanks
Gobinda

**Comment by quickware** [comment]
Hello I had the same issue and realised it is due to throttling. I used the command to download chocolatey on multiple machines which quickly exceeds the limit allowed per IP. Consequently the downloaded filed is null and cannot be unzipped.
