### ISSUE TITLE
Links broken on package details page

### ISSUE THREAD

**Issue by dejoost** [chocolatey/chocolatey.org#599]
### What You Are Seeing?

Page not found when clicking on following links in any package details page:

package broken? => https://chocolatey.org/docs/package-triage-process
package outdated? => ...

### What is Expected?
the page with related info

### How Did You Get This To Happen? (Steps to Reproduce)
Navigate to https://chocolatey.org/packages/chocolatey
Click on the links described above, possibly other links are also broken

**Comment by pauby** [comment]
Those links work fine for me - the [site had issues last night](https://status.chocolatey.org) - was it during that time you tried them?

**Comment by dejoost** [comment]
The links were not working around the time i created the issue, but they
are indeed restored. I suspect a caching issue.

You can close this issue!
Joost
