### ISSUE TITLE
Broken link in Triage Process Docs

### ISSUE THREAD

**Issue by max-stockhausen** [chocolatey/chocolatey.org#601]
### What You Are Seeing?
I see "Sorry, an error occurred while processing your request" after I clicked "Package Maintainer Handover/Switch" on a docs page
### What is Expected?
I expect to see a docs page about the Maintainer Switch
### How Did You Get This To Happen? (Steps to Reproduce)

1. Go to: [https://chocolatey.org/docs/package-triage-process#new-maintainers](https://chocolatey.org/docs/package-triage-process#new-maintainers)
2. Click on Package Maintainer Handover/Switch
3. See the error

**Comment by pauby** [comment]
This was raised [here](https://github.com/chocolatey/choco-wiki/issues/102) - should have also raised it here so thanks for that @max-stockhausen

**Comment by mkevenaar** [comment]
This is fixed [here](https://github.com/chocolatey/choco-wiki/issues/102)

Can't we close this one?
