### ISSUE TITLE
Installer page gives me an error

### ISSUE THREAD

**Issue by djcarter85** [chocolatey/chocolatey.org#606]
### What You Are Seeing?

Install page gives me an error.

![image](https://user-images.githubusercontent.com/36643088/49220863-4539dd00-f3cf-11e8-95df-89a441fe2e8f.png)

### What is Expected?

An installer ...

### How Did You Get This To Happen? (Steps to Reproduce)

Go to https://chocolatey.org/install

**Comment by pauby** [comment]
@djcarter85 Please check https://status.chocolatey.org
