### ISSUE TITLE
Chocolatey install server is down

### ISSUE THREAD

**Issue by sedimentorc** [chocolatey/chocolatey.org#607]
### What You Are Seeing?

Error: Oh no, we broke something!
You might be here because:
There is an error on our server and the server is "given her all she's got, captain." 
The system is down, the system is down, the system is down.
Our name is smalls.

### What is Expected?

Ability to install chocolatey 

### How Did You Get This To Happen? (Steps to Reproduce)

Browsing to https://chocolatey.org/, then clicking 'install chocolatey now'

**Comment by pauby** [comment]
@jurri @sedimentorc Please check the status page at https://status.chocolatey.org
