### ISSUE TITLE
Error 429 Too Many Connections

### ISSUE THREAD

**Issue by bcharboneauiherb** [chocolatey/chocolatey.org#610]
### What You Are Seeing?
Error 429 Too Many Connections when downloading/installing packages
### What is Expected?
Package Downloads/Installs
### How Did You Get This To Happen? (Steps to Reproduce)
"choco.exe install {packagename}" with the following packages:
- notpadplusplus.install
- 7zip.install
- dotnetcore-runtime
- dotnetfx

**Comment by pauby** [comment]
@bcharboneauiherb See the [Google Groups response](https://groups.google.com/forum/#!topic/chocolatey/wTXapq8nCWw). For others finding this in the future, see [how rate limiting is implemented](https://chocolatey.org/docs/community-packages-disclaimer#rate-limiting) and our [excessive use policy](https://github.com/chocolatey/choc/wiki/CommunityPackagesDisclaimer#excessive-use)
