### ISSUE TITLE
How to configure azure storage

### ISSUE THREAD

**Issue by daemenseth** [chocolatey/chocolatey.org#614]
Is there some documentation to configure Azure storage.
When I configure azure storage I get the following error when I click on packages:
Error: Oh no, we broke something!

I configure the ``
<add key="Gallery:PackageStoreType" value="AzureStorageBlob" />
<add key="Gallery:AzureStorageBlobUrl" value="https://chocoblob.blob.core.windows.net/test" />
<add key="Gallery:AzureStorageAccountName" value="bla"/>
<add key="Gallery:AzureStorageAccessKey"
``

**Comment by pauby** [comment]
@daemenseth You need to be more clear - what are you configuring Azure storage for? Is this around using the [Chocolatey.org Package Gallery](https://gitter.im/chocolatey/choco?at=5c07b44ae4787d16e34ae52e)? If so please refer to the links I sent you through as we do not provide support for this.

**Comment by daemenseth** [comment]
Yess I try to save the chocolatey package on azure storage. On my osted chocolatey.org package gallery. I tried the nuget.gallery project here its easy to configure azure storage in de web.conf but the the chocolatey.org package gallery there are options the configure Azurestorage but it is not clear how to configure.

Maybe can anyone help me

**Comment by pauby** [comment]
@daemenseth As I said to you on Gitter the [Chocolatey Package Gallery is not supported](https://gitter.im/chocolatey/choco?at=5c07b44ae4787d16e34ae52e).
