### ISSUE TITLE
Moderation page shows weird chars

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey/chocolatey.org#615]
### What You Are Seeing?
Weird characters in the [moderation](https://chocolatey.org/docs/moderation) page:
![image](https://user-images.githubusercontent.com/834643/49701632-b3ac4580-fbee-11e8-9aca-3d17e7af88d3.png)
 
### What is Expected?
Not seeing those weird characters

### How Did You Get This To Happen? (Steps to Reproduce)
Just browse to the moderation page

**Comment by gep13** [comment]
@mkevenaar I am not seeing what you are seeing, in all the places that I can see the word Pending:

![image](https://user-images.githubusercontent.com/1271146/49721136-716c1e00-fc59-11e8-87ea-cd9476886695.png)

Can you confirm what browser you are using?  Thanks

**Comment by mkevenaar** [comment]
@gep13 I am using chrome Version 71.0.3578.80 (Official Build)

**Comment by designxsteph** [comment]
Seems to happen directly after a double quote. I will have a look!

**Comment by bcurran3** [comment]
FYI: This is happening on various documentation pages.

EXAMPLES: 
https://chocolatey.org/docs/create-packages

![image](https://user-images.githubusercontent.com/14026600/50851026-77285280-1330-11e9-89d5-e110925717d3.png)

![image](https://user-images.githubusercontent.com/14026600/50850928-30d2f380-1330-11e9-8ea8-28e504f0eb46.png)
