### ISSUE TITLE
Package list double results

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey/chocolatey.org#620]
### What You Are Seeing?
The package returns every package twice:
![screenshot](https://user-images.githubusercontent.com/834643/50422698-b9d82e00-084c-11e9-9e08-d2ca30715e58.png)

https://chocolatey.org/packages?q=Jetbrains&moderatorQueue=&prerelease=false&sortOrder=package-title

![webserver](https://user-images.githubusercontent.com/834643/50422706-dbd1b080-084c-11e9-876f-b7980628cbb7.png)

### What is Expected?
Only one result per package

### How Did You Get This To Happen? (Steps to Reproduce)
* Search for JetBrains from the packages page
* Sort by name (A-Z)

**Comment by pauby** [comment]
This is normally down to caching and is temporary.

I'm going to close this ticket just now.
