### ISSUE TITLE
Potential recurrence of #368 -  Package Listing Doubled

### ISSUE THREAD

**Issue by computamike** [chocolatey/chocolatey.org#631]
### What You Are Seeing?
On web3 the packages seem to be duplicated - at least on the first page.
![image](https://user-images.githubusercontent.com/464876/50867748-3c600200-13a4-11e9-8320-598f088c2fea.png)

### What is Expected?
No duplicate packages.

### How Did You Get This To Happen? (Steps to Reproduce)
click on packages - list single instances of packages, without duplicates.

**Comment by gep13** [comment]
Unfortunately, this is a side effect of the caching mechanism that we have in place on chocolatey.org.  It happens intermittently, and normally corrects itself after a short while.
