### ISSUE TITLE
Japanese Characters not displaying correctly

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey.org#642]
On this section of the site:

https://chocolatey.org/docs/resources#translations

Not clear if this is an issue with the conversion from markdown to cshtml, or something else.

Thought I would raise the issue here in the first instance.

**Comment by AdmiringWorm** [comment]
I'm guessing this has something to do with the version (or arguments) used when calling pandoc to create the documentation, probably doesn't support japanese characters, or must be configured to do exactly that.
