### ISSUE TITLE
Can't search eclipse

### ISSUE THREAD

**Issue by clong365** [chocolatey/chocolatey.org#643]
https://chocolatey.org/packages?q=eclipse

![image](https://user-images.githubusercontent.com/150419/51979323-d6106000-24c7-11e9-8b4f-308276388145.png)

**Comment by AdmiringWorm** [comment]
I seem to have the same problem.

/CC @gep13 @pauby

**Comment by pauby** [comment]
I'm looking into this. See https://status.chocolatey.org for updates.

**Comment by pauby** [comment]
@clong365 We've been looking at this and the only search that we've found that doesn't work (and to be fair it would be impossible to try everything!) is this one! It's very strange.

If you use `choco list eclipse` that also works so it's just the website for this one search.

**Comment by pauby** [comment]
The [search](chocolatey.org/packages?q=eclipse) is now working.
