### ISSUE TITLE
"Contact Site Admins" form will not submit

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#645]
### What You Are Seeing?
The "Contact Site Admins" form does not submit after filling out all required fields. The page will refresh, but not submit.

### What is Expected?
The form should submit after filling out all required fields and redirect back to the last viewed package page.

### How Did You Get This To Happen? (Steps to Reproduce)

1. Go to any package
2. Click on "Contact Site Admins" on the left navigation
3. Fill out all fields, and see that the form does not submit or redirect.

**Comment by JourneyOver** [comment]
Glad this was not something on my end, as I was trying to send a "Contact Site Admins" form  a day or two ago about a package, and every time I pushed submit it would always just seem to refresh the page so I was always unsure on if it actually had ever sent or not.

So glad to find out it's just a bug.

**Comment by ferventcoder** [comment]
This has just been merged and will be pushed up in a little while.

**Comment by ferventcoder** [comment]
Building now...
