### ISSUE TITLE
Incorrect date format on website

### ISSUE THREAD

**Issue by torokati44** [chocolatey/chocolatey.org#647]
The "Last update" date of packages is shown in an incorrect format on the website.

Originally reported on the mailing list by Daniel Albrecht on 7/11/17, and "Paul" suggested that I open an issue here on 19,8,2.

See the thread, including a link to the correct date format (ISO-8601) here:
https://groups.google.com/d/msg/chocolatey/Nx6PDDhBJqA/bA29mxHYAAAJ

**Comment by ferventcoder** [comment]
I might see this in a friendlier format, like 13 FEB 2019. That way it's easy to digest for folks everywhere.

**Comment by designxsteph** [comment]
Working this out. Here's a preview:
<img width="188" alt="Screen Shot 2019-11-19 at 3 06 31 PM" src="https://user-images.githubusercontent.com/42750725/69186565-51d2ac00-0ade-11ea-8402-139cbca0eeed.png">

**Comment by torokati44** [comment]
Still not conforming to the single, decades-old, universally accepted and understood, international standard, but at least it's less ambiguous.
Thanks.

**Comment by ferventcoder** [comment]
@torokati44 please don't close the issue - we'll do that when the code is complete.

**Comment by ferventcoder** [comment]
Merged into master at https://github.com/chocolatey/chocolatey.org/commit/37e78aa4272873ab42563812fc29eafad7fa257b and deployed just now.
