### ISSUE TITLE
[moderator] add option to start package-validator again

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey/chocolatey.org#648]
As a moderator I would like to be able to start the package-validator again after it has failed for some reason. Currently there is no option to do so.

I would suggest a checkbox like the one to restart the package-verifier to run the package-validator again.

/cc: @ferventcoder @gep13 @pauby

**Comment by mkevenaar** [comment]
I am willing to try and implement this.

**Comment by pauby** [comment]
Is this use case for this when there has been an issue with the validator
you'd want to restart it?

**Comment by mkevenaar** [comment]
@pauby yes.

**Comment by mkevenaar** [comment]
PR created #649
