### ISSUE TITLE
Choco push timeouts

### ISSUE THREAD

**Issue by Thilas** [chocolatey/chocolatey.org#651]
### What You Are Seeing?
From time to time, choco push timeouts with the following error even though the push succeeded:
```
Failed to process request. 'Origin Time-out'.  The remote server returned an error: (524) Origin Time-out..
```

@AGSPhoenix mentioned a similar error on #1285.

### What is Expected?
Not to have the timeout error.

### How Did You Get This To Happen? (Steps to Reproduce)
I'm using AU and the issue happens randomly.

### Output Log
AU log: https://ci.appveyor.com/project/Thilas/chocolatey-packages/build/3232

In this case, the package to push was really small.

**Comment by ferventcoder** [comment]
Moved to https://github.com/chocolatey/chocolatey.org/issues/651. Not sure why there is a bad exit code returned even when it completes successfully. It is annoying, but it is definitely at the chocolatey.org end.

**Comment by AdmiringWorm** [comment]
The last time this popped up, didn't that turn out to be due to cloudflare?
If I remember correctly, that was why the push endpoint was created.

**Comment by TheCakeIsNaOH** [comment]
I am also consistently running into this.
https://ci.appveyor.com/project/TheCakeIsNaOH/chocolatey-packages/builds/30732478

**Comment by pauby** [comment]
Is this still an issue? I haven't seen any mention of the 524 timeouts in quite a while now (since @ferventcoder did some work around this)?

**Comment by ferventcoder** [comment]
I'll go ahead and close this out for now as it was hopefully fixed by other work in this area. If it needs to be reopened, someone drop a comment.
