### ISSUE TITLE
chocolatey.org Is unable to cache icons from websites requiring TLS 1.2

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey.org#652]
### What You Are Seeing?
When a maintainer is using an icon from a website that requires TLS 1.2 to be used, chocolatey.org is unable to cache that icon on the server.
Which results in a broken icon on the package.

### What is Expected?
Expects chocolatey.org to be able to cache and show the icon even if the website the icon comes from requires TLS 1.2.

### How Did You Get This To Happen? (Steps to Reproduce)
Upload a new package version with a iconUrl from a TLS 1.2 only webpage (only one I know of right now is github raw links, but could be others).

### Possible Solutions
1. Update the caching code to set the service point to allow TLS 1.2 (this will require .NET 4.5 or higher to be installed on the machine compiling the website, and on the server itself).
2. If the image isn't cached locally, use the specified icon url as it is specified in the nuspec file.
3. Implement a custom downloader that allows for TLS 1.2

**Comment by AdmiringWorm** [comment]
reference https://gitter.im/chocolatey/choco?at=5c87acb025e4e24c0758ab9e

**Comment by ferventcoder** [comment]
Oh I see what you meant now. Terminology. Chocolatey.org != "chocolatey". When I see the term "chocolatey", I think of choco.exe.

**Comment by ferventcoder** [comment]
This would be nice to get to. I've started a .NET 4.5+ branch locally and there were a LOT of things that needed to be resolved (on the order of about 600), so of course that hasn't been pushed anywhere yet.

**Comment by AdmiringWorm** [comment]
While it would be nice to have the whole codebase converted to use .NET 4.5+, it isn't strictly necessary to do that just to implement this.

If changing the calls to the WebClient to ensure that TLS 1.2 is used (by setting the numerical enum values as is done in choco), then the only requirement should be that the machine building the code and the webserver have .NET 4.5+ installed.

**Comment by bcurran3** [comment]
(convo moved from #669)

Having this issue with icons sourced from Staticaly CDN.
-------------
REF: https://groups.google.com/forum/#!topic/chocolatey/x_o2zz5lvlY

chocolatey.org's caching of package icons sourced from staticaly CDN doesn't appear to be working.

example:
` <iconUrl>https://cdn.staticaly.com/gh/bcurran3/ChocolateyPackages/master/go-contact-sync-mod/go-contact-sync-mod_icon.png</iconUrl>`

Clicking https://cdn.staticaly.com/gh/bcurran3/ChocolateyPackages/master/go-contact-sync-mod/go-contact-sync-mod_icon.png will show the image exists and displays fine.

Clicking https://chocolatey.org/packages/go-contact-sync-mod which uses the above referenced iconUrl info, displays the default blank chocolatey.org package icon.

**Comment by bcurran3** [comment]
Possibly recently worked on?

I get icon for this that I pushed today:
https://chocolatey.org/packages/dell-update/3.0.1

**Comment by joel0** [comment]
Until this is fixed, I would suggest updating the [wiki icon guidelines](https://github.com/chocolatey/choco/wiki/CreatePackages#package-icon-guidelines) to warn that Statically isn't working right now.

I ran into this problem and was confused because it silently fails, so I didn't know if it was a cache problem.

**Comment by joel0** [comment]
I don't know what changed, but my [package](https://chocolatey.org/packages/workman/) now has an icon from what I believe is a TLS 1.2 server.  Perhaps removing TLS 1.0 & 1.1 from the chocolatey.org server end of things also upgraded the icon downloading TLS: https://chocolatey.org/blog/remove-support-for-old-tls-versions

**Comment by ferventcoder** [comment]
This is completed and will be pushed soon.
