### ISSUE TITLE
Install.ps1 wrongly warns that tls1.2/tls1.1 are missing for PowerShell Core 6.1.x

### ISSUE THREAD

**Issue by kasiagauza** [chocolatey/chocolatey.org#655]
### What You Are Seeing?
A warning is triggered: _Unable to set PowerShell to use TLS 1.2 and TLS 1.1 due to old .NET Framework installed (...)_ when running **Install.ps1** in **Powershell Core 6.1.x** - even if the protocols are present and a correct .Net Framework is installed.

It's because the "try {}" block is set on the following line:

https://github.com/chocolatey/chocolatey.org/blob/c7f7ed73931471dc12856a340c86e458e047b059/chocolatey/Website/Install.ps1#L93

The whole set of protocols are tested at once. If any of the protocols is missing, such as **SSL**, then a warning is triggered. But SSL support is absent from PS 6.1.x.

### What is Expected?

The script should pass to _SecurityProtocol_ only a list of available protocols and warn about missing Tsl 1.x only if they are truly absent.

### How Did You Get This To Happen? (Steps to Reproduce)

The fastest and cleanest way to see the warning:
- docker run -it --rm mcr.microsoft.com/powershell:nanoserver-1809
- _Run in command line:_ [System.Net.ServicePointManager]::SecurityProtocol = 3072 -bor 768 -bor 192 **-bor 48**
- _Then this:_ [System.Net.ServicePointManager]::SecurityProtocol = 3072 -bor 768 -bor 192

The second one succeeds, the first one fails, beccause SSL protocol is not present. The whole is being tested on a fresh PS 6.1.3 instance.

**Comment by kasiagauza** [comment]
@ferventcoder Here's the issue I should wrote before adding a pull request #654

**Comment by ferventcoder** [comment]
Superseded by #778

**Comment by 26384sunilrana** [comment]
> @ferventcoder Here's the issue I should wrote before adding a pull request #654

It did helped me I updated the Script. as shown in this comment :-) thanks :-)
