### ISSUE TITLE
The chocolately packages page has a pop up that is impossible to exit out of

### ISSUE THREAD

**Issue by joshy91** [chocolatey/chocolatey.org#658]

**Comment by gep13** [comment]
@joshy91 in order to best help you, can you please provide some more information, as per the template of the issue that you created?

Ideally with some screenshots, and if you can mention the screen resolution for the machine you are using, that will help as well.

**Comment by bcurran3** [comment]
@designxsteph it looks like you got rid of that big annoying cookie announcement screen and put in a nice small one. Thank you! "Chocolatey.org uses cookies to enhance the user experience of the site." is so much easier to read and acknowledge.  I see Chat added as well....

**Comment by designxsteph** [comment]
This has been released here https://github.com/chocolatey/chocolatey.org/commit/345bb4e1425eccb94c7f82d652476cd466398b54
