### ISSUE TITLE
Amazon Deprecating Path-Style URL's Moving To Use Virtual-Hosted URL's

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey.org#661]
[Amazon are deprecating path-style S3 URL's](https://devclass.com/2019/05/13/amazon-s3-user-you-may-need-to-change-the-way-you-fill-your-bucket/) (https://s3.amazonaws.com/bucketname/folder/file.ext) from September 2020 and moving to the virtual-hosted style of URL's (https://bucketname.s3.amazonaws.com/folder/file.ext) instead.

There has been a [follow-up](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) to say that they will only be deprecating path-style URL's for buckets created **after* 30 September 2020:

```
Out with the Old
In response to feedback on the original deprecation plan that we announced last week, we are making an important change. Here’s the executive summary:

Original Plan – Support for the path-style model ends on September 30, 2020.

Revised Plan – Support for the path-style model continues for buckets created on or before September 30, 2020. Buckets created after that date must be referenced using the virtual-hosted model.
```

However this will potentially lead to two different ways of referencing S3 in the same codebase and across all of the Chocolatey codebase. As this is a small change I believe it should be made now in case the stay of execution for path-style URL's is reversed.

**Comment by ferventcoder** [comment]
Mentioned on the PR - AWS decided to allow the old bucket url, which works for what we have so we'll probably keep it in place for now. If we need to revisit this in the future, we have the changes that will need to be made.
