### ISSUE TITLE
Using large icon file (from URL) hangs choco push

### ISSUE THREAD

**Issue by n3rd4i** [chocolatey/chocolatey.org#663]
While using large Icon file `iconUrl` (e.g. [image file](http://www.ti.com/content/dam/ticom/images/identities/online-design-tools/uniflash-bolt-icon.png)) make `choco push` command hang and timeout with the following error:
```log
Failed to process request. 'Origin Time-out'. 
The remote server returned an error: (524) Origin Time-out..
```

**Comment by bcurran3** [comment]
I'm guessing this is really related to:
https://github.com/chocolatey/chocolatey.org/issues/613

**Comment by n3rd4i** [comment]
stalled, closing
