### ISSUE TITLE
Broken Link in the "Getting Started" page

### ISSUE THREAD

**Issue by Omzig** [chocolatey/chocolatey.org#665]
### What You Are Seeing?
Located in this Link: https://chocolatey.org/docs/getting-started#overriding-default-install-directory-or-other-advanced-install-concepts

There is a reference located here:
Portable Package - packages that use zip or just contain the runtime software. Usually these packages do not require administrative privileges to install or run. See https://github.com/chocolatey/choco/wiki/ChocolateyFAQs#portable-application-something-that-doesnt-require-a-system-install-to-use">

### What is Expected?
I expected the link to work: https://github.com/chocolatey/choco/wiki/ChocolateyFAQs#portable-application-something-that-doesnt-require-a-system-install-to-use

### How Did You Get This To Happen? (Steps to Reproduce)
By clicking on the link.

### Workaround
copy the link and paste it in a new page.

**Comment by AdmiringWorm** [comment]
I'm afraid that this is the wrong repository for issues regarding the wiki page on chocolatey.org.

The correct repo would be: https://github.com/chocolatey/choco-wiki/issues

**Comment by Omzig** [comment]
Created: https://github.com/chocolatey/choco-wiki/issues/128
