### ISSUE TITLE
Problem acquiring icons from Staticaly CDN for chocolatey.org's package icon caching.

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey.org#669]
REF: https://groups.google.com/forum/#!topic/chocolatey/x_o2zz5lvlY

chocolatey.org's caching of package icons sourced from staticaly CDN doesn't appear to be working.

example:
` <iconUrl>https://cdn.staticaly.com/gh/bcurran3/ChocolateyPackages/master/go-contact-sync-mod/go-contact-sync-mod_icon.png</iconUrl>`

Clicking https://cdn.staticaly.com/gh/bcurran3/ChocolateyPackages/master/go-contact-sync-mod/go-contact-sync-mod_icon.png will show the image exists and displays fine.

Clicking https://chocolatey.org/packages/go-contact-sync-mod which uses the above referenced iconUrl info, displays the default blank chocolatey.org package icon.

@gep13's theory is that it might be a TLS issue when chocolatey.org tries to grab the icon.

**Comment by djdv** [comment]
I'm encountering this as well.
Package: https://chocolatey.org/packages/ipfs
`<iconUrl>https://ipfs.io/ipfs/QmXbCUGR4kWndmZyEV7AYZRh1AwsUfyAMbKJegHumyab5S/ipfs-logo-vector-ice-text.svg</iconurl>`

Previously, the SVG was used as expected.
But now the package gets the `packageDefaultIcon.png` icon.

**Comment by bcurran3** [comment]
@designxsteph - any recent (month or so?) changes that might be causing this?

**Comment by AdmiringWorm** [comment]
> theory is that it might be a TLS issue when chocolatey.org tries to grab the icon.

I can confirm that this is the case, the ssl certificate used on the statically server is TLS 1.2 only.

I am running an analysis on the ipfs.io domain now, but I suspect the reason is the same. Most likely their ssl certificate was recently renewed (only guessing right now), which would explain why you didn't see it before.

**Comment by AdmiringWorm** [comment]
@bcurran3 as the issue regarding statically is related to the TLS version, and there is already an issue for this. I believe it would be best to move the discussion for this over to the existing issue: #652

**Comment by bcurran3** [comment]
Thanks for the research.

Will move discussion and close.
