### ISSUE TITLE
Remove Codeplex link from User Profile

### ISSUE THREAD

**Issue by gep13** [chocolatey/chocolatey.org#671]
Codeplex has been retired:

https://archive.codeplex.com/

And as a result, I do not believe that anyone will be using it anymore.

Existing profile links, for example:

https://www.codeplex.com/site/users/view/gep13

Redirect to the archive link above, and serve no real purpose anymore.

**Comment by mkevenaar** [comment]
@gep13 @designxsteph I think we need to remove all the CodePlex links. When people use Chrome (and perhaps other browsers, I haven't tested this) they get the following message:

![image](https://user-images.githubusercontent.com/834643/75016826-202a0200-548c-11ea-9bde-1be9259aceb4.png)

You can reproduce this by visiting the profile link that @gep13 mentioned above on Chrome (and perhaps others).
