### ISSUE TITLE
Resize image in description to fit the page

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/chocolatey.org#676]
Currently some packages also include screenshots, such as [the VLC media player](https://chocolatey.org/packages/vlc). I think this is good, but if the screenshot is too large, it extends outside the right end. This can be easily seen by replacing the VLC screenshot with this image:

![ClassyShark Screenshot](https://cdn.jsdelivr.net/gh/borisf/classyshark-user-guide@7bb528db3ad5e35fc09734c6a7a7d1402d8cdc10/images/5%20ClassesDexData.png)

We can avoid the issue by adding some style:

```css
.package-page img {
    max-width: 100%;
}
```

**Comment by gep13** [comment]
@designxsteph do you happen to know if this is something that was changed in the upcoming website refresh?

**Comment by designxsteph** [comment]
@gep13 Yes, I have fixed this with the redesign.

**Comment by gep13** [comment]
@designxsteph perfect, thanks!

@FranklinYu I am going to go ahead and close this issue.  Once the new site is launched, if you continue to see problems in this area, I would ask that you comment again on this issue, and we can investigate.

**Comment by FranklinYu** [comment]
@gep13 Is it #653?

**Comment by gep13** [comment]
@FranklinYu yes
