### ISSUE TITLE
package PSScriptAnalyzer appears broken on the website

### ISSUE THREAD

**Issue by jayvdb** [chocolatey/chocolatey.org#677]
https://chocolatey.org/packages/PSScriptAnalyzer fails to load, however it is OK to fetch and use, and other packages on the website are ok.

**Comment by gep13** [comment]
@jayvdb thank you for reporting this.  I have just tested this, and I can confirm that this is indeed a problem.

@pauby do you happen to have also noticed this?

**Comment by pauby** [comment]
This seems to still be broken. Purged Cloudflare cache and no change. We had an issue with the `eclipse` package previously (@gep13?) and the web fairies fixed it as it started working again.

I'm not sure what could be causing this.

**Comment by pauby** [comment]
The issue appears to be the large JSON files that are in the package - removing those large text files resolves the issue.

I'll redo the package as soon as I can and get them submitted for the next version.

**Comment by mkevenaar** [comment]
@pauby it's still open: #643 but for me, that works now.

**Comment by pauby** [comment]
I've reworked the package to ZIP the module before embedding it. This should fix the issue when the next version of PSScriptAnalyzer is released.

Closing this just now but happy to reopen if need be.
