### ISSUE TITLE
Non-elevated prompt not displaying selection options

### ISSUE THREAD

**Issue by RussKie** [chocolatey/chocolatey.org#679]
### What You Are Seeing?

![choco-issue](https://user-images.githubusercontent.com/4403806/59891640-3b360500-9419-11e9-8895-3f6c0414c009.gif)

### What is Expected?

The selection must be visible before the time-out

### How Did You Get This To Happen? (Steps to Reproduce)

Run an install in a non-elevated prompt.

### Env:

Chocolatey v0.10.13

**Comment by gep13** [comment]
@RussKie does this happen like this in something other than ISE?

**Comment by RussKie** [comment]
Good catch 👍 

It looks like ISE-specific issue

* cmd: 
![image](https://user-images.githubusercontent.com/4403806/59964808-f1e4d300-9548-11e9-9acb-ce8485c296e8.png)
* Console2 cmd: 
![image](https://user-images.githubusercontent.com/4403806/59964795-d5489b00-9548-11e9-862c-472c88db2e44.png)
* Console2 PSx64
![image](https://user-images.githubusercontent.com/4403806/59964818-23f63500-9549-11e9-99b9-39a2d70324d5.png)
* ISE
![image](https://user-images.githubusercontent.com/4403806/59964823-51db7980-9549-11e9-87b0-912be4a077aa.png)

**Comment by gep13** [comment]
The reason that I asked the question is that we have seen issues when running Chocolatey in ISE. It doesn’t seem to like the fact that Chocolatey spawns it’s own PowerShell host. The guidance is to not use Chocolatey within ISE.

**Comment by RussKie** [comment]
Fair enough.
May be make this a warning if the Choco run under ISE...

**Comment by gep13** [comment]
@RussKie off the top of my head, I am not sure if there is a way to detect if the current execution is happening out of ISE or not.  If there is, that would be an issue that would need to be raised over on the `chocolatey/choco` repository.  Would you mind creating a new issue there?  And I will go ahead and close this one, as I don't think that it is required, as we have narrowed down the issue to specifically regarding ISE.
