### ISSUE TITLE
Support .msixbundle as a exe type (checksums)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#682]
https://chocolatey.org/packages/microsoft-windows-terminal

**Comment by gep13** [comment]
I actually have a list of other file types that also need to have this change made.  I will try to dig them out and add them as a list here.

**Comment by mkevenaar** [comment]
.msix, .appx and .appxbundle should also be added, I think

**Comment by AdmiringWorm** [comment]
Shouldn't all files that aren't handled as a read-able text file include the checksum?

**Comment by gep13** [comment]
>@AdmiringWorm said...
Shouldn't all files that aren't handled as a read-able text file include the checksum?

As in have a "whitelist" for text files, rather than a list of files that are checksummed?

**Comment by AdmiringWorm** [comment]
@gep13 yes, exactly.

I would think it is better to have a checksum for a file, than not having anything at all.

**Comment by gep13** [comment]
Interesting.  I would have to look at the code to see if this would be possible, and to check that there wasn't a technical reason why it is done this way.  It would seem that there would be fewer file types that we would want to display, compared to those that we wanted to provide a checksum for.

**Comment by ferventcoder** [comment]
We currently have a whitelist for both

**Comment by designxsteph** [comment]
@AdmiringWorm @gep13 @mkevenaar @ferventcoder I have added the file extensions "msix, msixbundle, appx, and appxbundle" to show a checksum. Are there any others we need to add at this point?

Also, while testing locally, I noticed that it will only start showing these files with the checksums on newly uploaded packages. It does not change existing packages that contain these file extensions.

Here's a preview of the Microsoft Windows Terminal package after making these changes and uploading a new version:
![checksum](https://user-images.githubusercontent.com/42750725/69146050-9e919500-0a94-11ea-9d79-9c00ec24605a.png)

**Comment by gep13** [comment]
@designxsteph I have a note of at least one other file extension that I think need to get added as well.

It was `tar.xz` (but it could be that there are other compression types that should be supported.  That is a question I would aim at @ferventcoder and @AdmiringWorm

**Comment by gep13** [comment]
@designxsteph I also have a very vague recollection of a file extension for a Python related package that I thought I noted down as well, but I can't seem to find that note currently.  If I find it, I will report back.

**Comment by AdmiringWorm** [comment]
Some common archive file extension I know (mostly under linux, not sure about windows) of is:

- `tar` (Uncrompressed archive)
- `tar.gz` (I see `gz` is there, so probably not needing this)
- `tar.xz`
- `tar.bz2` (Compressed archive using bzip2)

Other file extensions I know of that should be treated as binary would be:

- `zst` (Compressed file using facebooks zstd library, not sure if it is an official extension though).
- `pyc` (Python compiled bytecode)
- `pyo` (Python compiled bytecode with optimisations only)
- `pyd` (Python compiled windows dll file)
- `bin` (Typically a binary serialised configuration file, but also used in other circumstances)

File extension I am a little unsure if they should be treated as a binary:
- `pdf` (It is not a text file, but not really a binary file either)


There are many more extensions that should be treated as a binary file, but those are the ones I can think of right now.

**Comment by designxsteph** [comment]
@AdmiringWorm thanks, I added in those extensions as well. I did not add in `pdf` as of now.

**Comment by gep13** [comment]
@AdmiringWorm I "think" it might have been the `pyc` extension that I was thinking of.
