### ISSUE TITLE
Clickjacking on website

### ISSUE THREAD

**Issue by HridayBhatia** [chocolatey/chocolatey.org#684]
Bug report for clickjacking

**Comment by ferventcoder** [comment]
@HridayBhatia this isn't the proper method to disclose security issues. I'm guessing you also sent an email recently after learning the proper method.

**Comment by HridayBhatia** [comment]
I apologize because I didn't knew the proper channel and first point of contact so opened an issue at GitHub. From future I will refrain. Kindly consider this bug and timeline for remediation.
Also I do not remember sending you an email, as of I cannot find them on my sent box. I humbly request you to share that email or reply on it so I can manage to confirm that it shouldn't belong to someone else.

**Comment by AdmiringWorm** [comment]
@HridayBhatia the email to send security related issues is mentioned here: https://chocolatey.org/security#report-issue

and it is: `security [at] chocolatey dot io`

**Comment by ferventcoder** [comment]
This has been released and is live.

**Comment by ferventcoder** [comment]
Special thanks to @HridayBhatia  and FKL (name redacted awaiting permission) for pointing this out!
