### ISSUE TITLE
Licensing for open-source edition not clear

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/chocolatey.org#685]
Chocolatey releases bundle two binaries that are not under the Apache 2.0 license. Namely, shimgen.exe which is under a EULA, and 7zip.dll which is under the LGPL + unRAR restriction. However, there are a couple of places(listed below) on Chocolatey.org that state that the open-source edition is under Apache 2.0, which is only partially correct due to the bundled binaries.

https://chocolatey.org/pricing#compare - `Licensing & Terms` section and `Is the open source license business friendly?` section
https://chocolatey.org/faq - `I would like to use Chocolatey in my organization, is the licensing friendly?` section
https://chocolatey.org/docs/legal - under `Open-source edition`
https://chocolatey.org/docs/getting-started - under `Open Source Licensing Is Ready for Business`

I would suggest that these pages be changed to clarify the licensing for the open-source edition, ie that it is not only under Apache 2.0, but also parts are under the two other licenses.

**Comment by darealshinji** [comment]
I guess you could write something similar to shimgen and release it under Apache license if you need to. As for 7zip, there are probably builds available without the unrar licensing (and therefor without unrar support I guess).

**Comment by ferventcoder** [comment]
> Chocolatey releases bundle two binaries that are not under the Apache 2.0 license. Namely, shimgen.exe which is under a EULA, and 7zip.dll which is under the LGPL + unRAR restriction. However, there are a couple of places(listed below) on Chocolatey.org that state that the open-source edition is under Apache 2.0, which is only partially correct due to the bundled binaries.

You can release something under Apache v2 that uses libraries that are MIT, LGPL, etc. It doesn't change the licensing of the product you are releasing.

**Comment by ferventcoder** [comment]
You should include 3rd party licenses and we do. https://github.com/chocolatey/choco/blob/master/docs/legal/CREDITS.md#third-party-licenses---runtime

**Comment by TheCakeIsNaOH** [comment]
> You can release something under Apache v2 that uses libraries that are MIT, LGPL, etc. It doesn't change the licensing of the product you are releasing.

I am not disputing that that chocolatey itself is under Apache, namely `choco.exe`, the helper PowerShell functions, and other associated bits. I apologize, my wording in the OP could have been much more clear. 

What I am saying is that the chocolatey nupgk includes binaries that are not under Apache. Because of that, I am suggesting that the pages linked above include information or a link to information about bundled binaries. The [credits](https://github.com/chocolatey/choco/blob/master/docs/legal/CREDITS.md#third-party-licenses---runtime) page linked above would work great IMO.

However, it appears that you consider this not important enough to clutter website pages with, which I can respect if be disappointed with. Thank you for time.
