### ISSUE TITLE
Cannot install chocolately client. Unable to connect to server.

### ISSUE THREAD

**Issue by Dragonsong3k** [chocolatey/chocolatey.org#702]
### What You Are Seeing? 
When running this .. 
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

or this... 

Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex

Getting this..

Unable to connect to the remote server
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by ferventcoder** [comment]
@Dragonsong3k This sounds like a proxy issue on your end. You will want to see the advanced section on installation and look at how to configure for proxy. HTH

**Comment by ferventcoder** [comment]
https://chocolatey.org/docs/installation#more-install-options

**Comment by ferventcoder** [comment]
This one should also be helpful - https://chocolatey.org/docs/installation#installing-behind-a-proxy

**Comment by Dragonsong3k** [comment]
I have no proxies on my end. Turned out to be a bad NIC config on a few systems that I tested. 

Thanks for the response!
