### ISSUE TITLE
Some of the course pages are missing the right-side navigation

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey/chocolatey.org#704]
Some of the course pages are missing the right-side navigation. It's possible they're missing the right-side nav because they are missing consistent section headers or something? For example (and the complete list, as I encounter them, follows):

![image](https://user-images.githubusercontent.com/217842/65700479-c7c21600-e04d-11e9-88c5-ddf140c31c11.png)

 * [Terminology](https://chocolatey.org/courses/getting-started/terminology)
 * [Chocolatey Packages](https://chocolatey.org/courses/getting-started/chocolatey-packages)
 * [Internationalization and Localization of Packages](https://chocolatey.org/courses/creating-chocolatey-packages/internationalization-and-localization)
 * [Package Maintainer Handover](https://chocolatey.org/courses/creating-chocolatey-packages/package-maintainer-handover)

And some course pages have right-side nav, but are missing the Quiz nav.

![image](https://user-images.githubusercontent.com/217842/65700950-82eaaf00-e04e-11e9-9cc4-888b24720c83.png)

 * [All About Shims](https://chocolatey.org/courses/creating-chocolatey-packages/shims)

**Comment by AnthonyMastrean** [comment]
This page has right-side nav, but is missing the Quiz nav.

https://chocolatey.org/courses/creating-chocolatey-packages/shims

![image](https://user-images.githubusercontent.com/217842/65700950-82eaaf00-e04e-11e9-9cc4-888b24720c83.png)

**Comment by ferventcoder** [comment]
Probably missing a TOC on some of those.
