### ISSUE TITLE
[Enhancement] Tag Search

### ISSUE THREAD

**Issue by Jaykul** [chocolatey/chocolatey.org#73]
The website should support search by tag (something like what the NuGet website does now). Most importantly, clicking on a tag in a module list or module details page should return **only** modules *with that exact tag* (not modules with that word in their description).  

Currently tagging things is no better than just putting the words in the description on the Web UI even through the back-end OData feed supports it.

Examples, on Nuget site

http://www.nuget.org/packages?q=Tags:Microsoft
http://www.nuget.org/packages?q=Tags:Microsoft+Tags:Mvc

Obviously Chocolatey doesn't have to implement it that way, it could be done as path, like /tags/Microsoft and /tags/Microsoft/Mvc or even /tags/Microsoft+Mvc ... nobody cares about the details as long as it works. ;)

**Comment by ferventcoder** [comment]
This will be done by tag:value and or author:value.
