### ISSUE TITLE
Moderator queue search results incorrect

### ISSUE THREAD

**Issue by bc3tech** [chocolatey/chocolatey.org#731]
### What You Are Seeing?
![image](https://user-images.githubusercontent.com/1967433/68629030-3391fe00-0497-11ea-9a0e-4e91f077cc1c.png)

### What is Expected?
"Returned X packages" should match the verbiage under "Display results N - M of X" and 'Next' link at bottom should be enabled/disabled (shown/hidden) accordingly.

### How Did You Get This To Happen? (Steps to Reproduce)
Filter the moderator queue w/ a package name as the `q` parameter in the url. e.g. https://chocolatey.org/packages?q=vivaldi&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count

**Comment by ferventcoder** [comment]
Yep, that definitely looks incorrect.

**Comment by designxsteph** [comment]
Looking into this- When I click that link above a get totally different results
<img width="1232" alt="Screen Shot 2019-11-21 at 5 51 03 AM" src="https://user-images.githubusercontent.com/42750725/69335877-3b823880-0c23-11ea-8531-b4898ae0cf64.png">

When I search for that not in the moderator queue I get 4 results.

I am adding in the verbiage to add the total count to "Display results N - M of X" where "X" is the total count. The search results that I'm getting and what you're getting might another issue in itself that I will try to reproduce with perhaps another search term.

@bc3tech @ferventcoder curious- if you are to click the link above again, do you get the same results as in the original picture?

**Comment by designxsteph** [comment]
I figured out that it is showing 760 in your picture because it found 9 results, but then there is also 751 unknown packages. (9 +751). I'm still not sure how it found the 9 results though.

@ferventcoder Is the adding of the unknown packages into search results total count, and then not showing the unknown packages, wanted behavior? What should be the behavior? I remember this happening before the redesign now, as I was confused about the unknown packages.

**Comment by bc3tech** [comment]
> I figured out that it is showing 760 in your picture because it found 9 results, but then there is also 751 unknown packages. (9 +751). I'm still not sure how it found the 9 results though.
> 
> @ferventcoder Is the adding of the unknown packages into search results total count, and then not showing the unknown packages, wanted behavior? What should be the behavior? I remember this happening before the redesign now, as I was confused about the unknown packages.

yes you will of course get different results today; all the packages have been moderated.

**Comment by bc3tech** [comment]
Still happening:

![image](https://user-images.githubusercontent.com/1967433/72011272-511ce300-320e-11ea-84a1-a56c51863f8a.png)

**Comment by gep13** [comment]
943 - 747 = 196

The 747 packages are a count of packages that are unreviewed.  They are not in active moderation, and they won't be until a new package version is submitted for that package.  So the 196 is a true reflection of the packages that are actively being moderated.

Does that make sense?

How would you suggest that we make this clearer?

**Comment by bc3tech** [comment]
If I'm filtering the list, the counts should reflect the filtered set, not the whole set. See what GitHub does when you filter PRs, Issues, etc. You don't get a filtered list then the ability to page through _every_ Issue.

**Comment by designxsteph** [comment]
@gep13 I have made the changes we have spoken about regarding the package moderation count number when viewing all statuses in the moderation queue. https://github.com/chocolatey/chocolatey.org/pull/821
