### ISSUE TITLE
Not all files are appearing in files list

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#736]
### What You Are Seeing?
Empty package files are not appearing within the files list.

### What is Expected?
All files should be shown on a package if even that file is empty.

### How Did You Get This To Happen? (Steps to Reproduce)
Visit https://chocolatey.org/packages/microsoft-windows-terminal#files. Notice that the `.msixbundle` file is missing.

**Comment by AdmiringWorm** [comment]
I wouldn't expect the `.msibundle` file extension to be completely empty, it should probably show a checksum. That is what I think anyhow.

Which files is getting a checksum seems to be handled by the configuration value `Gallery:PackageFileChecksumExtensions` in the `Web.config` file located here: https://github.com/chocolatey/chocolatey.org/blob/master/chocolatey/Website/Web.config#L61

**Comment by mkevenaar** [comment]
@AdmiringWorm While I agree that these files should be handled as binary, the website should still show the full contents of a package, even if there are no checksums available for that file.

**Comment by AdmiringWorm** [comment]
@mkevenaar yes of course, I did not mean to imply that the website shouldn't show them.

**Comment by gep13** [comment]
@AdmiringWorm @mkevenaar there is actually a separate issue for doing just that...

https://github.com/chocolatey/chocolatey.org/issues/682

**Comment by AdmiringWorm** [comment]
Ah, I had forgotten about that one.

Thanks @gep13

**Comment by gep13** [comment]
@AdmiringWorm I actually mentioned that issue to @designxsteph yesterday, as it would be good to ship it at the same time as we re-instate showing of the msixbundle files.

**Comment by designxsteph** [comment]
Hey @AdmiringWorm thanks for the heads up on where that is located. I started a conversation about this over at #682 

@gep13 @mkevenaar

**Comment by ferventcoder** [comment]
This has just been released - might take a little while for the caches to clear up, but everything should appear again.
