### ISSUE TITLE
Markdown editor does not work on Android phones

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#738]
When commenting on a package while on a mobile Android device, the editor does not work correctly. When double tapping on keyboard suggestions, it will insert the word in reverse. It will also will copy previously selected words into the text field. It is then hard to edit the text in the editor and tends to push all the edits towards the end. In all it is "buggy" on Android devices and doesn't work as flawlessly as it does on desktop.

**Comment by ferventcoder** [comment]
This has been deployed - caching and all of that noted.
