### ISSUE TITLE
Avatars next to package statuses in moderator queue broken

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#740]
### What You Are Seeing?
Sometimes the avatars next to a package with a "waiting" status show up without a profile attached to them, which then links off to a 404 page. This happens when the last username to respond was "chocolatey-ops" or if the user does not provide an email.

For the "updated" and "responded" package status, the avatar does not always reflect the last person to comment/review on a package and sometimes also will lead to a 404. 

![image (8)](https://user-images.githubusercontent.com/42750725/69630072-44ec1600-1012-11ea-889e-e75096b900ad.png)

### What is Expected?
I would expect that when I click on the avatar, it will link me off to the last person who responded with a comment/review.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Go to the moderation queue
3. Click on avatars next to package statuses until it takes you to a 404.

**Comment by ferventcoder** [comment]
Merged into master at https://github.com/chocolatey/chocolatey.org/commit/37e78aa4272873ab42563812fc29eafad7fa257b and deployed to production just now
