### ISSUE TITLE
Stats page timing out

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#746]
The stats page and the query behind it are causing timeouts. The query needs rewritten appropriately to return quickly instead of doing multiple calls to dbo.Packages.

**Comment by VideoPlayerCode** [comment]
Ah, so it was a monstrous query that finally reached the tipping point and pegged the database process, hehe. Glad to see your solution so quickly, and great job on the impressive speedup in your new query. Thanks for bringing the service back online!
