### ISSUE TITLE
Chocolatey Installation Script Uses TLS 1 When TLS 1.2 is Available

### ISSUE THREAD

**Issue by elliotkillick** [chocolatey/chocolatey.org#767]
### What You Are Seeing?

```
Unable to set PowerShell to use TLS 1.2 and TLS 1.1 due to old .NET Framework installed. If you see underlying connection closed or trust errors, you may need to do one or mo
re of the following: (1) upgrade to .NET Framework 4.5+ and PowerShell v3, (2) specify internal Chocolatey package location (set $env:chocolateyDownloadUrl prior to install o
r host the package internally), (3) use the Download + PowerShell method of install. See https://chocolatey.org/install for all install options.
```

On Windows 7, PowerShell 2.

### What is Expected?

No message because PowerShell 2 can be forced to use TLS 1.2 with the line of code below.

### How Did You Get This To Happen? (Steps to Reproduce)

`iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`

### Fix

`[System.Net.ServicePointManager]::SecurityProtocol = [Enum]::ToObject([System.Net.SecurityProtocolType], 3072)`

As found here: https://social.technet.microsoft.com/Forums/en-US/fe02169c-30a5-43f5-b0fa-0c1002f7bd03/how-to-use-tls12-secuirty-in-powershell-20?forum=winserverpowershell

This line of code configures TLS 1.2 to be used for the rest of the PowerShell session. This can be confirmed by looking at a packet sniffer like Wireshark to see TLS 1.2 is now certainly being used.

A note should be made about this on the installation page that for (now soon to be EOL) operating systems like Windows 7, you should also paste in this line to use a secure version of TLS.

TLS 1.0 is insecure now due to MITM attacks such as BEAST affecting it.

Also, it would be best practice to disable TLS 1.0/1.1 support on the website to make downgrade attacks impossible. You can see your SSL/TLS ranking [here](https://www.ssllabs.com/ssltest/analyze.html?d=chocolatey.org&s=2606%3a4700%3a10%3a0%3a0%3a0%3a6814%3a4a1c). It's great except for the "This server supports TLS 1.0 and TLS 1.1. Grade will be capped to B from January 2020." part.

**Comment by ferventcoder** [comment]
@elliotkillick we definitely make note of BEAST.

**Comment by ferventcoder** [comment]
@elliotkillick appreciate the notes here, we do walk the security protocol and try to put in the highest available. But it does require .NET Framework 4.5.

**Comment by ferventcoder** [comment]
Not sure if you've had an opportunity to review the installation script?

https://github.com/chocolatey/chocolatey.org/blob/a3bebc2cc70c7ae9130be34870a3fff2d7fc13f8/chocolatey/Website/Install.ps1#L88-L96

**Comment by ferventcoder** [comment]
Just note that once we restrict to 1.2 only, older systems will need to install Windows updates BEFORE they can connect to Chocolatey.org. Most people use Chocolatey to perform the upgrade to .NET framework from the default or older versions. 

Perhaps we take that hard line and just state that's how they will need to go about it once Windows 7/2008 R2 EOL next month?

**Comment by ferventcoder** [comment]
I think we likely need to provide that communication with a little more notice though?

**Comment by ferventcoder** [comment]
Hi @elliotkillick - I will leave this for a few days, but what you are asking to be done can't be done on a box that doesn't yet have .NET Framework 4.5+. We've done extensive work in this area and we provide abilities to connect, so when it is using less than TLS 1.2, it's because your client doesn't yet support it. I'm going to to ahead and close this in favor of a new issue, which is to deprecate the use of lower TLS's.

**Comment by ferventcoder** [comment]
Interim is #655, ultimately #778.
