### ISSUE TITLE
FEATURE REQUEST: markdown handling/parsing "updated" to old style

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey.org#772]
Please consider handling Markdown Heading syntax the same as the old site. The old site would process hashhashhashword and make it a heading while the new site requires hashhashhashspaceword.

```
###Would work on old site (but not GH :-))
### Required on new site.
```

There are HUNDREDS of older packages on chocolatey.org/packages that the description doesn't display as intended now.

**Comment by gep13** [comment]
@bcurran3 am I right in saying that this request is for the currently published package versions that already exist on the Chocolatey Community Repository?  Going forward, have you fixed the nuspec files in your repository (as per the PR's that I sent in) so that any new package versions will work correctly?

**Comment by AdmiringWorm** [comment]
> Please consider handling Markdown Heading syntax the same as the old site.

No, no, just no. The way it was handling it previously was not correct. ATX headers without a space between `#` and the first word have never been considered valid markdown (well, not after there was a spec for markdown anyhow), and as such chocolatey.org should not revert to use that again.

**Comment by bcurran3** [comment]
@gep13 request is for displaying of markdown information on chocolatey.org, specifically descriptions on package pages

@AdmiringWorm "backwards compatibility"

**Comment by gep13** [comment]
>@bcurran3 said...
request is for displaying of markdown information on chocolatey.org, specifically descriptions on package pages

But that doesn't really answer my question... Going forward, are you planning on fixing the descriptions for your packages to have valid markdown, so that at some point in the future, this will all be resolved?

**Comment by AdmiringWorm** [comment]
> @AdmiringWorm "backwards compatibility"

Still a NO from me. If anything, This should have been considered a bug in markdownsharp that it allowed an ATX header without a space at all.

**Comment by bcurran3** [comment]
@gep13 
1 - This has been answered previously at your PR. 
2 - This is not about me. This is about the site and many package pages that have no relation to me. Don't make this about me, it's not. 

@AdmiringWorm 
Hindsight is 20/20. If the legacy site didn't follow Markdown to spec, it doesn't have any relation to the new site not displaying information as the packager intended. This is not about following rules or doing things to spec, this is about supporting what was displayed as intended on the legacy site on the new site with the same results.

**Comment by bcurran3** [comment]
@gep13 

I guess I fail to stand out from the crowd. You really must have me confused with someone less proactive.

https://chocolatey.org/packages/choco-nuspec-checker/2019.12.14

![image](https://user-images.githubusercontent.com/14026600/70854479-2b035d80-1e71-11ea-8226-55c1dd11fe9a.png)

### So I reiterate: This is not about me. I can adapt and clean up my own house. This issue is about chocolatey.org.

**Comment by ferventcoder** [comment]
My question here is I'm about compatibility - yes it was a bug, but it wasn't discovered or it was allowed for so long that now those packages don't look quite right in their descriptions. 

So IMHO we should handle it if they are wrong, but also have the validator require they are fixed for newer versions of packages.

**Comment by ferventcoder** [comment]
@designxsteph can you look into this and see how much work this would require and if this is feasible to do? If it's something we can easily solve in the context of what we have now, let's make it happen, otherwise I think we should discuss options with @kdayo0701

**Comment by designxsteph** [comment]
@ferventcoder for sure, I'll take a look at it and see. I think it'd just be a matter of searching for those patterns/replacing them before Markdig takes over, much like how we are handling some of the links.

**Comment by gep13** [comment]
@ferventcoder did you see the PR that I put up for the validator?

**Comment by gep13** [comment]
@bcurran3 @AdmiringWorm @ferventcoder @designxsteph I have just deployed this to the live production site.

On an example package, it has meant that it has changed from this:

![image](https://user-images.githubusercontent.com/1271146/71247846-7c986600-2311-11ea-9593-654e1e1c6c86.png)

To this:

![image](https://user-images.githubusercontent.com/1271146/71247855-8326dd80-2311-11ea-8fa9-9fefce59a723.png)
