### ISSUE TITLE
API endpoint https://chocolatey.org/api/v2/Packages() down right now

### ISSUE THREAD

**Issue by SimonOfHH** [chocolatey/chocolatey.org#773]
### What You Are Seeing?

https://chocolatey.org/api/v2/Packages() is unavailable. Calling "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" returns a "The operation has timed out" error.
Opening the page in the browser returns either a "The service is unaviable" or shows a CloudFlare-page indicating that the service is down.

![image](https://user-images.githubusercontent.com/17087203/70859211-05796100-1f10-11ea-9961-283d83d74b84.png)

Under https://status.chocolatey.org/ everything is marked as Operational.

### What is Expected?
A responding API 😉

### How Did You Get This To Happen? (Steps to Reproduce)
Just try calling https://chocolatey.org/api/v2/Packages() in the browser or try the suggested script and wait around 2 minutes (not sure about the exact period).

Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

**Comment by SimonOfHH** [comment]
Seems to be resolved already. Sorry for the fuzz

**Comment by HenkPoley** [comment]
Down again 😐
