### ISSUE TITLE
Download stats not working

### ISSUE THREAD

**Issue by mkevenaar** [chocolatey/chocolatey.org#774]
### What You Are Seeing?
No download stats for packages, counter stays at 0

### What is Expected?
Stats to appear.

### How Did You Get This To Happen? (Steps to Reproduce)
Have a look at the download stats for several packages:
https://chocolatey.org/packages/microsoft-windows-terminal
https://chocolatey.org/packages/lastpass

For more recent packages:
https://chocolatey.org/packages?prerelease=false&sortOrder=package-created

**Comment by pauby** [comment]
We know what this issue is and I'll have it fixed shortly.

**Comment by ferventcoder** [comment]
@pauby I was just grabbing this link to send it over :D

**Comment by pauby** [comment]
This has been resolved now. Both of those packages have now got updated download numbers in the database and will appear on the website once the cache expires (a few hours). Will keep this ticket open until they appear on the website.

**Comment by pauby** [comment]
Both package numbers have updated on the page.

**Comment by RickStrahl** [comment]
Yup works for me again too... but this is a recurring problem. It's been a lot better, but this last episode lasted for at least 2 weeks of no counter stats.

**Comment by ferventcoder** [comment]
Hi @RickStrahl - this was a fix to move things out of the website where they would time out sometimes to a different way of handling it. However while in transition, there was a change to disable an aspect of that that wasn't reenabled at the end of the transition and it was just missed for a little while (2 weeks it appears). But now you should see near zero issues with this (unless we have another misconfiguration).

**Comment by ferventcoder** [comment]
So long answer to say this should no longer be a recurring problem ever again. 

We appreciate you always keeping us appraised of this and I'm glad we could finally get it to a place where it should no longer be an issue at all!

**Comment by ferventcoder** [comment]
For reference - https://github.com/chocolatey/chocolatey.org/issues/750

**Comment by RickStrahl** [comment]
Cool - I'll be sure to let you know if it breaks again :smile:
