### ISSUE TITLE
Require TLS 1.2 minimum

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#778]
Right now we let clients dial down to a lower TLS setting when they don't yet have the higher levels. This is done to allow for older Windows versions to connect and get updated through Chocolatey. However those older clients are coming to an EOL in January and we need to think about closing the gap on this so that SSL/TLS downgrade attacks would no longer be possible.

A lot of the notes for this came from the conversation in #767.

**Comment by ferventcoder** [comment]
Mostly this is thinking about the notifications and timelines as flipping to this is very simple.

**Comment by ferventcoder** [comment]
From what I'm seeing in reports, nearly all users are TLS 1.2+. So let's look to provide notification and do this by end of January @pauby .

**Comment by pauby** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deprecate < TLS 1.2 on chocolatey.org](https://trello.com/c/2vq4Ns9Y/102-deprecate-tls-12-on-chocolateyorg)

**Comment by pauby** [comment]
Blog post [published](https://chocolatey.org/blog/remove-support-for-old-tls-versions). Announcements made via Twitter, Slack, Gitter and Google Groups.

**Comment by pauby** [comment]
Reminder announcements made via Twitter, Gitter and Slack.

**Comment by pauby** [comment]
Reminders sent:

* 28 Jan
* 30 Jan
* 2 Feb
* 3 Feb

TLS 1.2 is now set as the minimum supported protocol for chocolatey.org.

**Comment by ferventcoder** [comment]
Docs and install ps1 files now reflect the requirement for TLS 1.2
