### ISSUE TITLE
Access to chocolatey.org is patchy

### ISSUE THREAD

**Issue by pezz** [chocolatey/chocolatey.org#780]
### What You Are Seeing?

Seeing connectivity issues when using choco or even searching the main site for packages.

'choco outdated' does the following several times randomly during package checks:

> Error retrieving packages from source 'https://chocolatey.org/api/v2/':
>  Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

Some packages get checked fine, others produce that error, it seems random.

https://chocolatey.org/packages?q=something also randomly returns a simple "The service is unavailable" message to a browser, you can refresh and the next request will work.

### What is Expected?

Access to work consistently.

### How Did You Get This To Happen? (Steps to Reproduce)

As described, using the choco command or searching packages on the web site.

**Comment by elior-ashkenazi** [comment]
Suffering the same issues for the last hour (07:00 am UTC).
Status page indicates everything should work as expected

**Comment by gep13** [comment]
@elior-ashkenazi the status page currently isn't automatically updated when there are issues, and instead, this is a manual process.  There are ongoing issues with the site that we are working very hard to resolve.

**Comment by elior-ashkenazi** [comment]
@gep13 Great to hear Gary! Appreciate your update :)

**Comment by SlyDave** [comment]
Just a quick update to say https://chocolatey.org/api/v2 is still offline, I was very confused when checking the status page showing no issues :P - it's been over 10 hours, might want to find 2 mins to update it :)

**Comment by SlyDave** [comment]
looks like it's back up, for now at least! good work.

**Comment by tschoonj** [comment]
Down again 😢

**Comment by ferventcoder** [comment]
Please keep an eye on https://status.chocolatey.org. There are known issues that are happening intermittently.
