### ISSUE TITLE
chocolatey.org website package search results intermittently missing existing packages

### ISSUE THREAD

**Issue by whitis** [chocolatey/chocolatey.org#782]
### What You Are Seeing?
blank search results, or incomplete results in spite of package existing
"fldigi" = empty results
"ham radio" = klog

### What is Expected?
search results should include the packages that actually match the name or the search query.
fldigi = fldigi
"Ham radio" = chirp.portable chirp.install chirp fldigi gridtracker klog winlog32 sd jtdx jtalert wsjtx

### How Did You Get This To Happen? (Steps to Reproduce)
https://chocolatey.org/search?q=fldigi
0 results
https://chocolatey.org/search?q=flrig
0 results
on windows machine:
choco search fldigi
0 packages found
choco install fldigi
proceeds to install package

I have seen this on well over a dozens of different packages in the last 24 hours.  Sometimes there was an error message that the server was done but often it was just returning an empty list of search results.   If I google "chocolatey fldigi", it will take me to the chocolatey page for that package and the package looks current.
Also, the following search returns exactly one result (with or without the space)
https://chocolatey.org/packages?q=ham+radio
Previously, less than 24 hours ago, the same search returned about 14  results.  That is how I knew, in the first place, that fldigi was there.  

Just opened a new tab on firefox (linux):
Search for "ham radio" Returned 11 Packages
getting the same results in tabs that already had chocolatey opened.
But later, I expect to get bogus results again.

**Comment by ferventcoder** [comment]
Please watch https://status.chocolatey.org - there are some issues that are being worked on. Until then you are going to see intermittent results. HTH

**Comment by whitis** [comment]
You do not appear to have addressed the problem.

1. database outage
2. website responds incorrectly to database outage
3. choco responds incorrectly to database not being available
4. chocolateyGUI probably also responds incorrectly (untested)

Neither the website nor the choco command line tool correctly responded that "the database is borked", instead they responded 0 results.    On some occasions they said the search was unavailable but many, many times they just returned erroneous results.

Also, you have a fundamental issue if a server going down makes the system non-operational.   Package info should be cached at the client level.   Preferably not in a way that users are constantly downloading the whole database all the time.   Something like CouchDB and the couch replication protocol might prove useful here.  PouchDB even lets web sites cache CouchDB offline.

Have a happy new year.

**Comment by gep13** [comment]
@whitis we deployed some changes to the site yesterday that we are hoping will addresses some of the concerns that you are seeing.  There are other items in our backlog to address some of the others, like local package indexing which is something that we are looking to tackle.  We are monitoring the situation, and are working hard to resolve the problems that we are currently seeing.
