### ISSUE TITLE
Bad link on Pricing page

### ISSUE THREAD

**Issue by auveae** [chocolatey/chocolatey.org#788]
### What You Are Seeing?
Link to Package Shims under the Open Source heading on the pricing page takes browser to the error page.

### What is Expected?
Link should take browser to Shimming in docs

### How Did You Get This To Happen? (Steps to Reproduce)
Click it.
Link points to 
https://chocolatey.org/docs/features-shims
instead of 
https://chocolatey.org/docs/features-shim

**Comment by gep13** [comment]
@auveae thank you for taking the time to raise this issue.  I have just raised a PR to address this problem here:

https://github.com/chocolatey/chocolatey.org/pull/789

**Comment by ferventcoder** [comment]
This is scheduled to go out with next website push. Thanks @gep13!!

**Comment by ferventcoder** [comment]
And this should be live. Thanks!
