### ISSUE TITLE
4 spaces being converted to code block on package description

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#790]
### What You Are Seeing?
On packages that have 4 spaces inside the package description area, the 4 spaces is being converted to a code block when it should not be. 

See: https://chocolatey.org/packages/powershell-preview#description and compare it to the nuspec at: https://github.com/DarwinJS/ChocoPackages/blob/d6967a91b3787020f4938aa0f8a8face8d47e134/pwshpackages/powershell-preview/powershell-preview.nuspec#L20-L48

### What is Expected?
In this case it is not intended for the 4 spaces to be converted to a code block.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Go to https://chocolatey.org/packages/powershell-preview#description and notice that the description is all in a code block and highlighted.

![code-block](https://user-images.githubusercontent.com/42750725/71671654-355e9c00-2d39-11ea-844e-6118786d8ee4.png)

**Comment by gep13** [comment]
@designxsteph this has been deployed...

![image](https://user-images.githubusercontent.com/1271146/71982387-40736980-321c-11ea-929e-c71269b33cc8.png)
