### ISSUE TITLE
Windows 10 1909 64 bit: connection issue

### ISSUE THREAD

**Issue by erotavlas-turbo** [chocolatey/chocolatey.org#795]
Hi,
I just installed a fresh copy of windows 10 1909 64 bit and I could not install chocolatey via default command: `Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`. After several trials, I was able to install it. Now, I always get the error messages:
```
By installing you accept licenses for the packages.
Error retrieving packages from source 'https://chocolatey.org/api/v2/':
 Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.
megatools not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more 
 assistance.
[NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.
```
I think it is related to the latest windows version or to chocolatey a server problem.

**Comment by ferventcoder** [comment]
Bumped over to https://github.com/chocolatey/chocolatey.org/issues/795. Going to close as the status updates are here for this one at https://status.chocolatey.org
