### ISSUE TITLE
A number of broken links need corrected/updated

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#796]
### What You Are Seeing?
There are a number of broken links that need addressed on chocolatey.org. Some of them might be parsing incorrectly in and some may not exist. Below is a list of known links at this time (not including links found in choco-wiki.

- [x] docs/commands-setapikey 
Addressed [here](https://github.com/chocolatey/chocolatey.org/pull/797)

- [x] docs/helpers-get-packageparameters 
Addressed [here](https://github.com/chocolatey/chocolatey.org/pull/797) and [here](https://github.com/chocolatey/chocolatey.org/pull/799) and will need accepted into wiki [here](https://github.com/chocolatey/choco-wiki/pull/172)

- [x] resources/testimonials 
Addressed [here](https://github.com/chocolatey/chocolatey.org/pull/797)

- [x]  resources/case-studies/managing-windows-at-facebook > resources/case-studies/winops-2017-dan-sedlacek-managing-windows-at-facebook
Addressed [here](https://github.com/chocolatey/chocolatey.org/pull/799)
**Note: I can not find a direct link to the first url in the code base.**

- [x]  docs/features-shims > docs/features-shim
Addressed [here](https://github.com/chocolatey/chocolatey.org/pull/799)
**Note: I can not find a direct link to the first url in the code base.**

- [x]  docs/install > docs/installation
Addressed [here](https://github.com/chocolatey/chocolatey.org/pull/799)
**Note: I can not find a direct link to the first url in the code base.**

### What is Expected?
I would expect these links to work or for them to be corrected to the right link.

### How Did You Get This To Happen? (Steps to Reproduce)
Visit the links above and notice you'll get a 404 or a "Oh no we broke something" page.

**Comment by ferventcoder** [comment]
@gep13 is this still in working, or is this what was deployed this morning?

**Comment by ferventcoder** [comment]
@designxsteph noticed a couple here are not marked.

**Comment by gep13** [comment]
>@ferventcoder said...
@gep13 is this still in working, or is this what was deployed this morning?

I deployed a new version of the site this morning which included the PR that @designxsteph did which addressed some of the broken links, but I left this open as it was my understanding that there were still a couple of outstanding links that needed to be addressed.

**Comment by designxsteph** [comment]
@gep13 @ferventcoder Yes, I have another branch which I will put a PR up today which fixes the remaining issues brought up. I thought it'd be good to get the ones out that I had fixed already. A few of them were located in choco-wiki and have been fixed there.
