### ISSUE TITLE
500 HTTP error on uploading a package

### ISSUE THREAD

**Issue by taoxin2988** [chocolatey/chocolatey.org#798]
### What You Are Seeing?
Oh no, we broke something!
You might be here because:
There is an error on our server and the server is "given her all she's got, captain."
The system is down, the system is down, the system is down...

### What is Expected?
I would  like to know how long the function of edit package will be restored

### How Did You Get This To Happen? (Steps to Reproduce)
 when I upload a package and click "Verify Details & Submit", I got  en error upon in the reply for several days.

**Comment by pauby** [comment]
You don't mention which package(s) this is for?

**Comment by taoxin2988** [comment]
> You don't mention which package(s) this is for?

my package is platon_mtool_other, the current version is 0.7.4, and I want to update to 0.7.5

**Comment by benshep** [comment]
I have this issue too, for getiplayer updating from 3.23 to 3.24.

**Comment by pauby** [comment]
@taoxin2988 Thanks for clarifying that - I wanted to check the [package exists](https://chocolatey.org/packages/platon_mtool_other). To get the error message you are clicking the 'Edit Package' button on the package page and then you immediately get the 'Oh no, we broke something!'. Are those the exact steps you're taking?

**Comment by pauby** [comment]
@benshep Can you clarify exactly what you're doing to get that error?

**Comment by taoxin2988** [comment]
> @benshep Can you clarify exactly what you're doing to get that error?

Actually, you can operates like this: first of all,  go into Account; second, click "Upload Package", and you will be asked to upload your  ****.nupkg , next you need to click "Verify Details & Submit", then I got the error above.

**Comment by taoxin2988** [comment]
> @taoxin2988 Thanks for clarifying that - I wanted to check the [package exists](https://chocolatey.org/packages/platon_mtool_other). To get the error message you are clicking the 'Edit Package' button on the package page and then you immediately get the 'Oh no, we broke something!'. Are those the exact steps you're taking?

alternatively, you can click "Manage Packages" in your Account, and select a package you wanna update, then you will find a button "Edit Package" in that page,click this button and you will link into the upload pages like what I descripted above.

**Comment by benshep** [comment]
> 
> 
> @taoxin2988 Thanks for clarifying that - I wanted to check the [package exists](https://chocolatey.org/packages/platon_mtool_other). To get the error message you are clicking the 'Edit Package' button on the package page and then you immediately get the 'Oh no, we broke something!'. Are those the exact steps you're taking?

Yes, that's exactly what I'm doing.

**Comment by ferventcoder** [comment]
I haven't dug into this but there is an exception on this we are digging into.

**Comment by ferventcoder** [comment]
As a workaround for now, can we have you use choco push?

**Comment by taoxin2988** [comment]
> As a workaround for now, can we have you use choco push?

choco push works when I push a new package, but I want to update my package, it give me a error like: "Failed to process request. 'The package xxxx have a previous version in a submitted state, and no approved stable releases.' " when I push it.

**Comment by gep13** [comment]
>@taoxin2988 said...
choco push works when I push a new package, but I want to update my package, it give me a error like: "Failed to process request. 'The package xxxx have a previous version in a submitted state, and no approved stable releases.' " when I push it.

This is a separate, and valid, error message.  If the initial version of a package isn't in an approved (or rejected) state, then you can't push a new package version.  If the package version is currently in a submitted state, then make changes to the package, but push it with the same version number, if you are looking to fix issues that were identified with it.

**Comment by taoxin2988** [comment]
> > @taoxin2988 said...
> > choco push works when I push a new package, but I want to update my package, it give me a error like: "Failed to process request. 'The package xxxx have a previous version in a submitted state, and no approved stable releases.' " when I push it.
> 
> This is a separate, and valid, error message. If the initial version of a package isn't in an approved (or rejected) state, then you can't push a new package version. If the package version is currently in a submitted state, then make changes to the package, but push it with the same version number, if you are looking to fix issues that were identified with it.

Thank your for your reply. 
exactly, the current version of my package is not in an approved state, I have made some changes to this package locally, but I can not upload the modified package to the chocolatey because of the upload error. Is there any way to upload it with choco push command in this situation?

**Comment by FredHappyface** [comment]
This error "Oh no, we broke something! [...]" also occurs when submitting a new package as was the case for me yesterday

**Comment by pauby** [comment]
@FredHappyface It will happen when you use the [Upload Package](https://github.com/chocolatey/chocolatey.org/issues/798#issuecomment-571369750). Is this what you were using? If so, [can you use](https://github.com/chocolatey/chocolatey.org/issues/798#issuecomment-571772672) `choco push`?

**Comment by AdmiringWorm** [comment]
@taoxin2988 submit the updated package with the same version as the one already on chocolatey.org.
As long as it isn't approved/exempted, package versions should be updatable.

**Comment by FredHappyface** [comment]
Hello, 

Apologies for the delay in getting back to you, I have just got back to my windows machine

I've had success with one package but not the other:

```
choco push .\firanf.4.202.nupkg --source https://push.chocolatey.org/
Chocolatey v0.10.15
Attempting to push firanf.4.202.nupkg to https://push.chocolatey.org/
Failed to process request. 'Origin Time-out'.
The remote server returned an error: (524) Origin Time-out..
```

^ Despite the error, the package is visible under unlisted packages 

```
choco push firacodenf.2.1.0.nupkg --source https://push.chocolatey.org/
Chocolatey v0.10.15
Attempting to push firacodenf.2.1.0.nupkg to https://push.chocolatey.org/
An error has occurred. It's possible the package version already exists on the repository.
```

^ This package is not visible under my packages so I am doubtful that the package has been submitted

Thank you

**Comment by FredHappyface** [comment]
(I was previously using the web UI)

**Comment by gep13** [comment]
@FredHappyface both packages are there:

https://chocolatey.org/packages/firanf
https://chocolatey.org/packages/firacodenf

They are in the moderation queue, and will go through the automated process.

**Comment by taoxin2988** [comment]
> @taoxin2988 submit the updated package with the same version as the one already on chocolatey.org (using `choco push`).
> As long as it isn't approved/exempted, package versions should be updatable.

I'm afraid it doesn't work,  When I use choco push, I got error message like: 
> choco push platon_mtool_other.0.7.5.nupkg --source https://chocolatey.org/
Chocolatey v0.10.15
Attempting to push platon_mtool_other.0.7.5.nupkg to https://chocolatey.org/
Failed to process request. 'The package platon_mtool_other have a previous version in a submitted state, and no approved stable releases.'.

**Comment by AdmiringWorm** [comment]
@taoxin2988 

> with the same version as the one already on chocolatey.org

  ^^ Is what I said, you currently got version 0.7.4 and 0.7.3 on chocolatey.org.
Pushing 0.7.5 would be a **new** version, which is correctly rejected by the server as you don't have any approved version available on that package.

**Comment by jhspetersson** [comment]
Same happens to my package `fselect` which is stuck in the middle of updating from `0.6.7` to `0.6.8` version. I got the error message just after pushing the Verify button.

**Comment by ferventcoder** [comment]
We are getting to the bottom of this one still.

**Comment by jhspetersson** [comment]
Thank you, that worked for me.

**Comment by gep13** [comment]
@taoxin2988 @jhspetersson @benshep @FredHappyface for those that are experiencing this issue...  Does the error page appear straight away after clicking the `verify` button, or is there a delay between clicking it and it appearing?

**Comment by benshep** [comment]
There's a delay, during which Firefox displays "Sending request to chocolatey.org..." in the status bar.

**Comment by benshep** [comment]
I just tried the `choco push` command. I haven't used it before, I always uploaded via the website. Here's the error from that:

> Attempting to push getiplayer.3.24.nupkg to https://push.chocolatey.org/
> Failed to process request. 'Origin Time-out'.
> The remote server returned an error: (524) Origin Time-out..

**Comment by codingfreak** [comment]
I just wanted to add that I experience the same as @benshep. Pushing adds a submission to the profile page but ends up in an error in the command line. Upload via portal fails completely.

**Comment by sumo300** [comment]
Unsure if this will be helpful, but I've been trying to update MediaElch over the past few days.  At first, I was doing it through the web UI and getting the 500 error.  Then, attempted to use `choco push` today and got the following message:

```
Attempting to push MediaElch.2.6.4.nupkg to https://push.chocolatey.org/
An error has occurred. It's possible the package version already exists on the repository.
```

When I looked at the package version history on chocolatey.org, it is now listed as `Pending Automated Review`.  It was not there before.  So, the push worked, but still showed me an error.

**Comment by webprofusion-chrisc** [comment]
Sorry to 'me too' but manual upload (new version of certifytheweb package) using the website failed for my also  - it gets to the Verify Upload step then says 'Oh no we broke something'. 

Using choco push instead returned an error 524 which I know is because the cloudflare front end is timing out it's request (but the upload has still happened):
```
choco push certifytheweb.4.1.7.nupkg --source https://push.chocolatey.org/
Chocolatey v0.10.15
Attempting to push certifytheweb.4.1.7.nupkg to https://push.chocolatey.org/
Failed to process request. 'Origin Time-out'. 
The remote server returned an error: (524) Origin Time-out..
```
The package is now pending automated review as normal.

As a complete guess I'd say the web UI has a short internal timeout (database?) or needs some TLC but you can probably see more in the server logs. Likewise the choco push. I've not looked much at the code but I'd suggest making some common actions async so you don't stall the web worker while the request is in progress, unless you have heaps of available worker processes. I have no idea how hosting is currently being done.

**Comment by BornToBeRoot** [comment]
Same issue updating from 2019.12.0 to 2020.1.0: https://chocolatey.org/packages/NETworkManager

**Comment by ildar-shaimordanov** [comment]
The issue is still there. Updating packages doesn't work via web. Seems something serious.

**Comment by lareeth** [comment]
Any update on this? It seems to be a common issue that many people have had over the past few months, tickets just get closed and told its fixed. https://github.com/chocolatey/chocolatey.org/issues/499 was supposed to fix this, but it still happening.

When trying to automate the build and upload of packages its not helpful that the cli fails, even if the package uploads successfully, as then the build needs to be re-run until it passes, as builds cannot be in a failed state. Eventually running multiple times, the cli will success and mark the build as passed.

The error can be one of the following
```
Attempting to push concourse.5.7.1.nupkg to https://push.chocolatey.org/
An error has occurred. It's possible the package version already exists on the repository.
```
```
Attempting to push concourse.5.7.1.nupkg to https://push.chocolatey.org/
Failed to process request. 'Origin Time-out'. 
The remote server returned an error: (524) Origin Time-out..
```

Can we have an official update on this?

**Comment by calvn** [comment]
I am encountering the same error when trying to update the `consul` choco package. The upload is done programmatically via `choco push` through AppVeyor. No process changes were made between now and the last few releases aside from bumping the version.


```
...
Added ApiKey for https://push.chocolatey.org/
Chocolatey v0.10.15
Attempting to push consul.1.6.2.nupkg to https://push.chocolatey.org/
An error has occurred. It's possible the package version already exists on the repository.
Command exited with code 1
```

Full build logs: https://ci.appveyor.com/project/calvn/chocolatey-consul/builds/31837479

**Comment by riverar** [comment]
Same issue here for a brand new `eartrumpet` package. If there's anything else I can help with, reach out. Will try push in the meantime.

**Comment by wget** [comment]
Had the exact same issue when pushing KeeWeb 1.13.1. It was always complaining with this error message:
```
An error has occurred. It's possible the package version already exists on the repository.
```

I had to use a high bitrate upload connection to fix the issue (used a VM hosted on Azure). After some trials, the Chocolatey website finally accepted the package. Maybe the issue could be caused by Cloudflare then?

**Comment by FredHappyface** [comment]
Still causing issues. I keep getting the following error:

```none
An error has occurred. It's possible the package version already exists on the repository.
```

I have tried changing the version number as below:

![image](https://user-images.githubusercontent.com/41634689/82362613-83342200-9a04-11ea-91c0-7366e014e890.png)

Is there an ETA on this as there is no way for me to update packages

**Comment by polyvertex** [comment]
Same issue here when trying to upload the [keypirinha](https://chocolatey.org/packages/keypirinha) package via the web site.

`choco push` *seems* successful though ("package submitted for moderation" email).

There is a less-than-a-second delay after clicking on `Verify Details & Submit`.

**Comment by lareeth** [comment]
Can we get an official response to this @ferventcoder? This is ridiculous that no one has addressed this issue and that its affecting so many people

**Comment by ferventcoder** [comment]
For choco push, we are discussing at #613. We've just pushed some updates to the website a few days ago that could have a nice side effect of fixing a few aspects of this as well.

**Comment by ferventcoder** [comment]
For the website parts, we are gearing up to do some work on some of the lingering community issues that we've unfortunately not been able to address due to competing priorities. Not meant as an excuse by any means - we'll be working on addressing this and other issues that have been somewhat harder to address over the next few weeks.

**Comment by lareeth** [comment]
Thank you for finally providing an update, I look forward to hearing any improvements to community communication

**Comment by gep13** [comment]
We have discussed this within the team, and we have come to the decision that uploading nupkg's through the website isn't going to be supported going forward.  Instead, the recommendation is going to be using the `choco push` command.  This fits in better with the natural flow of creating a package, i.e. you run `choco pack` followed by a `choco push`.

There is an open [PR](https://github.com/chocolatey/chocolatey.org/pull/891) which removes the ability to upload a nupkg directly through the site.

Please let us know if you have any concerns about this approach.
