### ISSUE TITLE
choco install failed if package version specified

### ISSUE THREAD

**Issue by itn3000** [chocolatey/chocolatey.org#804]
### What You Are Seeing?

When I attempted to install 7zip of specific version with chocolatey,
installation is failed with following error message.
```
Chocolatey v0.10.15
Installing the following packages:
7zip
By installing you accept licenses for the packages.
7zip not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '19.0'. It is possible that version
 does not exist for '7zip' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - 7zip - 7zip not installed. The package was not found with the source(s) liste
d.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '19.0'. It is possible that version
 does not exist for '7zip' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare
```

### What is Expected?

7zip installation successfull.

### How Did You Get This To Happen? (Steps to Reproduce)

1. install chocolatey(version 0.10.15)
2. execute `choco install 7zip --version 19.0`

executing `choco install 7zip` was success.
And I tried to install another version(like `18.1`), installation was also failed.

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

2020-01-09 15:19:07,901 4692 [DEBUG] - XmlConfiguration is now operational
2020-01-09 15:19:07,937 4692 [INFO ] - ============================================================
2020-01-09 15:19:08,063 4692 [INFO ] - Chocolatey v0.10.15
2020-01-09 15:19:08,069 4692 [DEBUG] - Chocolatey is running on Windows v 10.0.14393.0
2020-01-09 15:19:08,070 4692 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2020-01-09 15:19:08,071 4692 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2020-01-09 15:19:08,076 4692 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" install 7zip --version 19.0
2020-01-09 15:19:08,077 4692 [DEBUG] - Received arguments: install 7zip --version 19.0
2020-01-09 15:19:08,113 4692 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2020-01-09 15:19:08,117 4692 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2020-01-09 15:19:08,122 4692 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2020-01-09 15:19:08,159 4692 [DEBUG] - Performing validation checks.
2020-01-09 15:19:08,163 4692 [DEBUG] - Global Configuration Validation Checks:
2020-01-09 15:19:08,164 4692 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
2020-01-09 15:19:08,165 4692 [DEBUG] - System State Validation Checks:
2020-01-09 15:19:08,166 4692 [DEBUG] -  Reboot Requirement Checks:
2020-01-09 15:19:08,168 4692 [DEBUG] -  - Pending Computer Rename = Checked
2020-01-09 15:19:08,169 4692 [DEBUG] -  - Pending Component Based Servicing = Checked
2020-01-09 15:19:08,170 4692 [DEBUG] -  - Pending Windows Auto Update = Checked
2020-01-09 15:19:08,171 4692 [DEBUG] -  - Pending File Rename Operations = Ignored
2020-01-09 15:19:08,171 4692 [DEBUG] -  - Pending Windows Package Installer = Checked
2020-01-09 15:19:08,172 4692 [DEBUG] -  - Pending Windows Package Installer SysWow64 = Checked
2020-01-09 15:19:08,175 4692 [INFO ] - 2 validations performed. 2 success(es), 0 warning(s), and 0 error(s).
2020-01-09 15:19:08,176 4692 [DEBUG] - The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type
2020-01-09 15:19:08,177 4692 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
2020-01-09 15:19:08,183 4692 [DEBUG] - Configuration: CommandName='install'|
CacheLocation='C:\Users\malion\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='False'|Verbose='False'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='7zip'|Version='19.0'|
AllVersions='False'|SkipPackageInstallProvider='False'|
PackageNames='7zip'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.14393.0'|
Information.PlatformName='Windows Server 2016'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='False'|
Information.UserName='malion'|
Information.UserDomainName='MALIONCLOUDITOT'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\Users\malion'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
2020-01-09 15:19:08,184 4692 [DEBUG] - _ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
2020-01-09 15:19:08,188 4692 [INFO ] - Installing the following packages:
2020-01-09 15:19:08,189 4692 [INFO ] - 7zip
2020-01-09 15:19:08,189 4692 [INFO ] - By installing you accept licenses for the packages.
2020-01-09 15:19:08,448 4692 [ERROR] - 7zip not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '19.0'. It is possible that version 
 does not exist for '7zip' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more 
 assistance.
2020-01-09 15:19:08,457 4692 [WARN ] - 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2020-01-09 15:19:08,459 4692 [INFO ] - 
2020-01-09 15:19:08,460 4692 [ERROR] - Failures
2020-01-09 15:19:08,460 4692 [ERROR] -  - 7zip - 7zip not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '19.0'. It is possible that version 
 does not exist for '7zip' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more 
 assistance.
2020-01-09 15:19:08,462 4692 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2020-01-09 15:19:08,466 4692 [DEBUG] - Exiting with 1

</p>

</details>

**Comment by pauby** [comment]
The issue was down to two Cloudflare rules that were put in place a little while ago. What is puzzling me is why it has caused this now rather than when they were implemented. There is still some work to do around this but as far as I can see this issue is now resolved.

@danielskowronski @itn3000 @jlholtus do you agree or are you still seeing the issues?

**Comment by ferventcoder** [comment]
This was my fault here folks - we were tweaking firewall rules based on invalid attempts of access. This was based on looking at logs and seeing what bad things people are doing. Missed that there was a valid use for comma in the url.

**Comment by AtlanticRebel** [comment]
Would this affect installing chocolatey as well?  Trying to install on a new deployment, and powershell script is timing out when trying to download the package, tried to open https://chocolatey.org/api/v2/package/chocolatey/ in Chrome, and am getting CF errors shown below.

![image](https://user-images.githubusercontent.com/7734496/72092089-ffe12200-32e7-11ea-9973-eb0dd6ab2def.png)

**Comment by v1v** [comment]
@AtlanticRebel , I don't see that particular message in my browser, neither when running the curl command

```
curl -sSL -D -  https://chocolatey.org/api/v2/package/chocolatey/ -o /dev/null
HTTP/2 302 
date: Thu, 09 Jan 2020 18:09:06 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d9fecfc2c5d3b71f57f60ed6a9bc47d8b1578593346; expires=Sat, 08-Feb-20 18:09:06 GMT; path=/; domain=.chocolatey.org; HttpOnly; SameSite=Lax; Secure
cache-control: private
location: https://packages.chocolatey.org/chocolatey.0.10.15.nupkg
x-frame-options: deny
cf-cache-status: DYNAMIC
strict-transport-security: max-age=12960000
x-content-type-options: nosniff
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 55285c3cca5f361b-MAN

HTTP/2 200 
date: Thu, 09 Jan 2020 18:09:06 GMT
content-type: application/octet-stream
content-length: 4067171
set-cookie: __cfduid=d2c073af438c497890fd2d9ee56719e321578593346; expires=Sat, 08-Feb-20 18:09:06 GMT; path=/; domain=.chocolatey.org; HttpOnly; SameSite=Lax; Secure
x-amz-id-2: KfxIt6/X5j+g9OCLKOOI4aCkBBWPvRtPMDRCP3Q5xLKYWd8UOTBVwxIqnzDr3Z0vjnwhgXFQIxI=
x-amz-request-id: 2FB51CDF4DEAA165
last-modified: Mon, 03 Jun 2019 21:51:36 GMT
etag: "193d9a6e05699976f6e3d8dcaa0eefdf"
cache-control: max-age=14400
cf-cache-status: HIT
age: 466
accept-ranges: bytes
strict-transport-security: max-age=12960000
x-content-type-options: nosniff
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 55285c404bdbd214-MAN

```

**Comment by AtlanticRebel** [comment]
Thanks @v1v looks like it must have been temporary, and entirely coincidental, works fine now.

**Comment by pauby** [comment]
@AtlanticRebel Your issue was different from the original issue and was down to queries taking an excessive amount of time.

**Comment by itn3000** [comment]
it seems to work fine, thank you for fixing.
