### ISSUE TITLE
Unable to submit package to chocolaty.org via the web interface.

### ISSUE THREAD

**Issue by ericjaystevens** [chocolatey/chocolatey.org#809]
### What You Are Seeing?

I received the following error when submitting a new package. I tried a few times on several machines over the course of 24 hours or so.

```Oh no, we broke something!
You might be here because:
There is an error on our server and the server is "given her all she's got, captain."
The system is down, the system is down, the system is down.
Our name is smalls.
We have logged the error and we will look into it, and make sure it doesn’t happen again. However, if you keep seeing this page please File a bug on the Chocolatey Gallery issue tracker.
```

### What is Expected?

The package to be submitted and the moderation process to begin.

### How Did You Get This To Happen? (Steps to Reproduce)

from https://chocolatey.org/packages/verify-upload after uploading the attached package. Then click verify details and submit. I created the package using ```choco pack``` and my ```choco --version``` is ```0.10.10```

[circleci-cli.0.1.5879.zip](https://github.com/chocolatey/chocolatey.org/files/4055533/circleci-cli.0.1.5879.zip)

**Comment by mkevenaar** [comment]
@ericjaystevens would you be able to push your package using the [Push command](https://chocolatey.org/docs/commands-push) `choco push mypackage`

**Comment by ericjaystevens** [comment]
@mkevenaar  yes ```choco push .\circleci-cli.0.1.5879.nupkg --source https://push.chocolatey.org/ ``` worked. Appending 'via the web interface.' to the title of the issue.

I received the expected output
```
Chocolatey v0.10.10
Attempting to push circleci-cli.0.1.5879.nupkg to https://push.chocolatey.org/
circleci-cli 0.1.5879 was pushed successfully to https://push.chocolatey.org/

Your package may be subject to moderation. A moderator will review the
package prior to acceptance. You should have received an email. If you
don't hear back from moderators within 1-3 business days, please reply
to the email and ask for status or use contact site admins on the
package page to contact moderators.

Please ensure your registered email address is correct and emails from
noreply at chocolatey dot org are not being sent to your spam/junk
folder.

Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare
```

That achieves my desired result, feel free to close if there is no value in tracking the original issue.

**Comment by mkevenaar** [comment]
I think it's a duplicate from #798

**Comment by ericjaystevens** [comment]
Closing as duplicate of #798
