### ISSUE TITLE
HTTP 500 & 524 errors from OutOfMemoryExceptions when updating data

### ISSUE THREAD

**Issue by vexx32** [chocolatey/chocolatey.org#829]
# What You Are Seeing?

Whenever the website is under load, any update operation on the site (including things like moderation actions) can trigger an OutOfMemoryException which results in HTTP 500 and 524 errors, making moderation difficult at best.

The [Lucene documentation for IndexWriter](https://lucenenetdocs.azurewebsites.net/api/Lucene.Net/Lucene.Net.Index.IndexWriter.html#Lucene_Net_Index_IndexWriter_Commit) mentions that **several** of its methods can potentially throw OutOfMemoryException and we should look to handle that as best we can.

### What is Expected?

Preferable, no OutOfMemoryExceptions should surface and we should be able to deal with them in most instances.

### How Did You Get This To Happen? (Steps to Reproduce)

The issue is currently intermittent, but package moderation actions are known to surface errors at times.

**Comment by mkevenaar** [comment]
Related to #840

**Comment by ferventcoder** [comment]
Pushing the changes out, guess we'll find out pretty fast if this resolves the issues

**Comment by vexx32** [comment]
Thanks for the vote of confidence @ferventcoder 😂 💖
