### ISSUE TITLE
Contact Maintainer, Contact Admins, and Report Abuse forms do not submit

### ISSUE THREAD

**Issue by agyild** [chocolatey/chocolatey.org#830]
### What You Are Seeing?
When I contact the maintainers of a package through **Contact maintainers** page after clicking the submit button and passing the captcha I get logged out of site and I get redirected to the main page. In addition **Send me a copy** option does not seem to work since I don't receive a copy of the message in my e-mail inbox. I am using Mozilla Firefox 72.0.2 64-bit.

### What is Expected?
I should be able to send my message without getting logged out after submitting it and I should see a confirmation message that my message has been sent and finally I should receive a copy of my message when I choose the **Send me a copy** option.

**Comment by designxsteph** [comment]
Hi @agyild thanks for reporting this. I have tested and confirmed this is an issue. It is actually happening on this form and the **Contact Admins** form as well. We will do some investigating on this issue, progress will be tracked here.

**Comment by ferventcoder** [comment]
Merged and pushed to prod. Should be up in the next few minutes.
