### ISSUE TITLE
Could not create SSL/TLS secure channel error when installing Chocolatey

### ISSUE THREAD

**Issue by israelvaldez** [chocolatey/chocolatey.org#833]
Starting today we've started to receive errors like the one below when getting the ps1 file that installs chocolatey from: https://chocolatey.org/install.ps1 where you guys expecting that to happen?
```
The request was aborted: Could not create SSL/TLS secure channel." ---> 
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
  at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
  at System.Net.WebClient.DownloadString(Uri address)
```

These can be fixed on our end by adding workarounds like the one below on Powershell, what is the official workaround that you'd recommend people to follow to alleviate this issue?
```
  $AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'
  [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
  [System.Net.ServicePointManager]::Expect100Continue = $true
```

**Comment by ferventcoder** [comment]
@israelvaldez yesterday we updated the install.ps1 file, but I believe I forgot to remove the cached version from cloudflare. #778

**Comment by ferventcoder** [comment]
Work was done in this commit - https://github.com/chocolatey/chocolatey.org/commit/cf136694755899e3aee2dcb7c77d8c7448f97eaa

**Comment by ferventcoder** [comment]
@israelvaldez did you see the new installation notes showing new instructions at https://chocolatey.org/install? Note that it has a new line included with setting TLS 1.2 properly.


`Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`

**Comment by ferventcoder** [comment]
I think if you use the official installation instructions to actively set TLS 1.2 like the script we have there does, you should be good to go.

I looked at https://chocolatey.org/install.ps1 and it does appear to contain the additional changes to set TLS 1.2 in it, so it should be good as well. I'm going to clear the cache as well in cloudflare to be sure it it updated on whatever edge server you are hitting.

**Comment by ferventcoder** [comment]
Lowering priority, bumping to not an issue and closing now - it appears that new instructions were missed for installation.

**Comment by israelvaldez** [comment]
Now it looks like the docs are pointing to that, for some reason I didn't see anything related to TLS 1.2 in the https://chocolatey.org/docs/installation URL back when I tried to look for clues this morning :(.
