### ISSUE TITLE
Searching while on page x opens page x instead of page 1 of results

### ISSUE THREAD

**Issue by vertigo220** [chocolatey/chocolatey.org#837]
### What You Are Seeing?

If you perform a search, then navigate to another page, then do another search, it will load the results page for the new search that you were on before the search. For example, if you search for "browser" and go to page 2, then search for "firefox," you'll get page 2 of the results for the firefox search. If there are no results on page x (2 in this example), it will then automatically load page 1.

### What is Expected?

It should always start you off with the first page.

### How Did You Get This To Happen? (Steps to Reproduce)

See above

**Comment by designxsteph** [comment]
Thanks for reporting this @vertigo220, unfortunately I'm unable to reproduce the issue. Below are the steps I am taking. Can you let me know if I doing something wrong?

1. Go to https://chocolatey.org/packages
2. Search for "browser"
3. Navigate to the page 2 of results
4. Search for "firefox"

When I do this, after step 4, I am directed to the first page of results for "firefox" as expected and not page 2.

**Comment by vertigo220** [comment]
Sorry, I somehow managed to click the link to the wrong repo and didn't notice. This was meant for the GUI.
