### ISSUE TITLE
Course: In the quiz of course section "Installing Chocolatey" are slashes instead of backslashes

### ISSUE THREAD

**Issue by JohannesKonings** [chocolatey/chocolatey.org#845]
### What You Are Seeing?
Slashes instead of backslashes
https://chocolatey.org/courses/installation/installing?method=installing-chocolatey?quiz=true

![image](https://user-images.githubusercontent.com/14806640/76350661-6dbbc100-630c-11ea-9a65-51d5408428ea.png)

### What is Expected?
Pathes like this:
C:\ProgramData\chocolatey
C:\Program Files (x86)\chocolatey

### How Did You Get This To Happen? (Steps to Reproduce)
https://chocolatey.org/courses/installation/installing?method=installing-chocolatey?quiz=true

**Comment by ferventcoder** [comment]
While the forward slashes will work, that does need to be fixed. Thanks for noting that!
