### ISSUE TITLE
NullReferenceException and AlreadyClosed errors from Index writer accesses

### ISSUE THREAD

**Issue by vexx32** [chocolatey/chocolatey.org#853]
See (#829) for prior reference.

Following the related PR's merge (#826) and code pushed to the website, things have looked _more_ stable but still prone to failure after a few days.

Current errors seen in the logs related to the index writer include:

- NullReferenceException
- AlreadyClosed

This indicates we may have threading issues, and some index writes may still be lost while the index writer is being regenerated.

Possible fix may be to block get operations for the index writer while it is being regenerated. I'm poking at the code currently, may submit a PR in a bit for review.

/cc @gep13  and @ferventcoder

**Comment by ferventcoder** [comment]
Merged into master at https://github.com/chocolatey/chocolatey.org/commit/1f70af7bdeb70482965351d28eac571a1adba604. Pushed out just now.
