### ISSUE TITLE
I can't sign up to chocolatey.org or send message to maintainers

### ISSUE THREAD

**Issue by sffred** [chocolatey/chocolatey.org#861]
I have seen here is the warning "Unable to correctly validate spam validation response: missing-input-response" whenever I filled the sign up form or want to send message to any maintainers. And I have seen no way to get over it. What's going on or what can be done to fix this issue?

**Comment by mkevenaar** [comment]
@sffred have you tried using an incognito browsing session? 
If that works, can you check your browser plugins for ad-blocking and/or script blockers?

Chocolatey website requires Google Captcha to validate your request.

**Comment by sffred** [comment]
@mkevenaar I don't have any browser plugins, and opening an InPrivate window doesn't work.
You said that it requires Google Captcha? Since I am in China, do I need a proxy or something to solve this problem?

**Comment by sffred** [comment]
> @sffred have you tried using an incognito browsing session?
> If that works, can you check your browser plugins for ad-blocking and/or script blockers?
> 
> Chocolatey website requires Google Captcha to validate your request.

Yeah, after I set up a proxy, I can sign up now. Thanks a lot. but I have to comment that this problem is not very friendly to Chinese users.
