### ISSUE TITLE
Intermittent pre-releases being returned or selected for installation (if they are the absolute latest version)

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey.org#872]
### What You Are Seeing?
Installing a package without `--pre` installs the latest pre-release version anyways.

### What is Expected?
Only stable versions are installed

### How Did You Get This To Happen? (Steps to Reproduce)
Attempt to install the latest package of selenium web driver for chrome, and got the pre-release version instead of stable.

**Comment by ferventcoder** [comment]
When we switched over in December to putting all versions in the Lucene Index, it appears we missed something important. That is reducing the selection based on prerelease or not. 
https://github.com/chocolatey/chocolatey.org/blob/47bb23f66f60935e97db04e68a9522143267cebf/chocolatey/Website/Infrastructure/Lucene/LuceneSearchService.cs#L81-L84

**Comment by ferventcoder** [comment]
Updated the filter. Let's see if that resolves the issue.
