### ISSUE TITLE
Edit package still has link to removed website nupkg upload page

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/chocolatey.org#894]
### What You Are Seeing?
After clicking  `Edit Package`, the pop up still has a link to the removed nupkg upload form.

![image](https://user-images.githubusercontent.com/38865330/83956233-4dbf6f00-a821-11ea-8316-b7a90153809b.png)

### What is Expected?

That the link is not there anymore.

### How Did You Get This To Happen? (Steps to Reproduce)

Click the edit package button on a page for package of which I am the maintainer.

**Comment by gep13** [comment]
@TheCakeIsNaOH we left the Upload page in place, with information about how packages should be uploaded going forward, i.e. to use `choco push`.  When they visit this page they will see:

![image](https://user-images.githubusercontent.com/1271146/83963330-260dec80-a89d-11ea-8f57-3ef041e01db6.png)

I think that leaving this page, and navigation to it, in tact makes sense, no?

**Comment by TheCakeIsNaOH** [comment]
I think it would make more sense to give that information about how to use choco push on the pop-up, instead of leaving a link to a deprecated page.

**Comment by TheCakeIsNaOH** [comment]
Closing as this is pretty much just a nitpick, and it does not seem others agree with me.
