### ISSUE TITLE
User who submitted a package version is missing in review comments section

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey.org#900]
### What You Are Seeing?

When a user submits a new package version (or update the existing one) chocolatey.org don't show which user that submitted this package (screenshot is at the end).

The comment seems to be added for a few hours when the website gets redeployed, but within the day it continues with not showing it again.

### What is Expected?

I would expect that the user that submitted the package version would be added as a comment in the review comments section every time the user submits a new/updated package version.

### How Did You Get This To Happen? (Steps to Reproduce)

Other than just pushing a new/updated package to chocolatey.org, I do not have any steps to reproduce.

### Screenshots

<details>
<summary>Missing submitted before re-deployment</summary>

https://chocolatey.org/packages/ccleaner/5.68.7820.20200625
![image](https://user-images.githubusercontent.com/1474648/85788050-a43b1180-b72c-11ea-8ee7-fd43fa5ea0e4.png)

</details>

<details>
<summary>Shown after re-deployment</summary>

https://chocolatey.org/packages/grafana/7.0.4
![image](https://user-images.githubusercontent.com/1474648/85788135-c46ad080-b72c-11ea-8e81-dc55557c2bc3.png)

</details>

<details>
<summary>Missing again several hours after re-deployment</summary>

https://chocolatey.org/packages/book-collector/20.3.1
![image](https://user-images.githubusercontent.com/1474648/85788254-f8de8c80-b72c-11ea-9ac3-d1735267dfc6.png)

</details>

**Comment by ferventcoder** [comment]
Is this still the case? We made some refactoring recently and I believe that should now be showing again. @gep13 for visibility

**Comment by AdmiringWorm** [comment]
@ferventcoder you are correct, the user that submitted the new package version is now showing up. (Completely forgot about this  issue).

**Comment by ferventcoder** [comment]
Just to tag the commit, that was https://github.com/chocolatey/chocolatey.org/commit/bfafdbef633b550ac9fd6cfc6c09a5f0ef30307c.
