### ISSUE TITLE
Software author(s) does not wrap on chromium based browsers

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/chocolatey.org#915]
### What You Are Seeing?

When the software author(s) field is long, it does not wrap onto multiple lines. 
Happens on chromium, chrome, and edge (chromium), all version 84. 

An example is keepassxc with a URL in the software authors field. 
https://chocolatey.org/packages/keepassxc
#### Detail
![image](https://user-images.githubusercontent.com/38865330/88305590-4c61dd00-cccf-11ea-8b16-b6f60dd9ef58.png)

#### In context
![image](https://user-images.githubusercontent.com/38865330/88305526-3eac5780-cccf-11ea-8923-e7eb1658ec2a.png)

### What is Expected?

The software authors field wraps in chromium like it does in firefox.
![image](https://user-images.githubusercontent.com/38865330/88307313-68667e00-ccd1-11ea-8ebf-c86953310a71.png)

### How Did You Get This To Happen? (Steps to Reproduce)

Open https://chocolatey.org/packages/keepassxc 
In chrome 84, chromium 84, or edge 84

**Comment by ferventcoder** [comment]
@designxsteph - see above.

**Comment by ferventcoder** [comment]
This has been merged and will be released on next website push.
