### ISSUE TITLE
Typo in front page of chocolately.org. Webinar announcement.

### ISSUE THREAD

**Issue by ahtee** [chocolatey/chocolatey.org#952]
### What You Are Seeing?

The front page of the site shows a webinar announcement. However, September is spelled incorrectly, at least for US english.
Tuesday, 22 Septemeber 2020

### What is Expected?

Tuesday, 22 September 2020

### How Did You Get This To Happen? (Steps to Reproduce)

visit chocolately.org and scroll down to view the webinar announcement under "Chocolatey Central Management Deployments". You can also search (`cntrl + f`) for "webinar".

**Comment by ahtee** [comment]
You are most welcome. Thanks for addressing so quickly! You're the best! Have a great day

**Comment by gep13** [comment]
@ahtee this has been deployed and is now live on the site.  Thanks for catching this!

**Comment by ahtee** [comment]
great! happy to help with this!!
