### ISSUE TITLE
Documentation URL's have unwanted `-` between letters and numbers

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#956]
### What You Are Seeing? 
The url:
 https://chocolatey.org/docs/quick-deployment-internet-setup-v-1

Should actually be:
https://chocolatey.org/docs/quick-deployment-internet-setup-v1

**Comment by ferventcoder** [comment]
what if it is `V1` as part of the naming convention? Would that be handled? This is important for @vexx32 and what he has done for the rest of the v1 docs on QDE (and that I asked him to switch direction, which may have been incorrect).

**Comment by designxsteph** [comment]
The file name I was going off of that is currently in the project is `QuickDeploymentInternetSetup-v1.md`. I see a PR in choco-wiki where there are files named like `QuickDeploymentSetupV1.md`. Which one are we planning on using? There needs to be some consistency in the naming convention, which I think is what you were after. If not we're always going to be adjusting how URL's are parsed and risk having wonky URL's unintentionally.

Currently a file named like `QuickDeploymentSetupV1.md` would render as `quick-deployment-setup-v-1`. This follows the rules we have set up because we also have a file named `ChocolateyInstallPS1.md` where a space is wanted (I think, at least thats how it's been) between the uppercase char and digit.

[With my fix,](https://github.com/chocolatey/chocolatey.org/pull/957/commits/062e487955c83f712bfe90e71c56912cb520a1f1) if the filename were to stay as the `QuickDeploymentInternetSetup-v1.md` naming convention, everything works without messing with that existing PS1 file. If we want to use the naming convention of `V1`, then maybe a fix would be to detect a `V` before a digit and exclude that from having a `-` added after it.

**Comment by vexx32** [comment]
Do we want `PS1` to be rendered as `PS-1`? It would be odd to me at least to see `PS1` rendered as `PS-1` since that's a file extension (i.e., it's referring a file named `ChocolateyInstall.ps1`).

But yeah, `V1` would be good to render without hyphens in it too.

Unsure of the best way to handle it. I don't really mind too much either way; as I understand it this is mainly to do with how we render URLs from the filenames, so as long as it's pretty consistent I don't think it's overly concerning. 🙂

**Comment by designxsteph** [comment]
@vexx32 @ferventcoder I was questioning if we wanted it to be `-ps-1` as well. It has always been this way. @ferventcoder should I update this to be `-ps1` and redirect the old link? Then I could simply make a rule to not insert a `-` before a digit.

**Comment by designxsteph** [comment]
I went ahead and added this fix in to remove a `-` between a letter and a number, and added a redirect for `ps-1` to `ps1`.  I did this as an additional commit on https://github.com/chocolatey/chocolatey.org/pull/957, so if this is the route we want to go, I will fix this up into the previous commit on that PR and update this issue.

**Comment by designxsteph** [comment]
Based on the thumbs up on my above comment I fixed up my PR and this should be good to go now! https://github.com/chocolatey/chocolatey.org/pull/957
