### ISSUE TITLE
Prev/Next Buttons Do Not Work on Carousels

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#960]
### What You Are Seeing? 
The previous/next buttons are not working on any of the carousel items. When clicked, they do nothing, or freeze the carousel.

### What is Expected?
I would expect the buttons to work and move to the next slide.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Go to the home page and click the prev/next buttons on the carousel item located under the webinar announcement (or any carousel on any page).

**Comment by gep13** [comment]
@designxsteph this has been deployed, and is now live on chocolatey.org
