### ISSUE TITLE
Convert Documentation to PDF

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#963]
### What You Are Seeing? 
It would be nice to be able to convert the documentation files into a PDF that can be printed off for later use.

### What is Expected?
A download PDF button to be present on each documentation page that when clicked, would download the page as PDF.

**Comment by gep13** [comment]
I am going to go ahead and close this out, and I have got a new issue to track this here: https://github.com/chocolatey/docs/issues/85
