### ISSUE TITLE
QDE v1 links need added to left side navigation in documentation area

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/chocolatey.org#965]
### What You Are Seeing? 
The QDE documentation was recently updated to v2, but there is no navigation links to the v1 docs in the left side navigation in the documentation area.

### What is Expected?
I would expect any version of the documentation to be available, incase a user has not upgraded and needs to find documentation relating to their current setup.

### How Did You Get This To Happen? (Steps to Reproduce)
Visit: https://chocolatey.org/docs/quick-deployment-setup-v1 and notice how the navigation on the left does not expand and nothing is highlighted.

**Comment by ferventcoder** [comment]
This still needs pushed out.
