### ISSUE TITLE
Create a security.txt for folks who prefer to learn how to report security vulnerabilities that way

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey.org#970]
Security researchers have a working draft for a way to better find out how to report vulnerabilities at https://tools.ietf.org/html/draft-foudil-securitytxt-10. 

Basically it is to include a file at https://chocolatey.org/.well-known/security.txt (and ensure https://chocolatey.org/security.txt redirects to that).

The contents of the file (based on the output from https://securitytxt.org/) will look as thus:

~~~
Contact: mailto:security@chocolatey.io
Preferred-Languages: en
Canonical: https://chocolatey.org/.well-known/security.txt
Policy: https://chocolatey.org/security
~~~

We can go back later and add keys.

**Comment by ferventcoder** [comment]
This should echo in a more succinct form what we have at https://chocolatey.org/security

**Comment by AdmiringWorm** [comment]
May I also perhaps suggest a [humans.txt](http://humanstxt.org/) file as well?

> It's an initiative for knowing the people behind a website. It's a TXT file that contains information about the different people who have contributed to building the website.

Nothing to do with security though, but could be interesting for people that want to know who is behind the website for instance.

**Comment by designxsteph** [comment]
@AdmiringWorm good suggestion! Would you mind opening up a new enhancement issue for this so we can keep track of it better? Thanks!

**Comment by AdmiringWorm** [comment]
Sure thing, on it.

**Comment by AdmiringWorm** [comment]
@designxsteph opened the issue here: #983
