### ISSUE TITLE
Link Chocolatey Workshop at OSAD Munich

### ISSUE THREAD

**Issue by mwallner** [chocolatey/chocolatey.org#981]
There's going to be a online Chocolatey Workshop at Open Source Automation Days Munich.

* https://osad-munich.org/en/workshops/chocolatey-package-manager-workshop/

it would be nice to have it listed on https://chocolatey.org/events

**Comment by designxsteph** [comment]
Hi @mwallner! Looking to get this added. I see the event is on 19.10.2020, but is there a specific time for this workshop that I can add as well? Thanks!

**Comment by gep13** [comment]
@mwallner this has been deployed: https://chocolatey.org/events
