### ISSUE TITLE
Choco list <package> -e -a -r return only latest version of package

### ISSUE THREAD

**Issue by romandolinsky** [chocolatey/chocolatey.org#999]
When I use choco list <package> -e -a -r, chocolatey return only the latest version of a specific package. 
-e argument - Exact - Only return packages with this exact name
-a argument - AllVersions - include results from all versions.

What is Expected:
When I use argument combination -e -a I will receive a tool list with the exact name and different versions. Because -a argument return list of tools with the same or similar name. 

Example: 
contend of package repo:
keil 1.0
keil 2.0
keil 3.0
keil_idontknow 1.0
keil_idontknow 2.0

cmd:
choco list/search keil -e -a -r

Actual situation:
cmd return:
keil|3.0

Expected situation:
cmd return:
keil|1.0
keil|2.0
keil|3.0

**Comment by ferventcoder** [comment]
This is an issue with choco, and one that is fixed by the beta release. You might give that a shot. The repo for choco is https://github.com/chocolatey/choco.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/1843 is the issue you are looking for. 👍
